import { JsonConsoleLogger, LocalSecretService, LocalVariablesService, NoopAuditService } from '@pikku/core/services'
import { pikkuServices } from '../.pikku/pikku-types.gen.js'
import { TypedSecretService } from '../.pikku/secrets/pikku-secrets.gen.js'
import { TypedVariablesService } from '../.pikku/variables/pikku-variables.gen.js'
import { CFWorkerSchemaService } from '@pikku/schema-cfworker'
import { Kysely, CamelCasePlugin } from 'kysely'
import { LibsqlWebDialect } from '@pikku/kysely-sqlite'
import { FakePaymentService } from './services/fake-payment.js'
import type { DB } from './types/db.types.js'

// @snippet start shopServices
export const createSingletonServices = pikkuServices(async (config, existingServices) => {
  const variables =
    existingServices?.variables ?? new TypedVariablesService(new LocalVariablesService())
  const secrets =
    existingServices?.secrets ?? new TypedSecretService(new LocalSecretService(variables))
  const logger = existingServices?.logger ?? new JsonConsoleLogger()
  const schema = existingServices?.schema ?? new CFWorkerSchemaService(logger)
  const paymentService = existingServices?.paymentService ?? new FakePaymentService()

  // In CF Workers DATABASE_URL is injected by Fabric.
  // In local dev (pikku dev) existingServices.kysely is the node:sqlite instance.
  // In tests existingServices.kysely is provided by the test support layer.
  let kysely: Kysely<DB> | undefined
  if (existingServices?.kysely) {
    kysely = existingServices.kysely as Kysely<DB>
  } else {
    const databaseUrl = await variables.get('DATABASE_URL')
    if (databaseUrl) {
      if (/^postgres(ql)?:\/\//.test(databaseUrl)) {
        const [{ PostgresJSDialect }, postgres] = await Promise.all([
          import('kysely-postgres-js'),
          import('postgres'),
        ])
        kysely = new Kysely<DB>({
          dialect: new PostgresJSDialect({ postgres: postgres.default(databaseUrl) }),
          plugins: [new CamelCasePlugin()],
        })
      } else {
        kysely = new Kysely<DB>({
          dialect: new LibsqlWebDialect({ url: databaseUrl }),
          plugins: [new CamelCasePlugin()],
        })
      }
    } else {
      throw new Error('kysely not provided: set DATABASE_URL or pass kysely via existingServices')
    }
  }

  return {
    ...(existingServices ?? {}),
    config,
    variables,
    secrets,
    logger,
    schema,
    kysely,
    paymentService,
    audit: existingServices?.audit ?? new NoopAuditService(),
  }
})
// @snippet end shopServices

// @snippet start shopWireServices
import { pikkuWireServices } from '../.pikku/pikku-types.gen.js'

export const createWireServices = pikkuWireServices(
  async (_singletonServices, _wire) => {
    // Created fresh per HTTP request, queue job, CLI command, or WebSocket lifetime.
    // Pikku merges these with singletons so functions see one flat object.
    // Add per-request services here — e.g. scoped loggers, transactions, etc.
    return {}
  }
)
// @snippet end shopWireServices

// @snippet start shopDynamicImport
import { requiredSingletonServices } from '../.pikku/pikku-services.gen.js'

// requiredSingletonServices is a map of booleans generated by pikku.
// If a service is false, no wired function needs it — safe to skip.
if (requiredSingletonServices.kysely) {
  // Dynamic import only when actually needed — skip on cold starts that don't use DB
  const { Kysely, CamelCasePlugin } = await import('kysely')
  void Kysely, CamelCasePlugin // referenced to satisfy linter in snippet context
}
// @snippet end shopDynamicImport
