/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { pikkuState } from '@pikku/core/ecosystem'
import { GatewaysMeta } from '@pikku/core/gateway'
import metaData from './pikku-gateway-wirings-meta.gen.json' with { type: 'json' }

pikkuState(null, 'gateway', 'meta', metaData as GatewaysMeta)