/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { addAIAgent } from '@pikku/core/ai-agent'
import './pikku-agent-wirings-meta.gen.js'
import { checkoutAssistant } from '../../src/wirings/shop.bot.js'
import { opsAgent } from '../../src/wirings/shop.bot.js'
import { shopAssistant } from '../../src/wirings/shop.bot.js'

addAIAgent('checkoutAssistant', checkoutAssistant)
addAIAgent('opsAgent', opsAgent)
addAIAgent('shopAssistant', shopAssistant)