/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { addSchema } from '@pikku/core/schema'

import * as AddToBasketInput from './schemas/AddToBasketInput.schema.json' with { type: 'json' }
addSchema('AddToBasketInput', AddToBasketInput)


import * as AddToBasketOutput from './schemas/AddToBasketOutput.schema.json' with { type: 'json' }
addSchema('AddToBasketOutput', AddToBasketOutput)


import * as AgentApproveCallerInput from './schemas/AgentApproveCallerInput.schema.json' with { type: 'json' }
addSchema('AgentApproveCallerInput', AgentApproveCallerInput)


import * as AgentCallerInput from './schemas/AgentCallerInput.schema.json' with { type: 'json' }
addSchema('AgentCallerInput', AgentCallerInput)


import * as AgentResumeCallerInput from './schemas/AgentResumeCallerInput.schema.json' with { type: 'json' }
addSchema('AgentResumeCallerInput', AgentResumeCallerInput)


import * as AgentStreamCallerInput from './schemas/AgentStreamCallerInput.schema.json' with { type: 'json' }
addSchema('AgentStreamCallerInput', AgentStreamCallerInput)


import * as AuthHandlerOutput from './schemas/AuthHandlerOutput.schema.json' with { type: 'json' }
addSchema('AuthHandlerOutput', AuthHandlerOutput)


import * as CancelOrderInput from './schemas/CancelOrderInput.schema.json' with { type: 'json' }
addSchema('CancelOrderInput', CancelOrderInput)


import * as CancelOrderOutput from './schemas/CancelOrderOutput.schema.json' with { type: 'json' }
addSchema('CancelOrderOutput', CancelOrderOutput)


import * as CancelOrderToolInput from './schemas/CancelOrderToolInput.schema.json' with { type: 'json' }
addSchema('CancelOrderToolInput', CancelOrderToolInput)


import * as CancelOrderToolOutput from './schemas/CancelOrderToolOutput.schema.json' with { type: 'json' }
addSchema('CancelOrderToolOutput', CancelOrderToolOutput)


import * as DeleteAgentThreadInput from './schemas/DeleteAgentThreadInput.schema.json' with { type: 'json' }
addSchema('DeleteAgentThreadInput', DeleteAgentThreadInput)


import * as DeleteAgentThreadOutput from './schemas/DeleteAgentThreadOutput.schema.json' with { type: 'json' }
addSchema('DeleteAgentThreadOutput', DeleteAgentThreadOutput)


import * as GetAgentThreadMessagesInput from './schemas/GetAgentThreadMessagesInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadMessagesInput', GetAgentThreadMessagesInput)


import * as GetAgentThreadMessagesOutput from './schemas/GetAgentThreadMessagesOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadMessagesOutput', GetAgentThreadMessagesOutput)


import * as GetAgentThreadRunsInput from './schemas/GetAgentThreadRunsInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadRunsInput', GetAgentThreadRunsInput)


import * as GetAgentThreadRunsOutput from './schemas/GetAgentThreadRunsOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadRunsOutput', GetAgentThreadRunsOutput)


import * as GetAgentThreadsInput from './schemas/GetAgentThreadsInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadsInput', GetAgentThreadsInput)


import * as GetAgentThreadsOutput from './schemas/GetAgentThreadsOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadsOutput', GetAgentThreadsOutput)


import * as GetSessionInput from './schemas/GetSessionInput.schema.json' with { type: 'json' }
addSchema('GetSessionInput', GetSessionInput)


import * as GetSessionOutput from './schemas/GetSessionOutput.schema.json' with { type: 'json' }
addSchema('GetSessionOutput', GetSessionOutput)


import * as GraphStarterInput from './schemas/GraphStarterInput.schema.json' with { type: 'json' }
addSchema('GraphStarterInput', GraphStarterInput)


import * as GraphStarterOutput from './schemas/GraphStarterOutput.schema.json' with { type: 'json' }
addSchema('GraphStarterOutput', GraphStarterOutput)


import * as ListItemsInput from './schemas/ListItemsInput.schema.json' with { type: 'json' }
addSchema('ListItemsInput', ListItemsInput)


import * as ListItemsOutput from './schemas/ListItemsOutput.schema.json' with { type: 'json' }
addSchema('ListItemsOutput', ListItemsOutput)


import * as ListItemsToolInput from './schemas/ListItemsToolInput.schema.json' with { type: 'json' }
addSchema('ListItemsToolInput', ListItemsToolInput)


import * as ListItemsToolOutput from './schemas/ListItemsToolOutput.schema.json' with { type: 'json' }
addSchema('ListItemsToolOutput', ListItemsToolOutput)


import * as MCPToolResponse from './schemas/MCPToolResponse.schema.json' with { type: 'json' }
addSchema('MCPToolResponse', MCPToolResponse)


import * as PikkuConsoleGetSecretInput from './schemas/PikkuConsoleGetSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetSecretInput', PikkuConsoleGetSecretInput)


import * as PikkuConsoleGetSecretOutput from './schemas/PikkuConsoleGetSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetSecretOutput', PikkuConsoleGetSecretOutput)


import * as PikkuConsoleGetVariableInput from './schemas/PikkuConsoleGetVariableInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetVariableInput', PikkuConsoleGetVariableInput)


import * as PikkuConsoleGetVariableOutput from './schemas/PikkuConsoleGetVariableOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetVariableOutput', PikkuConsoleGetVariableOutput)


import * as PikkuConsoleHasSecretInput from './schemas/PikkuConsoleHasSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleHasSecretInput', PikkuConsoleHasSecretInput)


import * as PikkuConsoleHasSecretOutput from './schemas/PikkuConsoleHasSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleHasSecretOutput', PikkuConsoleHasSecretOutput)


import * as PikkuConsoleSetSecretInput from './schemas/PikkuConsoleSetSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetSecretInput', PikkuConsoleSetSecretInput)


import * as PikkuConsoleSetSecretOutput from './schemas/PikkuConsoleSetSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetSecretOutput', PikkuConsoleSetSecretOutput)


import * as PikkuConsoleSetVariableInput from './schemas/PikkuConsoleSetVariableInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetVariableInput', PikkuConsoleSetVariableInput)


import * as PikkuConsoleSetVariableOutput from './schemas/PikkuConsoleSetVariableOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetVariableOutput', PikkuConsoleSetVariableOutput)


import * as RealtimeEventStreamInput from './schemas/RealtimeEventStreamInput.schema.json' with { type: 'json' }
addSchema('RealtimeEventStreamInput', RealtimeEventStreamInput)


import * as RealtimeSubscribeInput from './schemas/RealtimeSubscribeInput.schema.json' with { type: 'json' }
addSchema('RealtimeSubscribeInput', RealtimeSubscribeInput)


import * as RealtimeUnsubscribeInput from './schemas/RealtimeUnsubscribeInput.schema.json' with { type: 'json' }
addSchema('RealtimeUnsubscribeInput', RealtimeUnsubscribeInput)


import * as RecordAnalyticsEventsInput from './schemas/RecordAnalyticsEventsInput.schema.json' with { type: 'json' }
addSchema('RecordAnalyticsEventsInput', RecordAnalyticsEventsInput)


import * as RecordAnalyticsEventsOutput from './schemas/RecordAnalyticsEventsOutput.schema.json' with { type: 'json' }
addSchema('RecordAnalyticsEventsOutput', RecordAnalyticsEventsOutput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as SecretSchema_betterAuthSecret from './schemas/SecretSchema_betterAuthSecret.schema.json' with { type: 'json' }
addSchema('SecretSchema_betterAuthSecret', SecretSchema_betterAuthSecret)


import * as SecretSchema_scenarioActorSecret from './schemas/SecretSchema_scenarioActorSecret.schema.json' with { type: 'json' }
addSchema('SecretSchema_scenarioActorSecret', SecretSchema_scenarioActorSecret)


import * as SendOrderConfirmationInput from './schemas/SendOrderConfirmationInput.schema.json' with { type: 'json' }
addSchema('SendOrderConfirmationInput', SendOrderConfirmationInput)


import * as StreamWorkflowRunInput from './schemas/StreamWorkflowRunInput.schema.json' with { type: 'json' }
addSchema('StreamWorkflowRunInput', StreamWorkflowRunInput)


import * as VariableSchema_corsOrigins from './schemas/VariableSchema_corsOrigins.schema.json' with { type: 'json' }
addSchema('VariableSchema_corsOrigins', VariableSchema_corsOrigins)


import * as VariableSchema_frontendUrl from './schemas/VariableSchema_frontendUrl.schema.json' with { type: 'json' }
addSchema('VariableSchema_frontendUrl', VariableSchema_frontendUrl)


import * as WatchOrderInput from './schemas/WatchOrderInput.schema.json' with { type: 'json' }
addSchema('WatchOrderInput', WatchOrderInput)


import * as WorkflowApproverInput from './schemas/WorkflowApproverInput.schema.json' with { type: 'json' }
addSchema('WorkflowApproverInput', WorkflowApproverInput)


import * as WorkflowApproverOutput from './schemas/WorkflowApproverOutput.schema.json' with { type: 'json' }
addSchema('WorkflowApproverOutput', WorkflowApproverOutput)


import * as WorkflowRunStatus from './schemas/WorkflowRunStatus.schema.json' with { type: 'json' }
addSchema('WorkflowRunStatus', WorkflowRunStatus)


import * as WorkflowRunnerInput from './schemas/WorkflowRunnerInput.schema.json' with { type: 'json' }
addSchema('WorkflowRunnerInput', WorkflowRunnerInput)


import * as WorkflowStarterInput from './schemas/WorkflowStarterInput.schema.json' with { type: 'json' }
addSchema('WorkflowStarterInput', WorkflowStarterInput)


import * as WorkflowStarterOutput from './schemas/WorkflowStarterOutput.schema.json' with { type: 'json' }
addSchema('WorkflowStarterOutput', WorkflowStarterOutput)


import * as WorkflowStatusCheckerInput from './schemas/WorkflowStatusCheckerInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusCheckerInput', WorkflowStatusCheckerInput)


import * as WorkflowStatusStreamFullInput from './schemas/WorkflowStatusStreamFullInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusStreamFullInput', WorkflowStatusStreamFullInput)


import * as WorkflowStatusStreamInput from './schemas/WorkflowStatusStreamInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusStreamInput', WorkflowStatusStreamInput)
