/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { addSchema } from '@pikku/core/schema'

import * as AIAgentInput from './schemas/AIAgentInput.schema.json' with { type: 'json' }
addSchema('AIAgentInput', AIAgentInput)


import * as AddToBasketInput from './schemas/AddToBasketInput.schema.json' with { type: 'json' }
addSchema('AddToBasketInput', AddToBasketInput)


import * as AgentApproveCallerInput from './schemas/AgentApproveCallerInput.schema.json' with { type: 'json' }
addSchema('AgentApproveCallerInput', AgentApproveCallerInput)


import * as AgentCallerInput from './schemas/AgentCallerInput.schema.json' with { type: 'json' }
addSchema('AgentCallerInput', AgentCallerInput)


import * as AgentCallerOutput from './schemas/AgentCallerOutput.schema.json' with { type: 'json' }
addSchema('AgentCallerOutput', AgentCallerOutput)


import * as AgentResumeCallerInput from './schemas/AgentResumeCallerInput.schema.json' with { type: 'json' }
addSchema('AgentResumeCallerInput', AgentResumeCallerInput)


import * as AgentStreamCallerInput from './schemas/AgentStreamCallerInput.schema.json' with { type: 'json' }
addSchema('AgentStreamCallerInput', AgentStreamCallerInput)


import * as AuthHandlerOutput from './schemas/AuthHandlerOutput.schema.json' with { type: 'json' }
addSchema('AuthHandlerOutput', AuthHandlerOutput)


import * as CancelOrderInput from './schemas/CancelOrderInput.schema.json' with { type: 'json' }
addSchema('CancelOrderInput', CancelOrderInput)


import * as ChargeCardInput from './schemas/ChargeCardInput.schema.json' with { type: 'json' }
addSchema('ChargeCardInput', ChargeCardInput)


import * as ChargeCardOutput from './schemas/ChargeCardOutput.schema.json' with { type: 'json' }
addSchema('ChargeCardOutput', ChargeCardOutput)


import * as CheckItemAvailabilityInput from './schemas/CheckItemAvailabilityInput.schema.json' with { type: 'json' }
addSchema('CheckItemAvailabilityInput', CheckItemAvailabilityInput)


import * as CheckItemAvailabilityOutput from './schemas/CheckItemAvailabilityOutput.schema.json' with { type: 'json' }
addSchema('CheckItemAvailabilityOutput', CheckItemAvailabilityOutput)


import * as CheckOrderRefundableInput from './schemas/CheckOrderRefundableInput.schema.json' with { type: 'json' }
addSchema('CheckOrderRefundableInput', CheckOrderRefundableInput)


import * as CheckOrderRefundableOutput from './schemas/CheckOrderRefundableOutput.schema.json' with { type: 'json' }
addSchema('CheckOrderRefundableOutput', CheckOrderRefundableOutput)


import * as CheckoutWorkflowInput from './schemas/CheckoutWorkflowInput.schema.json' with { type: 'json' }
addSchema('CheckoutWorkflowInput', CheckoutWorkflowInput)


import * as CheckoutWorkflowOutput from './schemas/CheckoutWorkflowOutput.schema.json' with { type: 'json' }
addSchema('CheckoutWorkflowOutput', CheckoutWorkflowOutput)


import * as CreateCategoryInput from './schemas/CreateCategoryInput.schema.json' with { type: 'json' }
addSchema('CreateCategoryInput', CreateCategoryInput)


import * as CreateCategoryOutput from './schemas/CreateCategoryOutput.schema.json' with { type: 'json' }
addSchema('CreateCategoryOutput', CreateCategoryOutput)


import * as CreateItemInput from './schemas/CreateItemInput.schema.json' with { type: 'json' }
addSchema('CreateItemInput', CreateItemInput)


import * as CreateItemOutput from './schemas/CreateItemOutput.schema.json' with { type: 'json' }
addSchema('CreateItemOutput', CreateItemOutput)


import * as CreateOrderInput from './schemas/CreateOrderInput.schema.json' with { type: 'json' }
addSchema('CreateOrderInput', CreateOrderInput)


import * as CreateOrderOutput from './schemas/CreateOrderOutput.schema.json' with { type: 'json' }
addSchema('CreateOrderOutput', CreateOrderOutput)


import * as CreateOrderRecordInput from './schemas/CreateOrderRecordInput.schema.json' with { type: 'json' }
addSchema('CreateOrderRecordInput', CreateOrderRecordInput)


import * as CreateOrderRecordOutput from './schemas/CreateOrderRecordOutput.schema.json' with { type: 'json' }
addSchema('CreateOrderRecordOutput', CreateOrderRecordOutput)


import * as CreateOrderWithValidationInput from './schemas/CreateOrderWithValidationInput.schema.json' with { type: 'json' }
addSchema('CreateOrderWithValidationInput', CreateOrderWithValidationInput)


import * as CreateOrderWithValidationOutput from './schemas/CreateOrderWithValidationOutput.schema.json' with { type: 'json' }
addSchema('CreateOrderWithValidationOutput', CreateOrderWithValidationOutput)


import * as DeleteAgentThreadInput from './schemas/DeleteAgentThreadInput.schema.json' with { type: 'json' }
addSchema('DeleteAgentThreadInput', DeleteAgentThreadInput)


import * as DeleteAgentThreadOutput from './schemas/DeleteAgentThreadOutput.schema.json' with { type: 'json' }
addSchema('DeleteAgentThreadOutput', DeleteAgentThreadOutput)


import * as DeleteOrderInput from './schemas/DeleteOrderInput.schema.json' with { type: 'json' }
addSchema('DeleteOrderInput', DeleteOrderInput)


import * as FinalizeOrderInput from './schemas/FinalizeOrderInput.schema.json' with { type: 'json' }
addSchema('FinalizeOrderInput', FinalizeOrderInput)


import * as GetAgentThreadMessagesInput from './schemas/GetAgentThreadMessagesInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadMessagesInput', GetAgentThreadMessagesInput)


import * as GetAgentThreadMessagesOutput from './schemas/GetAgentThreadMessagesOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadMessagesOutput', GetAgentThreadMessagesOutput)


import * as GetAgentThreadRunsInput from './schemas/GetAgentThreadRunsInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadRunsInput', GetAgentThreadRunsInput)


import * as GetAgentThreadRunsOutput from './schemas/GetAgentThreadRunsOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadRunsOutput', GetAgentThreadRunsOutput)


import * as GetAgentThreadsInput from './schemas/GetAgentThreadsInput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadsInput', GetAgentThreadsInput)


import * as GetAgentThreadsOutput from './schemas/GetAgentThreadsOutput.schema.json' with { type: 'json' }
addSchema('GetAgentThreadsOutput', GetAgentThreadsOutput)


import * as GetBasketInput from './schemas/GetBasketInput.schema.json' with { type: 'json' }
addSchema('GetBasketInput', GetBasketInput)


import * as GetBasketOutput from './schemas/GetBasketOutput.schema.json' with { type: 'json' }
addSchema('GetBasketOutput', GetBasketOutput)


import * as GetItemForAIInput from './schemas/GetItemForAIInput.schema.json' with { type: 'json' }
addSchema('GetItemForAIInput', GetItemForAIInput)


import * as GetItemForAIOutput from './schemas/GetItemForAIOutput.schema.json' with { type: 'json' }
addSchema('GetItemForAIOutput', GetItemForAIOutput)


import * as GetItemInput from './schemas/GetItemInput.schema.json' with { type: 'json' }
addSchema('GetItemInput', GetItemInput)


import * as GetItemOutput from './schemas/GetItemOutput.schema.json' with { type: 'json' }
addSchema('GetItemOutput', GetItemOutput)


import * as GetItemToolInput from './schemas/GetItemToolInput.schema.json' with { type: 'json' }
addSchema('GetItemToolInput', GetItemToolInput)


import * as GetItemToolOutput from './schemas/GetItemToolOutput.schema.json' with { type: 'json' }
addSchema('GetItemToolOutput', GetItemToolOutput)


import * as GetItemV1Input from './schemas/GetItemV1Input.schema.json' with { type: 'json' }
addSchema('GetItemV1Input', GetItemV1Input)


import * as GetItemV1Output from './schemas/GetItemV1Output.schema.json' with { type: 'json' }
addSchema('GetItemV1Output', GetItemV1Output)


import * as GetItemV2Input from './schemas/GetItemV2Input.schema.json' with { type: 'json' }
addSchema('GetItemV2Input', GetItemV2Input)


import * as GetItemV2Output from './schemas/GetItemV2Output.schema.json' with { type: 'json' }
addSchema('GetItemV2Output', GetItemV2Output)


import * as GetOrderInput from './schemas/GetOrderInput.schema.json' with { type: 'json' }
addSchema('GetOrderInput', GetOrderInput)


import * as GetOrderOutput from './schemas/GetOrderOutput.schema.json' with { type: 'json' }
addSchema('GetOrderOutput', GetOrderOutput)


import * as GetOrderThreeParamsInput from './schemas/GetOrderThreeParamsInput.schema.json' with { type: 'json' }
addSchema('GetOrderThreeParamsInput', GetOrderThreeParamsInput)


import * as GetOrderThreeParamsOutput from './schemas/GetOrderThreeParamsOutput.schema.json' with { type: 'json' }
addSchema('GetOrderThreeParamsOutput', GetOrderThreeParamsOutput)


import * as GetProfileOutput from './schemas/GetProfileOutput.schema.json' with { type: 'json' }
addSchema('GetProfileOutput', GetProfileOutput)


import * as GraphStarterInput from './schemas/GraphStarterInput.schema.json' with { type: 'json' }
addSchema('GraphStarterInput', GraphStarterInput)


import * as GraphStarterOutput from './schemas/GraphStarterOutput.schema.json' with { type: 'json' }
addSchema('GraphStarterOutput', GraphStarterOutput)


import * as HandlePaymentWebhookInput from './schemas/HandlePaymentWebhookInput.schema.json' with { type: 'json' }
addSchema('HandlePaymentWebhookInput', HandlePaymentWebhookInput)


import * as HandlePaymentWebhookOutput from './schemas/HandlePaymentWebhookOutput.schema.json' with { type: 'json' }
addSchema('HandlePaymentWebhookOutput', HandlePaymentWebhookOutput)


import * as HttpPostAgentsShopOutput from './schemas/HttpPostAgentsShopOutput.schema.json' with { type: 'json' }
addSchema('HttpPostAgentsShopOutput', HttpPostAgentsShopOutput)


import * as HttpPostAgentsShopStreamInput from './schemas/HttpPostAgentsShopStreamInput.schema.json' with { type: 'json' }
addSchema('HttpPostAgentsShopStreamInput', HttpPostAgentsShopStreamInput)


import * as IssueRefundInput from './schemas/IssueRefundInput.schema.json' with { type: 'json' }
addSchema('IssueRefundInput', IssueRefundInput)


import * as ListCategoriesOutput from './schemas/ListCategoriesOutput.schema.json' with { type: 'json' }
addSchema('ListCategoriesOutput', ListCategoriesOutput)


import * as ListCategoriesToolOutput from './schemas/ListCategoriesToolOutput.schema.json' with { type: 'json' }
addSchema('ListCategoriesToolOutput', ListCategoriesToolOutput)


import * as ListItemsInput from './schemas/ListItemsInput.schema.json' with { type: 'json' }
addSchema('ListItemsInput', ListItemsInput)


import * as ListItemsOutput from './schemas/ListItemsOutput.schema.json' with { type: 'json' }
addSchema('ListItemsOutput', ListItemsOutput)


import * as ListItemsToolInput from './schemas/ListItemsToolInput.schema.json' with { type: 'json' }
addSchema('ListItemsToolInput', ListItemsToolInput)


import * as ListItemsToolOutput from './schemas/ListItemsToolOutput.schema.json' with { type: 'json' }
addSchema('ListItemsToolOutput', ListItemsToolOutput)


import * as ListOrdersInput from './schemas/ListOrdersInput.schema.json' with { type: 'json' }
addSchema('ListOrdersInput', ListOrdersInput)


import * as ListOrdersOutput from './schemas/ListOrdersOutput.schema.json' with { type: 'json' }
addSchema('ListOrdersOutput', ListOrdersOutput)


import * as MCPToolResponse from './schemas/MCPToolResponse.schema.json' with { type: 'json' }
addSchema('MCPToolResponse', MCPToolResponse)


import * as NotifyOrderShippedInput from './schemas/NotifyOrderShippedInput.schema.json' with { type: 'json' }
addSchema('NotifyOrderShippedInput', NotifyOrderShippedInput)


import * as OnLowStockInput from './schemas/OnLowStockInput.schema.json' with { type: 'json' }
addSchema('OnLowStockInput', OnLowStockInput)


import * as PikkuConsoleGetSecretInput from './schemas/PikkuConsoleGetSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetSecretInput', PikkuConsoleGetSecretInput)


import * as PikkuConsoleGetSecretOutput from './schemas/PikkuConsoleGetSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetSecretOutput', PikkuConsoleGetSecretOutput)


import * as PikkuConsoleGetVariableInput from './schemas/PikkuConsoleGetVariableInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetVariableInput', PikkuConsoleGetVariableInput)


import * as PikkuConsoleGetVariableOutput from './schemas/PikkuConsoleGetVariableOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleGetVariableOutput', PikkuConsoleGetVariableOutput)


import * as PikkuConsoleHasSecretInput from './schemas/PikkuConsoleHasSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleHasSecretInput', PikkuConsoleHasSecretInput)


import * as PikkuConsoleHasSecretOutput from './schemas/PikkuConsoleHasSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleHasSecretOutput', PikkuConsoleHasSecretOutput)


import * as PikkuConsoleSetSecretInput from './schemas/PikkuConsoleSetSecretInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetSecretInput', PikkuConsoleSetSecretInput)


import * as PikkuConsoleSetSecretOutput from './schemas/PikkuConsoleSetSecretOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetSecretOutput', PikkuConsoleSetSecretOutput)


import * as PikkuConsoleSetVariableInput from './schemas/PikkuConsoleSetVariableInput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetVariableInput', PikkuConsoleSetVariableInput)


import * as PikkuConsoleSetVariableOutput from './schemas/PikkuConsoleSetVariableOutput.schema.json' with { type: 'json' }
addSchema('PikkuConsoleSetVariableOutput', PikkuConsoleSetVariableOutput)


import * as PlaceOrderInput from './schemas/PlaceOrderInput.schema.json' with { type: 'json' }
addSchema('PlaceOrderInput', PlaceOrderInput)


import * as PlaceOrderOutput from './schemas/PlaceOrderOutput.schema.json' with { type: 'json' }
addSchema('PlaceOrderOutput', PlaceOrderOutput)


import * as ProcessExportInput from './schemas/ProcessExportInput.schema.json' with { type: 'json' }
addSchema('ProcessExportInput', ProcessExportInput)


import * as ProcessPaymentInput from './schemas/ProcessPaymentInput.schema.json' with { type: 'json' }
addSchema('ProcessPaymentInput', ProcessPaymentInput)


import * as ProcessPaymentOutput from './schemas/ProcessPaymentOutput.schema.json' with { type: 'json' }
addSchema('ProcessPaymentOutput', ProcessPaymentOutput)


import * as RefundWorkflowInput from './schemas/RefundWorkflowInput.schema.json' with { type: 'json' }
addSchema('RefundWorkflowInput', RefundWorkflowInput)


import * as RefundWorkflowOutput from './schemas/RefundWorkflowOutput.schema.json' with { type: 'json' }
addSchema('RefundWorkflowOutput', RefundWorkflowOutput)


import * as RemoveFromBasketInput from './schemas/RemoveFromBasketInput.schema.json' with { type: 'json' }
addSchema('RemoveFromBasketInput', RemoveFromBasketInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as SecretSchema_betterAuthSecret from './schemas/SecretSchema_betterAuthSecret.schema.json' with { type: 'json' }
addSchema('SecretSchema_betterAuthSecret', SecretSchema_betterAuthSecret)


import * as SecretSchema_stripeSecretKey from './schemas/SecretSchema_stripeSecretKey.schema.json' with { type: 'json' }
addSchema('SecretSchema_stripeSecretKey', SecretSchema_stripeSecretKey)


import * as SendOrderConfirmationInput from './schemas/SendOrderConfirmationInput.schema.json' with { type: 'json' }
addSchema('SendOrderConfirmationInput', SendOrderConfirmationInput)


import * as StartCheckoutInput from './schemas/StartCheckoutInput.schema.json' with { type: 'json' }
addSchema('StartCheckoutInput', StartCheckoutInput)


import * as StartCheckoutOutput from './schemas/StartCheckoutOutput.schema.json' with { type: 'json' }
addSchema('StartCheckoutOutput', StartCheckoutOutput)


import * as StockPollTriggerInput from './schemas/StockPollTriggerInput.schema.json' with { type: 'json' }
addSchema('StockPollTriggerInput', StockPollTriggerInput)


import * as StockPollTriggerOutput from './schemas/StockPollTriggerOutput.schema.json' with { type: 'json' }
addSchema('StockPollTriggerOutput', StockPollTriggerOutput)


import * as StreamWorkflowRunInput from './schemas/StreamWorkflowRunInput.schema.json' with { type: 'json' }
addSchema('StreamWorkflowRunInput', StreamWorkflowRunInput)


import * as SubscribeToOrderInput from './schemas/SubscribeToOrderInput.schema.json' with { type: 'json' }
addSchema('SubscribeToOrderInput', SubscribeToOrderInput)


import * as UnsubscribeFromOrderInput from './schemas/UnsubscribeFromOrderInput.schema.json' with { type: 'json' }
addSchema('UnsubscribeFromOrderInput', UnsubscribeFromOrderInput)


import * as UpdateItemInput from './schemas/UpdateItemInput.schema.json' with { type: 'json' }
addSchema('UpdateItemInput', UpdateItemInput)


import * as UpdateStockToolInput from './schemas/UpdateStockToolInput.schema.json' with { type: 'json' }
addSchema('UpdateStockToolInput', UpdateStockToolInput)


import * as UpdateStockToolOutput from './schemas/UpdateStockToolOutput.schema.json' with { type: 'json' }
addSchema('UpdateStockToolOutput', UpdateStockToolOutput)


import * as ValidateBasketInput from './schemas/ValidateBasketInput.schema.json' with { type: 'json' }
addSchema('ValidateBasketInput', ValidateBasketInput)


import * as ValidateBasketOutput from './schemas/ValidateBasketOutput.schema.json' with { type: 'json' }
addSchema('ValidateBasketOutput', ValidateBasketOutput)


import * as VariableSchema_betterAuthUrl from './schemas/VariableSchema_betterAuthUrl.schema.json' with { type: 'json' }
addSchema('VariableSchema_betterAuthUrl', VariableSchema_betterAuthUrl)


import * as VariableSchema_databaseUrl from './schemas/VariableSchema_databaseUrl.schema.json' with { type: 'json' }
addSchema('VariableSchema_databaseUrl', VariableSchema_databaseUrl)


import * as VariableSchema_lowStockThreshold from './schemas/VariableSchema_lowStockThreshold.schema.json' with { type: 'json' }
addSchema('VariableSchema_lowStockThreshold', VariableSchema_lowStockThreshold)


import * as VariableSchema_scenarioActorSecret from './schemas/VariableSchema_scenarioActorSecret.schema.json' with { type: 'json' }
addSchema('VariableSchema_scenarioActorSecret', VariableSchema_scenarioActorSecret)


import * as WorkflowApproverInput from './schemas/WorkflowApproverInput.schema.json' with { type: 'json' }
addSchema('WorkflowApproverInput', WorkflowApproverInput)


import * as WorkflowApproverOutput from './schemas/WorkflowApproverOutput.schema.json' with { type: 'json' }
addSchema('WorkflowApproverOutput', WorkflowApproverOutput)


import * as WorkflowRunStatus from './schemas/WorkflowRunStatus.schema.json' with { type: 'json' }
addSchema('WorkflowRunStatus', WorkflowRunStatus)


import * as WorkflowRunnerInput from './schemas/WorkflowRunnerInput.schema.json' with { type: 'json' }
addSchema('WorkflowRunnerInput', WorkflowRunnerInput)


import * as WorkflowStarterInput from './schemas/WorkflowStarterInput.schema.json' with { type: 'json' }
addSchema('WorkflowStarterInput', WorkflowStarterInput)


import * as WorkflowStarterOutput from './schemas/WorkflowStarterOutput.schema.json' with { type: 'json' }
addSchema('WorkflowStarterOutput', WorkflowStarterOutput)


import * as WorkflowStatusCheckerInput from './schemas/WorkflowStatusCheckerInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusCheckerInput', WorkflowStatusCheckerInput)


import * as WorkflowStatusStreamFullInput from './schemas/WorkflowStatusStreamFullInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusStreamFullInput', WorkflowStatusStreamFullInput)


import * as WorkflowStatusStreamInput from './schemas/WorkflowStatusStreamInput.schema.json' with { type: 'json' }
addSchema('WorkflowStatusStreamInput', WorkflowStatusStreamInput)


import * as WriteAuditEventInput from './schemas/WriteAuditEventInput.schema.json' with { type: 'json' }
addSchema('WriteAuditEventInput', WriteAuditEventInput)
