// Generated by the fabric-theme tool — do not edit by hand.
// One JSON per theme. Each bundles a `brand` (colours + fonts) and a
// `structure` (radius/shadows/spacing) section. Add themes via the fabric-theme tool.
import t_default from './default.json'

export const themeSpecs: Record<string, unknown> = {
  default: t_default,
}
