/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * Auto-generated workflow route schemas
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { z } from 'zod'

export const WorkflowStart = z.object({
  workflowName: z.string(),
  data: z.unknown().optional(),
})

export const GraphStart = z.object({
  workflowName: z.string(),
  nodeId: z.string(),
  data: z.unknown().optional(),
})

export const WorkflowRunRef = z.object({
  workflowName: z.string(),
  runId: z.string(),
})

export const WorkflowRunId = z.object({ runId: z.string() })

export const WorkflowApproval = z.object({
  workflowName: z.string(),
  runId: z.string(),
  reason: z.string(),
  decision: z.unknown(),
})

export const Acknowledged = z.object({ ok: z.literal(true) })
