/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { addWorkflow } from '@pikku/core/workflow'
import './pikku-scenario-wirings-meta.gen.js'
import { shopperAsksTheAssistant } from '../../src/wirings/shop.scenario.js'
import { shopperBuysAnItem } from '../../src/wirings/shop.scenario.js'

addWorkflow('shopperAsksTheAssistant', shopperAsksTheAssistant)
addWorkflow('shopperBuysAnItem', shopperBuysAnItem)