/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { pikkuState } from '@pikku/core/ecosystem'
import type { WorkflowsRuntimeMeta } from '@pikku/core/workflow/types'
import '../workflow/pikku-workflow-wirings-meta.gen.js'

import capturesEveryPageScenarioMeta from './meta/capturesEveryPageScenario.gen.json' with { type: 'json' }
import everyFunctionRunsMeta from './meta/everyFunctionRuns.gen.json' with { type: 'json' }
import everyPageLoadsScenarioMeta from './meta/everyPageLoadsScenario.gen.json' with { type: 'json' }
import sessionHealthScenarioMeta from './meta/sessionHealthScenario.gen.json' with { type: 'json' }
import shopperAsksTheAssistantMeta from './meta/shopperAsksTheAssistant.gen.json' with { type: 'json' }
import shopperBuysAnItemMeta from './meta/shopperBuysAnItem.gen.json' with { type: 'json' }
import shopperBuysAnItemInTheBrowserMeta from './meta/shopperBuysAnItemInTheBrowser.gen.json' with { type: 'json' }
import signedInActorReachesTheAppScenarioMeta from './meta/signedInActorReachesTheAppScenario.gen.json' with { type: 'json' }

const scenariosMeta = {
  'capturesEveryPageScenario': capturesEveryPageScenarioMeta,
  'everyFunctionRuns': everyFunctionRunsMeta,
  'everyPageLoadsScenario': everyPageLoadsScenarioMeta,
  'sessionHealthScenario': sessionHealthScenarioMeta,
  'shopperAsksTheAssistant': shopperAsksTheAssistantMeta,
  'shopperBuysAnItem': shopperBuysAnItemMeta,
  'shopperBuysAnItemInTheBrowser': shopperBuysAnItemInTheBrowserMeta,
  'signedInActorReachesTheAppScenario': signedInActorReachesTheAppScenarioMeta,
} as WorkflowsRuntimeMeta

pikkuState(null, 'workflows', 'meta', {
  ...pikkuState(null, 'workflows', 'meta'),
  ...scenariosMeta,
})