/**
 * This file was generated by @pikku/cli@0.12.99
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core/function'
import { opensPage } from '../../test/scenarios/browser.steps.js'
import { restsOnPath } from '../../test/scenarios/browser.steps.js'
import { sweepsAllPages } from '../../test/scenarios/browser.steps.js'

addFunction('opensPage', opensPage)
addFunction('restsOnPath', restsOnPath)
addFunction('sweepsAllPages', sweepsAllPages)