/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { pikkuState } from '@pikku/core/internal'
import type { WorkflowsRuntimeMeta } from '@pikku/core/workflow/types'
import '../workflow/pikku-workflow-wirings-meta.gen.js'

import shopperAsksTheAssistantMeta from './meta/shopperAsksTheAssistant.gen.json' with { type: 'json' }
import shopperBuysAnItemMeta from './meta/shopperBuysAnItem.gen.json' with { type: 'json' }

const scenariosMeta = {
  'shopperAsksTheAssistant': shopperAsksTheAssistantMeta,
  'shopperBuysAnItem': shopperBuysAnItemMeta,
} as WorkflowsRuntimeMeta

pikkuState(null, 'workflows', 'meta', {
  ...pikkuState(null, 'workflows', 'meta'),
  ...scenariosMeta,
})