/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { pikkuState } from '@pikku/core/internal'
import type { WorkflowsRuntimeMeta } from '@pikku/core/workflow/types'
import '../workflow/pikku-workflow-wirings-meta.gen.js'

import everyPageLoadsScenarioMeta from './meta/everyPageLoadsScenario.gen.json' with { type: 'json' }
import sessionHealthScenarioMeta from './meta/sessionHealthScenario.gen.json' with { type: 'json' }
import signedInActorReachesTheAppScenarioMeta from './meta/signedInActorReachesTheAppScenario.gen.json' with { type: 'json' }

const scenariosMeta = {
  'everyPageLoadsScenario': everyPageLoadsScenarioMeta,
  'sessionHealthScenario': sessionHealthScenarioMeta,
  'signedInActorReachesTheAppScenario': signedInActorReachesTheAppScenarioMeta,
} as WorkflowsRuntimeMeta

pikkuState(null, 'workflows', 'meta', {
  ...pikkuState(null, 'workflows', 'meta'),
  ...scenariosMeta,
})