/**
 * This file was generated by @pikku/cli@0.12.99
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core/function'
import { callsMcpTool } from '../../test/scenarios/browser.steps.js'
import { capturesPage } from '../../test/scenarios/browser.steps.js'
import { clicks } from '../../test/scenarios/browser.steps.js'
import { clicksNear } from '../../test/scenarios/browser.steps.js'
import { opensPage } from '../../test/scenarios/browser.steps.js'
import { postsTo } from '../../test/scenarios/browser.steps.js'
import { restsOnPath } from '../../test/scenarios/browser.steps.js'
import { seesText } from '../../test/scenarios/browser.steps.js'
import { subscribesToChannel } from '../../test/scenarios/browser.steps.js'
import { sweepsAllPages } from '../../test/scenarios/browser.steps.js'

addFunction('callsMcpTool', callsMcpTool)
addFunction('capturesPage', capturesPage)
addFunction('clicks', clicks)
addFunction('clicksNear', clicksNear)
addFunction('opensPage', opensPage)
addFunction('postsTo', postsTo)
addFunction('restsOnPath', restsOnPath)
addFunction('seesText', seesText)
addFunction('subscribesToChannel', subscribesToChannel)
addFunction('sweepsAllPages', sweepsAllPages)