/**
 * This file was generated by @pikku/cli@0.12.102
 */
/**
 * Generated by @pikku/cli — do not edit.
 * Regenerate with `pikku all` (or `pikku realtime`).
 */
import { CorePikkuFetch } from '@pikku/fetch'
import { PikkuFetch } from './pikku-fetch.gen.js'
// No EventHubTopics import configured. Set clientFiles.realtimeEventHubTopicsImport
// in pikku.config.json (e.g. "../types/eventhub-topics.js#EventHubTopics")
// to get fully-typed subscribe/unsubscribe.
type EventHubTopics = Record<string, unknown>

type Handler<T> = (data: T) => void

interface RealtimeOptions {
  /** Auto-reconnect with backoff (default: true) */
  reconnect?: boolean
  /** Initial reconnect delay in ms (default: 500) */
  reconnectDelayMs?: number
  /** Cap on reconnect delay (default: 10_000) */
  reconnectMaxDelayMs?: number
}

/**
 * Realtime client. Mirrors the PikkuRPC pattern: wraps a PikkuFetch so
 * the server URL + auth are configured once and shared across transports.
 *
 * ```ts
 * const pikku = createPikku(PikkuFetch, PikkuRPC, { serverUrl: 'http://localhost:3000' })
 * const realtime = new PikkuRealtime()
 * realtime.setPikkuFetch(pikku.fetch)
 *
 * const off = realtime.subscribe('todo-created', ({ todo }) => { ... })
 * // later: off(); realtime.close()
 * ```
 */
export class PikkuRealtime {
  /** The underlying HTTP client used to derive server URL + auth */
  pikkuFetch = new PikkuFetch()

  private ws: WebSocket | null = null
  private readonly handlers = new Map<string, Set<Handler<any>>>()
  private readonly options: Required<RealtimeOptions>
  private reconnectAttempt = 0
  private closed = false
  private connectScheduled = false

  constructor(options: RealtimeOptions = {}) {
    this.options = {
      reconnect: options.reconnect ?? true,
      reconnectDelayMs: options.reconnectDelayMs ?? 500,
      reconnectMaxDelayMs: options.reconnectMaxDelayMs ?? 10_000,
    }
  }

  /**
   * Use a shared PikkuFetch instance (typically from `createPikku(...)`).
   * The realtime client picks up its server URL + auth from this fetch,
   * so you only configure connection details in one place.
   */
  setPikkuFetch(pikkuFetch: PikkuFetch): void {
    this.pikkuFetch = pikkuFetch
  }

  /** Sets the base server URL on the underlying PikkuFetch. */
  setServerUrl(serverUrl: string): void {
    this.pikkuFetch.setServerUrl(serverUrl)
  }

  /** Sets the JWT for auth on transports that send headers (SSE). */
  setAuthorizationJWT(jwt: string | null): void {
    this.pikkuFetch.setAuthorizationJWT(jwt)
  }

  /** Sets the API key for auth on transports that send headers (SSE). */
  setAPIKey(apiKey: string | null): void {
    this.pikkuFetch.setAPIKey(apiKey)
  }

  /**
   * Subscribe to a typed event topic over the websocket. Returns an
   * `unsubscribe` function. Auto-reconnects re-send subscriptions.
   */
  subscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler: Handler<EventHubTopics[K]>
  ): () => void {
    const set = this.handlers.get(topic) ?? new Set<Handler<any>>()
    if (set.size === 0) {
      this.send({ action: 'subscribe', topic })
    }
    set.add(handler)
    this.handlers.set(topic, set)
    this.ensureConnected()
    return () => this.unsubscribe(topic, handler)
  }

  unsubscribe<K extends keyof EventHubTopics & string>(
    topic: K,
    handler?: Handler<EventHubTopics[K]>
  ): void {
    const set = this.handlers.get(topic)
    if (!set) return
    if (handler) set.delete(handler)
    else set.clear()
    if (set.size === 0) {
      this.handlers.delete(topic)
      this.send({ action: 'unsubscribe', topic })
    }
  }

  /**
   * SSE alternative for a single topic stream. One EventSource per topic;
   * close the returned object to unsubscribe (the server cleans up
   * automatically on disconnect).
   */
  subscribeToTopic<K extends keyof EventHubTopics & string>(
    topic: K,
    handler: Handler<EventHubTopics[K]>
  ): { close: () => void } {
    return this.subscribeToSSE<EventHubTopics[K]>(
      `/events/${encodeURIComponent(topic)}`,
      handler
    )
  }

  /**
   * Generic SSE subscribe. Use for any `sse: true` HTTP route in your
   * project. Caller supplies the path (with any params/query) — the base
   * URL comes from the wrapped PikkuFetch.
   *
   * ```ts
   * const sub = realtime.subscribeToSSE<{ progress: number }>(
   *   `/workflow-run/${runId}/stream`,
   *   (e) => setProgress(e.progress)
   * )
   * ```
   */
  subscribeToSSE<T = unknown>(
    path: string,
    handler: Handler<T>,
    onError?: (err: unknown) => void
  ): { close: () => void } {
    const controller = new AbortController()
    const closed = { value: false }

    const run = async () => {
      try {
        const response = await (this.pikkuFetch as CorePikkuFetch).fetch(
          path,
          'GET',
          null,
          {
            headers: { Accept: 'text/event-stream' },
            signal: controller.signal,
          }
        )
        if (!response.ok || !response.body) {
          throw new Error(`SSE request failed: ${response.status}`)
        }

        const reader = response.body
          .pipeThrough(new TextDecoderStream())
          .getReader()
        let buffer = ''

        while (!closed.value) {
          const { done, value } = await reader.read()
          if (done) break
          buffer += value

          let sep: number
          while ((sep = buffer.indexOf('\n\n')) !== -1) {
            const raw = buffer.slice(0, sep)
            buffer = buffer.slice(sep + 2)

            const dataLines = raw
              .split('\n')
              .filter((l) => l.startsWith('data:'))
              .map((l) => l.slice(5).trimStart())
            if (dataLines.length === 0) continue
            const data = dataLines.join('\n')

            try {
              handler(JSON.parse(data) as T)
            } catch {
              // Ignore malformed events
            }
          }
        }
      } catch (err) {
        if (closed.value) return
        if (onError) onError(err)
      }
    }

    void run()

    return {
      close: () => {
        closed.value = true
        controller.abort()
      },
    }
  }

  /**
   * Open a raw WebSocket against one of the project's wireChannel routes.
   * Wrap the returned socket in `PikkuWebSocket<'channel-name'>` from the
   * generated websocket client for typed subscribe/send.
   */
  connectToChannel(
    channelPath: string,
    protocols?: string | string[]
  ): WebSocket {
    return new WebSocket(this.resolveWsUrl(channelPath), protocols)
  }

  /** Disconnect the events websocket and clear all subscriptions. */
  close(): void {
    this.closed = true
    this.handlers.clear()
    this.ws?.close()
    this.ws = null
  }

  private ensureConnected() {
    if (this.ws || this.connectScheduled || this.closed) return
    this.connect()
  }

  private connect() {
    if (this.closed) return
    this.connectScheduled = false
    const url = this.resolveWsUrl('/events')
    this.ws = new WebSocket(url)
    this.ws.onopen = () => {
      this.reconnectAttempt = 0
      for (const topic of this.handlers.keys()) {
        this.send({ action: 'subscribe', topic })
      }
    }
    this.ws.onmessage = (e: MessageEvent) => {
      let payload: unknown
      try {
        payload =
          typeof e.data === 'string' ? JSON.parse(e.data) : (e.data as unknown)
      } catch {
        return
      }
      if (
        payload &&
        typeof payload === 'object' &&
        'topic' in (payload as any) &&
        typeof (payload as any).topic === 'string'
      ) {
        const { topic, data } = payload as { topic: string; data: unknown }
        const set = this.handlers.get(topic)
        if (set) for (const h of set) h(data)
      }
    }
    this.ws.onclose = () => {
      this.ws = null
      if (this.closed || !this.options.reconnect) return
      const delay = Math.min(
        this.options.reconnectDelayMs * 2 ** this.reconnectAttempt,
        this.options.reconnectMaxDelayMs
      )
      this.reconnectAttempt += 1
      this.connectScheduled = true
      setTimeout(() => this.connect(), delay)
    }
    this.ws.onerror = () => {
      this.ws?.close()
    }
  }

  private send(message: { action: 'subscribe' | 'unsubscribe'; topic: string }) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(message))
    }
    // If not open, onopen replays current handler keys.
  }

  private resolveHttpUrl(path: string): string {
    const base = this.pikkuFetch.getServerUrl()
    if (!base) {
      throw new Error(
        'PikkuRealtime: no server URL — call setServerUrl(...) or setPikkuFetch(...) first.'
      )
    }
    return `${base}${path.startsWith('/') ? path : `/${path}`}`
  }

  private resolveWsUrl(path: string): string {
    const httpUrl = this.resolveHttpUrl(path)
    return httpUrl.replace(/^http/i, 'ws')
  }
}
