/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { TypedCredentialService as CoreTypedCredentialService, type CredentialMetaInfo } from '@pikku/core/services'
import type { CredentialService } from '@pikku/core/services'
import type { OAuth2CredentialConfig } from '@pikku/core/secret'
import type { z } from 'zod'
import { ShippingProviderSchema } from '../../src/wirings/shop.credential.js'

export interface CredentialsMap {
  'shipping-provider': z.infer<typeof ShippingProviderSchema>
}

export type CredentialName = keyof CredentialsMap

const CREDENTIALS_META: Record<string, CredentialMetaInfo> = {
  'shipping-provider': { name: 'shipping-provider', displayName: "Shipping Provider", type: 'singleton', oauth2: true }
}

export const CREDENTIAL_OAUTH2_CONFIGS = {
  'shipping-provider': {
    "appCredentialSecretId": "SHIPPING_APP_CREDENTIAL",
    "tokenSecretId": "SHIPPING_TOKENS",
    "authorizationUrl": "https://carrier.example.com/oauth/authorize",
    "tokenUrl": "https://carrier.example.com/oauth/token",
    "scopes": [
      "shipments:write"
    ],
    "type": "singleton"
  }
} satisfies Record<
  string,
  OAuth2CredentialConfig & {
    appCredentialSecretId: string
    type: 'singleton' | 'wire'
  }
>


export class TypedCredentialService extends CoreTypedCredentialService<CredentialsMap> {
  constructor(credentials: CredentialService) {
    super(credentials, CREDENTIALS_META)
  }
}
