import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
import { DefaultErrorPage } from '@/components/DefaultErrorPage'
import { DefaultNotFoundPage } from '@/components/DefaultNotFoundPage'

// TanStack Start discovers this `getRouter` factory to build a router per
// request (server) and once on the client (hydration). routeTree.gen.ts is
// generated by the tanstackStart() Vite plugin from src/routes/** — don't
// hand-edit it.
export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: 'intent',
    // These router defaults are the ones that actually fire for page failures.
    //
    // A route's own errorComponent only covers a failure in that route. Anything
    // thrown by a child is caught by the nearest enclosing CatchBoundary, and
    // when no ancestor route declares one that boundary falls back to the router
    // default — which, unset, is TanStack's bare stack-trace panel.
    defaultErrorComponent: DefaultErrorPage,
    // Likewise: the root's notFoundComponent handles an unmatched URL, while
    // this handles `throw notFound()` from inside a matched route's loader,
    // which is the case a data-driven 404 actually takes.
    defaultNotFoundComponent: DefaultNotFoundPage,
  })
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
