/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { addSchema } from '@pikku/core/schema'

import * as EveryPageLoadsScenarioOutput from './schemas/EveryPageLoadsScenarioOutput.schema.json' with { type: 'json' }
addSchema('EveryPageLoadsScenarioOutput', EveryPageLoadsScenarioOutput)


import * as OpensPageInput from './schemas/OpensPageInput.schema.json' with { type: 'json' }
addSchema('OpensPageInput', OpensPageInput)


import * as OpensPageOutput from './schemas/OpensPageOutput.schema.json' with { type: 'json' }
addSchema('OpensPageOutput', OpensPageOutput)


import * as RestsOnPathInput from './schemas/RestsOnPathInput.schema.json' with { type: 'json' }
addSchema('RestsOnPathInput', RestsOnPathInput)


import * as RestsOnPathOutput from './schemas/RestsOnPathOutput.schema.json' with { type: 'json' }
addSchema('RestsOnPathOutput', RestsOnPathOutput)


import * as SeesTextInput from './schemas/SeesTextInput.schema.json' with { type: 'json' }
addSchema('SeesTextInput', SeesTextInput)


import * as SeesTextOutput from './schemas/SeesTextOutput.schema.json' with { type: 'json' }
addSchema('SeesTextOutput', SeesTextOutput)


import * as SessionHealthScenarioOutput from './schemas/SessionHealthScenarioOutput.schema.json' with { type: 'json' }
addSchema('SessionHealthScenarioOutput', SessionHealthScenarioOutput)


import * as SignedInActorReachesTheAppScenarioOutput from './schemas/SignedInActorReachesTheAppScenarioOutput.schema.json' with { type: 'json' }
addSchema('SignedInActorReachesTheAppScenarioOutput', SignedInActorReachesTheAppScenarioOutput)


import * as SweepsAllPagesInput from './schemas/SweepsAllPagesInput.schema.json' with { type: 'json' }
addSchema('SweepsAllPagesInput', SweepsAllPagesInput)


import * as SweepsAllPagesOutput from './schemas/SweepsAllPagesOutput.schema.json' with { type: 'json' }
addSchema('SweepsAllPagesOutput', SweepsAllPagesOutput)
