/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { addSchema } from '@pikku/core/schema'

import * as ShopperAsksTheAssistantOutput from './schemas/ShopperAsksTheAssistantOutput.schema.json' with { type: 'json' }
addSchema('ShopperAsksTheAssistantOutput', ShopperAsksTheAssistantOutput)


import * as ShopperBuysAnItemOutput from './schemas/ShopperBuysAnItemOutput.schema.json' with { type: 'json' }
addSchema('ShopperBuysAnItemOutput', ShopperBuysAnItemOutput)
