/**
 * This file was generated by @pikku/cli@0.12.93
 */
// AUTO-GENERATED by pikku CLI — do not edit

import { wireSecret } from '@pikku/core/secret'
import { z } from 'zod'

export const BetterAuthSecretSchema = z.string()

wireSecret({
  name: 'betterAuthSecret',
  displayName: 'Better Auth Secret',
  description: 'Signing secret for better-auth sessions',
  secretId: 'BETTER_AUTH_SECRET',
  schema: BetterAuthSecretSchema,
})
