/**
 * This file was generated by @pikku/cli@0.12.93
 */
// AUTO-GENERATED by pikku CLI — do not edit

import { addHTTPMiddleware } from '../../../.pikku/pikku-types.gen.js'
import { betterAuthStatelessSession } from '@pikku/better-auth'
import { authBearer } from '@pikku/core/middleware'

addHTTPMiddleware('*', [
  betterAuthStatelessSession(),
  authBearer({
    token: {
      secretId: 'PIKKU_CONSOLE_TOKEN',
      userSession: { userId: 'pikku-console-token' },
    },
  }),
])
