/**
 * This file was generated by @pikku/cli@0.12.99
 */
// AUTO-GENERATED by pikku CLI — do not edit

import { pikkuSessionlessFunc, wireHTTPRoutes } from '../../../.pikku/pikku-types.gen.js'
import { createAuthHandler } from '@pikku/better-auth'
import '../../auth.js'

const authConfigHandler = createAuthHandler()
export const authHandler = pikkuSessionlessFunc({
  tags: ['pikku'],
  func: (services: any, data: any, interaction: any) =>
    authConfigHandler.func(services, data, interaction),
})

wireHTTPRoutes({
  tags: ['pikku'],
  routes: {
    getAuthCatchAll: { method: 'get', route: '/api/auth{/*splat}', func: authHandler, auth: false },
    postAuthCatchAll: { method: 'post', route: '/api/auth{/*splat}', func: authHandler, auth: false },
  },
})
