-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "channels" ("channel_id" text primary key, "channel_name" text not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "opening_data" text default '{}' not null, "pikku_user_id" text, "state" text, "last_wire" timestamp default CURRENT_TIMESTAMP not null);

create table "channel_subscriptions" ("channel_id" text not null references "channels" ("channel_id") on delete cascade, "topic" text not null, constraint "channel_subscriptions_pk" primary key ("channel_id", "topic"));

create table "pikku_user_sessions" ("pikku_user_id" text primary key, "session" text not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create table "secrets" ("key" varchar(255) primary key, "ciphertext" text not null, "wrapped_dek" text not null, "key_version" integer not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create table "secrets_audit" ("id" varchar(36) primary key, "secret_key" varchar(255) not null, "action" varchar(20) not null, "performed_at" timestamp default CURRENT_TIMESTAMP not null);

create table "credentials" ("name" varchar(255) not null, "user_id" varchar(255), "ciphertext" text not null, "wrapped_dek" text not null, "key_version" integer not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

CREATE UNIQUE INDEX credentials_name_user_id_unique ON credentials (name, COALESCE(user_id, ''));

create table "credentials_audit" ("id" varchar(36) primary key, "credential_name" varchar(255) not null, "user_id" varchar(255), "action" varchar(20) not null, "performed_at" timestamp default CURRENT_TIMESTAMP not null);

create table "pikku_deployments" ("deployment_id" text primary key, "endpoint" text not null, "last_heartbeat" timestamp default CURRENT_TIMESTAMP not null, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create table "pikku_deployment_functions" ("deployment_id" text not null references "pikku_deployments" ("deployment_id") on delete cascade, "function_name" text not null, constraint "pikku_deployment_functions_pk" primary key ("deployment_id", "function_name"));

create index "idx_pikku_deployments_heartbeat" on "pikku_deployments" ("last_heartbeat");

create index "idx_pikku_deployment_functions_name" on "pikku_deployment_functions" ("function_name");

create table "webhook_delivery" ("delivery_id" text primary key, "organization_id" text, "url" text not null, "event" text, "status" text default 'pending' not null, "attempts" integer default 0 not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null, "delivered_at" timestamp);

create table "webhook_delivery_attempt" ("attempt_id" text primary key, "delivery_id" text not null references "webhook_delivery" ("delivery_id") on delete cascade, "attempt_number" integer not null, "status_code" integer, "response_body" text, "error" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_webhook_delivery_org" on "webhook_delivery" ("organization_id");

create index "idx_webhook_delivery_attempt_delivery" on "webhook_delivery_attempt" ("delivery_id");

create table "workflow_runs" ("workflow_run_id" text primary key, "workflow" text not null, "status" text not null, "input" text not null, "output" text, "error" text, "state" text default '{}', "inline" boolean default false, "graph_hash" text, "deterministic" boolean default false, "planned_steps" text, "wire" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create table "workflow_step" ("workflow_step_id" text primary key, "workflow_run_id" text not null references "workflow_runs" ("workflow_run_id") on delete cascade, "step_name" text not null, "rpc_name" text, "data" text, "status" text default 'pending' not null, "result" text, "error" text, "child_run_id" text, "branch_taken" text, "retries" integer, "retry_delay" text, "from_step_name" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null, constraint "workflow_step_run_name_unique" unique ("workflow_run_id", "step_name"));

create table "workflow_step_history" ("history_id" text primary key, "workflow_step_id" text not null references "workflow_step" ("workflow_step_id") on delete cascade, "status" text not null, "result" text, "error" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "running_at" timestamp, "scheduled_at" timestamp, "succeeded_at" timestamp, "failed_at" timestamp);

create table "workflow_versions" ("workflow_name" text not null, "graph_hash" text not null, "graph" text not null, "source" text not null, "status" text default 'active' not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, constraint "workflow_versions_pk" primary key ("workflow_name", "graph_hash"));

create table "ai_threads" ("id" varchar(36) primary key, "resource_id" varchar(255) not null, "title" text, "metadata" text, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_ai_threads_resource" on "ai_threads" ("resource_id");

create table "ai_message" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "ai_threads" ("id") on delete cascade, "role" varchar(50) not null, "content" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_ai_message_thread" on "ai_message" ("thread_id", "created_at");

create table "ai_tool_call" ("id" varchar(36) primary key, "thread_id" varchar(36) not null references "ai_threads" ("id") on delete cascade, "message_id" varchar(36) not null references "ai_message" ("id") on delete cascade, "run_id" varchar(36), "tool_name" varchar(255) not null, "args" text not null, "result" text, "approval_status" varchar(50), "approval_type" varchar(50), "agent_run_id" varchar(36), "display_tool_name" varchar(255), "display_args" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_ai_tool_call_thread" on "ai_tool_call" ("thread_id");

create index "idx_ai_tool_call_message" on "ai_tool_call" ("message_id");

create table "ai_working_memory" ("id" varchar(255) not null, "scope" varchar(50) not null, "data" text not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null, constraint "ai_working_memory_pk" primary key ("id", "scope"));

create table "ai_run" ("run_id" varchar(36) primary key, "agent_name" varchar(255) not null, "thread_id" varchar(36) not null references "ai_threads" ("id") on delete cascade, "resource_id" varchar(255) not null, "status" varchar(50) default 'running' not null, "error_message" text, "suspend_reason" text, "missing_rpcs" text, "pending_approvals" text, "usage_input_tokens" integer default 0 not null, "usage_output_tokens" integer default 0 not null, "usage_model" varchar(255) default '' not null, "created_at" timestamp default CURRENT_TIMESTAMP not null, "updated_at" timestamp default CURRENT_TIMESTAMP not null);

create index "idx_ai_run_thread" on "ai_run" ("thread_id", "created_at");

create table "pikku_scopes" ("name" text primary key, "description" text, "declared" boolean default true not null);

create table "pikku_roles" ("name" text primary key, "description" text, "created_at" timestamp default CURRENT_TIMESTAMP not null);

create table "pikku_role_scopes" ("role" text not null references "pikku_roles" ("name") on delete cascade, "scope" text not null references "pikku_scopes" ("name") on delete cascade, constraint "pikku_role_scopes_pk" primary key ("role", "scope"));

create table "pikku_user_role" ("user_id" TEXT not null references "user" ("id") on delete cascade, "role" text not null references "pikku_roles" ("name") on delete cascade, "granted_by" text, "granted_at" timestamp default CURRENT_TIMESTAMP not null, constraint "pikku_user_role_pk" primary key ("user_id", "role"));

create table "pikku_user_scope" ("user_id" TEXT not null references "user" ("id") on delete cascade, "scope" text not null references "pikku_scopes" ("name") on delete cascade, "granted_by" text, "granted_at" timestamp default CURRENT_TIMESTAMP not null, constraint "pikku_user_scope_pk" primary key ("user_id", "scope"));

create index "pikku_role_scopes_scope_idx" on "pikku_role_scopes" ("scope");

create index "pikku_user_role_role_idx" on "pikku_user_role" ("role");
