// Generated by @pikku/cli — do not edit by hand.
// Run `pikku db migrate` to refresh.

export const classificationManifest = {
  version: 1 as const,
  tables: {
    "account": {
      "id": { classification: 'private', anonymize_strategy: null },
      "account_id": { classification: 'private', anonymize_strategy: null },
      "provider_id": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null },
      "access_token": { classification: 'private', anonymize_strategy: null },
      "refresh_token": { classification: 'private', anonymize_strategy: null },
      "id_token": { classification: 'private', anonymize_strategy: null },
      "access_token_expires_at": { classification: 'private', anonymize_strategy: null },
      "refresh_token_expires_at": { classification: 'private', anonymize_strategy: null },
      "scope": { classification: 'private', anonymize_strategy: null },
      "password": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "ai_message": {
      "id": { classification: 'private', anonymize_strategy: null },
      "thread_id": { classification: 'private', anonymize_strategy: null },
      "role": { classification: 'private', anonymize_strategy: null },
      "content": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "ai_run": {
      "run_id": { classification: 'private', anonymize_strategy: null },
      "agent_name": { classification: 'private', anonymize_strategy: null },
      "thread_id": { classification: 'private', anonymize_strategy: null },
      "resource_id": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "error_message": { classification: 'private', anonymize_strategy: null },
      "suspend_reason": { classification: 'private', anonymize_strategy: null },
      "missing_rpcs": { classification: 'private', anonymize_strategy: null },
      "pending_approvals": { classification: 'private', anonymize_strategy: null },
      "usage_input_tokens": { classification: 'private', anonymize_strategy: null },
      "usage_output_tokens": { classification: 'private', anonymize_strategy: null },
      "usage_model": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "ai_threads": {
      "id": { classification: 'private', anonymize_strategy: null },
      "resource_id": { classification: 'private', anonymize_strategy: null },
      "title": { classification: 'private', anonymize_strategy: null },
      "metadata": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "ai_tool_call": {
      "id": { classification: 'private', anonymize_strategy: null },
      "thread_id": { classification: 'private', anonymize_strategy: null },
      "message_id": { classification: 'private', anonymize_strategy: null },
      "run_id": { classification: 'private', anonymize_strategy: null },
      "tool_name": { classification: 'private', anonymize_strategy: null },
      "args": { classification: 'private', anonymize_strategy: null },
      "result": { classification: 'private', anonymize_strategy: null },
      "approval_status": { classification: 'private', anonymize_strategy: null },
      "approval_type": { classification: 'private', anonymize_strategy: null },
      "agent_run_id": { classification: 'private', anonymize_strategy: null },
      "display_tool_name": { classification: 'private', anonymize_strategy: null },
      "display_args": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "ai_working_memory": {
      "id": { classification: 'private', anonymize_strategy: null },
      "scope": { classification: 'private', anonymize_strategy: null },
      "data": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "app_user": {
      "user_id": { classification: 'private', anonymize_strategy: null },
      "email": { classification: 'private', anonymize_strategy: null },
      "name": { classification: 'private', anonymize_strategy: null },
      "role": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "audit_log": {
      "audit_id": { classification: 'private', anonymize_strategy: null },
      "entity_type": { classification: 'private', anonymize_strategy: null },
      "entity_id": { classification: 'private', anonymize_strategy: null },
      "action": { classification: 'private', anonymize_strategy: null },
      "actor_id": { classification: 'private', anonymize_strategy: null },
      "payload": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "basket": {
      "basket_id": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null },
      "session_id": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "basket_item": {
      "basket_item_id": { classification: 'private', anonymize_strategy: null },
      "basket_id": { classification: 'private', anonymize_strategy: null },
      "item_id": { classification: 'private', anonymize_strategy: null },
      "quantity": { classification: 'private', anonymize_strategy: null }
    },
    "category": {
      "category_id": { classification: 'private', anonymize_strategy: null },
      "name": { classification: 'private', anonymize_strategy: null },
      "slug": { classification: 'private', anonymize_strategy: null },
      "description": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "channel_subscriptions": {
      "channel_id": { classification: 'private', anonymize_strategy: null },
      "topic": { classification: 'private', anonymize_strategy: null }
    },
    "channels": {
      "channel_id": { classification: 'private', anonymize_strategy: null },
      "channel_name": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "opening_data": { classification: 'private', anonymize_strategy: null },
      "pikku_user_id": { classification: 'private', anonymize_strategy: null },
      "state": { classification: 'private', anonymize_strategy: null },
      "last_wire": { classification: 'private', anonymize_strategy: null }
    },
    "credentials": {
      "name": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null },
      "ciphertext": { classification: 'private', anonymize_strategy: null },
      "wrapped_dek": { classification: 'private', anonymize_strategy: null },
      "key_version": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "credentials_audit": {
      "id": { classification: 'private', anonymize_strategy: null },
      "credential_name": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null },
      "action": { classification: 'private', anonymize_strategy: null },
      "performed_at": { classification: 'private', anonymize_strategy: null }
    },
    "item": {
      "item_id": { classification: 'private', anonymize_strategy: null },
      "category_id": { classification: 'private', anonymize_strategy: null },
      "name": { classification: 'private', anonymize_strategy: null },
      "slug": { classification: 'private', anonymize_strategy: null },
      "description": { classification: 'private', anonymize_strategy: null },
      "price_cents": { classification: 'private', anonymize_strategy: null },
      "stock": { classification: 'private', anonymize_strategy: null },
      "image_url": { classification: 'private', anonymize_strategy: null },
      "is_active": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "order": {
      "order_id": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "total_cents": { classification: 'private', anonymize_strategy: null },
      "shipping_address": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "order_item": {
      "order_item_id": { classification: 'private', anonymize_strategy: null },
      "order_id": { classification: 'private', anonymize_strategy: null },
      "item_id": { classification: 'private', anonymize_strategy: null },
      "quantity": { classification: 'private', anonymize_strategy: null },
      "unit_price_cents": { classification: 'private', anonymize_strategy: null }
    },
    "payment": {
      "payment_id": { classification: 'private', anonymize_strategy: null },
      "order_id": { classification: 'private', anonymize_strategy: null },
      "amount_cents": { classification: 'private', anonymize_strategy: null },
      "provider": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "provider_ref": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_deployment_functions": {
      "deployment_id": { classification: 'private', anonymize_strategy: null },
      "function_name": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_deployments": {
      "deployment_id": { classification: 'private', anonymize_strategy: null },
      "endpoint": { classification: 'private', anonymize_strategy: null },
      "last_heartbeat": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_role_scopes": {
      "role": { classification: 'private', anonymize_strategy: null },
      "scope": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_roles": {
      "name": { classification: 'private', anonymize_strategy: null },
      "description": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_scopes": {
      "name": { classification: 'private', anonymize_strategy: null },
      "description": { classification: 'private', anonymize_strategy: null },
      "declared": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_user_role": {
      "user_id": { classification: 'private', anonymize_strategy: null },
      "role": { classification: 'private', anonymize_strategy: null },
      "granted_by": { classification: 'private', anonymize_strategy: null },
      "granted_at": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_user_scope": {
      "user_id": { classification: 'private', anonymize_strategy: null },
      "scope": { classification: 'private', anonymize_strategy: null },
      "granted_by": { classification: 'private', anonymize_strategy: null },
      "granted_at": { classification: 'private', anonymize_strategy: null }
    },
    "pikku_user_sessions": {
      "pikku_user_id": { classification: 'private', anonymize_strategy: null },
      "session": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "secrets": {
      "key": { classification: 'private', anonymize_strategy: null },
      "ciphertext": { classification: 'private', anonymize_strategy: null },
      "wrapped_dek": { classification: 'private', anonymize_strategy: null },
      "key_version": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "secrets_audit": {
      "id": { classification: 'private', anonymize_strategy: null },
      "secret_key": { classification: 'private', anonymize_strategy: null },
      "action": { classification: 'private', anonymize_strategy: null },
      "performed_at": { classification: 'private', anonymize_strategy: null }
    },
    "session": {
      "id": { classification: 'private', anonymize_strategy: null },
      "expires_at": { classification: 'private', anonymize_strategy: null },
      "token": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null },
      "ip_address": { classification: 'private', anonymize_strategy: null },
      "user_agent": { classification: 'private', anonymize_strategy: null },
      "user_id": { classification: 'private', anonymize_strategy: null }
    },
    "user": {
      "id": { classification: 'private', anonymize_strategy: null },
      "name": { classification: 'private', anonymize_strategy: null },
      "email": { classification: 'private', anonymize_strategy: null },
      "email_verified": { classification: 'private', anonymize_strategy: null },
      "image": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null },
      "actor": { classification: 'private', anonymize_strategy: null }
    },
    "verification": {
      "id": { classification: 'private', anonymize_strategy: null },
      "identifier": { classification: 'private', anonymize_strategy: null },
      "value": { classification: 'private', anonymize_strategy: null },
      "expires_at": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "webhook_delivery": {
      "delivery_id": { classification: 'private', anonymize_strategy: null },
      "organization_id": { classification: 'private', anonymize_strategy: null },
      "url": { classification: 'private', anonymize_strategy: null },
      "event": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "attempts": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null },
      "delivered_at": { classification: 'private', anonymize_strategy: null }
    },
    "webhook_delivery_attempt": {
      "attempt_id": { classification: 'private', anonymize_strategy: null },
      "delivery_id": { classification: 'private', anonymize_strategy: null },
      "attempt_number": { classification: 'private', anonymize_strategy: null },
      "status_code": { classification: 'private', anonymize_strategy: null },
      "response_body": { classification: 'private', anonymize_strategy: null },
      "error": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    },
    "workflow_runs": {
      "workflow_run_id": { classification: 'private', anonymize_strategy: null },
      "workflow": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "input": { classification: 'private', anonymize_strategy: null },
      "output": { classification: 'private', anonymize_strategy: null },
      "error": { classification: 'private', anonymize_strategy: null },
      "state": { classification: 'private', anonymize_strategy: null },
      "inline": { classification: 'private', anonymize_strategy: null },
      "graph_hash": { classification: 'private', anonymize_strategy: null },
      "deterministic": { classification: 'private', anonymize_strategy: null },
      "planned_steps": { classification: 'private', anonymize_strategy: null },
      "wire": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "workflow_step": {
      "workflow_step_id": { classification: 'private', anonymize_strategy: null },
      "workflow_run_id": { classification: 'private', anonymize_strategy: null },
      "step_name": { classification: 'private', anonymize_strategy: null },
      "rpc_name": { classification: 'private', anonymize_strategy: null },
      "data": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "result": { classification: 'private', anonymize_strategy: null },
      "error": { classification: 'private', anonymize_strategy: null },
      "child_run_id": { classification: 'private', anonymize_strategy: null },
      "branch_taken": { classification: 'private', anonymize_strategy: null },
      "retries": { classification: 'private', anonymize_strategy: null },
      "retry_delay": { classification: 'private', anonymize_strategy: null },
      "from_step_name": { classification: 'private', anonymize_strategy: null },
      "current_attempt": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "updated_at": { classification: 'private', anonymize_strategy: null }
    },
    "workflow_step_history": {
      "history_id": { classification: 'private', anonymize_strategy: null },
      "workflow_step_id": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "result": { classification: 'private', anonymize_strategy: null },
      "error": { classification: 'private', anonymize_strategy: null },
      "attempt": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null },
      "running_at": { classification: 'private', anonymize_strategy: null },
      "scheduled_at": { classification: 'private', anonymize_strategy: null },
      "succeeded_at": { classification: 'private', anonymize_strategy: null },
      "failed_at": { classification: 'private', anonymize_strategy: null }
    },
    "workflow_versions": {
      "workflow_name": { classification: 'private', anonymize_strategy: null },
      "graph_hash": { classification: 'private', anonymize_strategy: null },
      "graph": { classification: 'private', anonymize_strategy: null },
      "source": { classification: 'private', anonymize_strategy: null },
      "status": { classification: 'private', anonymize_strategy: null },
      "created_at": { classification: 'private', anonymize_strategy: null }
    }
  },
} as const
