// Generated by @pikku/cli — do not edit by hand.
// Run `pikku db migrate` to refresh.
// Use this type in db/classifications.ts:
//   import type { DbClassificationMap } from './.pikku/db/classification-map.gen.d.ts'
//   export const classifications = { ... } satisfies DbClassificationMap

export type ColumnEntry = {
  /** Privacy level — can the value leave the process? Defaults to 'private'.
   *  'encrypted' is the legacy spelling of `security: 'secret', form: 'wrapped'`. */
  security?: 'public' | 'private' | 'pii' | 'secret' | 'encrypted'
  /** How the value is held at rest, independent of `security`. A form other
   *  than 'plain' makes the column's INSERT/UPDATE type nominal, so only a
   *  real encrypt/seal/hash result can be written to it. Defaults to 'plain',
   *  which on a `secret` column is warned about (PKU483) until stated here. */
  form?: 'plain' | 'hashed' | 'wrapped' | 'sealed'
  /** Anonymize strategy used by `pikku db anonymize`. */
  classification?: 'fake:email' | 'fake:name' | 'hash' | 'keep'
  /** Column kind override for codegen coercion + typing. */
  kind?: 'date' | 'bool' | 'json' | 'uuid'
  /** TypeScript type override, e.g. `string[]` or `MyJson`. Wins over `kind`. */
  tsType?: string
  /** Zod string-format validator (keeps the TS type as `string`). */
  format?: 'email' | 'url' | 'emoji' | 'e164' | 'jwt' | 'cuid' | 'cuid2' | 'ulid' | 'nanoid' | 'base64' | 'base64url' | 'ipv4' | 'ipv6' | 'cidrv4' | 'cidrv6' | 'isoDate' | 'isoTime' | 'isoDatetime' | 'isoDuration'
  description?: string
}

export type DbClassificationMap = {
  "account": {
    "id": ColumnEntry
    "account_id": ColumnEntry
    "provider_id": ColumnEntry
    "user_id": ColumnEntry
    "access_token": ColumnEntry
    "refresh_token": ColumnEntry
    "id_token": ColumnEntry
    "access_token_expires_at": ColumnEntry
    "refresh_token_expires_at": ColumnEntry
    "scope": ColumnEntry
    "password": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "ai_message": {
    "id": ColumnEntry
    "thread_id": ColumnEntry
    "role": ColumnEntry
    "content": ColumnEntry
    "created_at": ColumnEntry
  }
  "ai_run": {
    "run_id": ColumnEntry
    "agent_name": ColumnEntry
    "thread_id": ColumnEntry
    "resource_id": ColumnEntry
    "status": ColumnEntry
    "error_message": ColumnEntry
    "suspend_reason": ColumnEntry
    "missing_rpcs": ColumnEntry
    "pending_approvals": ColumnEntry
    "usage_input_tokens": ColumnEntry
    "usage_output_tokens": ColumnEntry
    "usage_model": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "ai_threads": {
    "id": ColumnEntry
    "resource_id": ColumnEntry
    "title": ColumnEntry
    "metadata": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "ai_tool_call": {
    "id": ColumnEntry
    "thread_id": ColumnEntry
    "message_id": ColumnEntry
    "run_id": ColumnEntry
    "tool_name": ColumnEntry
    "args": ColumnEntry
    "result": ColumnEntry
    "approval_status": ColumnEntry
    "approval_type": ColumnEntry
    "agent_run_id": ColumnEntry
    "display_tool_name": ColumnEntry
    "display_args": ColumnEntry
    "created_at": ColumnEntry
  }
  "ai_working_memory": {
    "id": ColumnEntry
    "scope": ColumnEntry
    "data": ColumnEntry
    "updated_at": ColumnEntry
  }
  "audit_log": {
    "audit_id": ColumnEntry
    "entity_type": ColumnEntry
    "entity_id": ColumnEntry
    "action": ColumnEntry
    "actor_id": ColumnEntry
    "payload": ColumnEntry
    "created_at": ColumnEntry
  }
  "basket": {
    "basket_id": ColumnEntry
    "user_id": ColumnEntry
    "session_id": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "basket_item": {
    "basket_item_id": ColumnEntry
    "basket_id": ColumnEntry
    "item_id": ColumnEntry
    "quantity": ColumnEntry
  }
  "category": {
    "category_id": ColumnEntry
    "name": ColumnEntry
    "slug": ColumnEntry
    "description": ColumnEntry
    "created_at": ColumnEntry
  }
  "channel_subscriptions": {
    "channel_id": ColumnEntry
    "topic": ColumnEntry
  }
  "channels": {
    "channel_id": ColumnEntry
    "channel_name": ColumnEntry
    "created_at": ColumnEntry
    "opening_data": ColumnEntry
    "pikku_user_id": ColumnEntry
    "state": ColumnEntry
    "last_wire": ColumnEntry
  }
  "credentials": {
    "name": ColumnEntry
    "user_id": ColumnEntry
    "ciphertext": ColumnEntry
    "wrapped_dek": ColumnEntry
    "key_version": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "credentials_audit": {
    "id": ColumnEntry
    "credential_name": ColumnEntry
    "user_id": ColumnEntry
    "action": ColumnEntry
    "performed_at": ColumnEntry
  }
  "item": {
    "item_id": ColumnEntry
    "category_id": ColumnEntry
    "name": ColumnEntry
    "slug": ColumnEntry
    "description": ColumnEntry
    "price_cents": ColumnEntry
    "stock": ColumnEntry
    "image_url": ColumnEntry
    "is_active": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "order": {
    "order_id": ColumnEntry
    "user_id": ColumnEntry
    "status": ColumnEntry
    "total_cents": ColumnEntry
    "shipping_address": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "order_item": {
    "order_item_id": ColumnEntry
    "order_id": ColumnEntry
    "item_id": ColumnEntry
    "quantity": ColumnEntry
    "unit_price_cents": ColumnEntry
  }
  "payment": {
    "payment_id": ColumnEntry
    "order_id": ColumnEntry
    "amount_cents": ColumnEntry
    "status": ColumnEntry
    "provider": ColumnEntry
    "provider_ref": ColumnEntry
    "reason": ColumnEntry
    "created_at": ColumnEntry
  }
  "pikku_deployment_functions": {
    "deployment_id": ColumnEntry
    "function_name": ColumnEntry
  }
  "pikku_deployments": {
    "deployment_id": ColumnEntry
    "endpoint": ColumnEntry
    "last_heartbeat": ColumnEntry
    "created_at": ColumnEntry
  }
  "pikku_role_scopes": {
    "role": ColumnEntry
    "scope": ColumnEntry
  }
  "pikku_roles": {
    "name": ColumnEntry
    "description": ColumnEntry
    "created_at": ColumnEntry
    "system": ColumnEntry
    "declared": ColumnEntry
  }
  "pikku_scopes": {
    "name": ColumnEntry
    "description": ColumnEntry
    "declared": ColumnEntry
  }
  "pikku_user_role": {
    "user_id": ColumnEntry
    "role": ColumnEntry
    "granted_by": ColumnEntry
    "granted_at": ColumnEntry
  }
  "pikku_user_scope": {
    "user_id": ColumnEntry
    "scope": ColumnEntry
    "granted_by": ColumnEntry
    "granted_at": ColumnEntry
  }
  "pikku_user_sessions": {
    "pikku_user_id": ColumnEntry
    "session": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "secrets": {
    "key": ColumnEntry
    "ciphertext": ColumnEntry
    "wrapped_dek": ColumnEntry
    "key_version": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "secrets_audit": {
    "id": ColumnEntry
    "secret_key": ColumnEntry
    "action": ColumnEntry
    "performed_at": ColumnEntry
  }
  "session": {
    "id": ColumnEntry
    "expires_at": ColumnEntry
    "token": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
    "ip_address": ColumnEntry
    "user_agent": ColumnEntry
    "user_id": ColumnEntry
    "impersonated_by": ColumnEntry
  }
  "user": {
    "id": ColumnEntry
    "name": ColumnEntry
    "email": ColumnEntry
    "email_verified": ColumnEntry
    "image": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
    "actor": ColumnEntry
    "role": ColumnEntry
    "banned": ColumnEntry
    "ban_reason": ColumnEntry
    "ban_expires": ColumnEntry
    "fabric": ColumnEntry
  }
  "verification": {
    "id": ColumnEntry
    "identifier": ColumnEntry
    "value": ColumnEntry
    "expires_at": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "webhook_delivery": {
    "delivery_id": ColumnEntry
    "organization_id": ColumnEntry
    "url": ColumnEntry
    "event": ColumnEntry
    "status": ColumnEntry
    "attempts": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
    "delivered_at": ColumnEntry
  }
  "webhook_delivery_attempt": {
    "attempt_id": ColumnEntry
    "delivery_id": ColumnEntry
    "attempt_number": ColumnEntry
    "status_code": ColumnEntry
    "response_body": ColumnEntry
    "error": ColumnEntry
    "created_at": ColumnEntry
  }
  "workflow_runs": {
    "workflow_run_id": ColumnEntry
    "workflow": ColumnEntry
    "status": ColumnEntry
    "input": ColumnEntry
    "output": ColumnEntry
    "error": ColumnEntry
    "state": ColumnEntry
    "inline": ColumnEntry
    "graph_hash": ColumnEntry
    "deterministic": ColumnEntry
    "planned_steps": ColumnEntry
    "wire": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "workflow_step": {
    "workflow_step_id": ColumnEntry
    "workflow_run_id": ColumnEntry
    "step_name": ColumnEntry
    "rpc_name": ColumnEntry
    "data": ColumnEntry
    "status": ColumnEntry
    "result": ColumnEntry
    "error": ColumnEntry
    "child_run_id": ColumnEntry
    "branch_taken": ColumnEntry
    "retries": ColumnEntry
    "retry_delay": ColumnEntry
    "from_step_name": ColumnEntry
    "created_at": ColumnEntry
    "updated_at": ColumnEntry
  }
  "workflow_step_history": {
    "history_id": ColumnEntry
    "workflow_step_id": ColumnEntry
    "status": ColumnEntry
    "result": ColumnEntry
    "error": ColumnEntry
    "created_at": ColumnEntry
    "running_at": ColumnEntry
    "scheduled_at": ColumnEntry
    "succeeded_at": ColumnEntry
    "failed_at": ColumnEntry
  }
  "workflow_versions": {
    "workflow_name": ColumnEntry
    "graph_hash": ColumnEntry
    "graph": ColumnEntry
    "source": ColumnEntry
    "status": ColumnEntry
    "created_at": ColumnEntry
  }
}
