// Generated by @pikku/cli — do not edit by hand.
// Run `pikku db migrate` to refresh.
//
// Bare enum unions from Postgres enums and SQLite CHECK (col IN (…)) constraints.

export type OrderStatus = 'pending' | 'paid' | 'payment_failed' | 'shipped' | 'cancelled' | 'refunded'
