// Generated by @pikku/cli — do not edit by hand.
// Run `pikku db migrate` to refresh.

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>

export type Private<T> = T & { readonly __classification__?: 'private' }
export type Pii<T> = T & { readonly __classification__?: 'pii' }
export type Secret<T> = T & { readonly __classification__?: 'secret' }
export type Uuid = string

export interface Account {
  id: ColumnType<Private<string>, string, string>
  accountId: ColumnType<Private<string>, string, string>
  providerId: ColumnType<Private<string>, string, string>
  userId: ColumnType<Private<string>, string, string>
  accessToken: ColumnType<Private<string> | null, string | null, string | null>
  refreshToken: ColumnType<Private<string> | null, string | null, string | null>
  idToken: ColumnType<Private<string> | null, string | null, string | null>
  accessTokenExpiresAt: ColumnType<Private<string> | null, string | null, string | null>
  refreshTokenExpiresAt: ColumnType<Private<string> | null, string | null, string | null>
  scope: ColumnType<Private<string> | null, string | null, string | null>
  password: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string, string>
  updatedAt: ColumnType<Private<string>, string, string>
}

export interface AiMessage {
  id: ColumnType<Private<string>, string, string>
  threadId: ColumnType<Private<string>, string, string>
  role: ColumnType<Private<string>, string, string>
  content: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AiRun {
  runId: ColumnType<Private<string>, string, string>
  agentName: ColumnType<Private<string>, string, string>
  threadId: ColumnType<Private<string>, string, string>
  resourceId: ColumnType<Private<string>, string, string>
  status: ColumnType<Private<string>, string | undefined, string>
  errorMessage: ColumnType<Private<string> | null, string | null, string | null>
  suspendReason: ColumnType<Private<string> | null, string | null, string | null>
  missingRpcs: ColumnType<Private<string> | null, string | null, string | null>
  pendingApprovals: ColumnType<Private<string> | null, string | null, string | null>
  usageInputTokens: ColumnType<Private<number>, number | undefined, number>
  usageOutputTokens: ColumnType<Private<number>, number | undefined, number>
  usageModel: ColumnType<Private<string>, string | undefined, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AiThreads {
  id: ColumnType<Private<string>, string, string>
  resourceId: ColumnType<Private<string>, string, string>
  title: ColumnType<Private<string> | null, string | null, string | null>
  metadata: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AiToolCall {
  id: ColumnType<Private<string>, string, string>
  threadId: ColumnType<Private<string>, string, string>
  messageId: ColumnType<Private<string>, string, string>
  runId: ColumnType<Private<string> | null, string | null, string | null>
  toolName: ColumnType<Private<string>, string, string>
  args: ColumnType<Private<string>, string, string>
  result: ColumnType<Private<string> | null, string | null, string | null>
  approvalStatus: ColumnType<Private<string> | null, string | null, string | null>
  approvalType: ColumnType<Private<string> | null, string | null, string | null>
  agentRunId: ColumnType<Private<string> | null, string | null, string | null>
  displayToolName: ColumnType<Private<string> | null, string | null, string | null>
  displayArgs: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AiWorkingMemory {
  id: ColumnType<Private<string>, string, string>
  scope: ColumnType<Private<string>, string, string>
  data: ColumnType<Private<string>, string, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AppUser {
  userId: ColumnType<Private<string>, string, string>
  email: ColumnType<Private<string>, string, string>
  name: ColumnType<Private<string>, string, string>
  role: ColumnType<Private<string>, string | undefined, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface AuditLog {
  auditId: ColumnType<Private<string>, string, string>
  entityType: ColumnType<Private<string>, string, string>
  entityId: ColumnType<Private<string>, string, string>
  action: ColumnType<Private<string>, string, string>
  actorId: ColumnType<Private<string> | null, string | null, string | null>
  payload: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface Basket {
  basketId: ColumnType<Private<string>, string, string>
  userId: ColumnType<Private<string> | null, string | null, string | null>
  sessionId: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface BasketItem {
  basketItemId: ColumnType<Private<string>, string, string>
  basketId: ColumnType<Private<string>, string, string>
  itemId: ColumnType<Private<string>, string, string>
  quantity: ColumnType<Private<number>, number | undefined, number>
}

export interface Category {
  categoryId: ColumnType<Private<string>, string, string>
  name: ColumnType<Private<string>, string, string>
  slug: ColumnType<Private<string>, string, string>
  description: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface ChannelSubscriptions {
  channelId: ColumnType<Private<string>, string, string>
  topic: ColumnType<Private<string>, string, string>
}

export interface Channels {
  channelId: ColumnType<Private<string>, string, string>
  channelName: ColumnType<Private<string>, string, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  openingData: ColumnType<Private<string>, string | undefined, string>
  pikkuUserId: ColumnType<Private<string> | null, string | null, string | null>
  state: ColumnType<Private<string> | null, string | null, string | null>
  lastWire: ColumnType<Private<string>, string | undefined, string>
}

export interface Credentials {
  name: ColumnType<Private<string>, string, string>
  userId: ColumnType<Private<string> | null, string | null, string | null>
  ciphertext: ColumnType<Private<string>, string, string>
  wrappedDek: ColumnType<Private<string>, string, string>
  keyVersion: ColumnType<Private<number>, number, number>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface CredentialsAudit {
  id: ColumnType<Private<string>, string, string>
  credentialName: ColumnType<Private<string>, string, string>
  userId: ColumnType<Private<string> | null, string | null, string | null>
  action: ColumnType<Private<string>, string, string>
  performedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface Item {
  itemId: ColumnType<Private<string>, string, string>
  categoryId: ColumnType<Private<string>, string, string>
  name: ColumnType<Private<string>, string, string>
  slug: ColumnType<Private<string>, string, string>
  description: ColumnType<Private<string> | null, string | null, string | null>
  priceCents: ColumnType<Private<number>, number, number>
  stock: ColumnType<Private<number>, number | undefined, number>
  imageUrl: ColumnType<Private<string> | null, string | null, string | null>
  isActive: ColumnType<Private<number>, number | undefined, number>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface Order {
  orderId: ColumnType<Private<string>, string, string>
  userId: ColumnType<Private<string>, string, string>
  status: ColumnType<Private<string>, string | undefined, string>
  totalCents: ColumnType<Private<number>, number, number>
  shippingAddress: ColumnType<Private<string>, string, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface OrderItem {
  orderItemId: ColumnType<Private<string>, string, string>
  orderId: ColumnType<Private<string>, string, string>
  itemId: ColumnType<Private<string>, string, string>
  quantity: ColumnType<Private<number>, number, number>
  unitPriceCents: ColumnType<Private<number>, number, number>
}

export interface Payment {
  paymentId: ColumnType<Private<string>, string, string>
  orderId: ColumnType<Private<string>, string, string>
  amountCents: ColumnType<Private<number>, number, number>
  provider: ColumnType<Private<string>, string | undefined, string>
  status: ColumnType<Private<string>, string | undefined, string>
  providerRef: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface PikkuDeploymentFunctions {
  deploymentId: ColumnType<Private<string>, string, string>
  functionName: ColumnType<Private<string>, string, string>
}

export interface PikkuDeployments {
  deploymentId: ColumnType<Private<string>, string, string>
  endpoint: ColumnType<Private<string>, string, string>
  lastHeartbeat: ColumnType<Private<string>, string | undefined, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface PikkuRoleScopes {
  role: ColumnType<Private<string>, string, string>
  scope: ColumnType<Private<string>, string, string>
}

export interface PikkuRoles {
  name: ColumnType<Private<string>, string, string>
  description: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface PikkuScopes {
  name: ColumnType<Private<string>, string, string>
  description: ColumnType<Private<string> | null, string | null, string | null>
  declared: ColumnType<Private<boolean>, boolean | undefined, boolean>
}

export interface PikkuUserRole {
  userId: ColumnType<Private<string>, string, string>
  role: ColumnType<Private<string>, string, string>
  grantedBy: ColumnType<Private<string> | null, string | null, string | null>
  grantedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface PikkuUserScope {
  userId: ColumnType<Private<string>, string, string>
  scope: ColumnType<Private<string>, string, string>
  grantedBy: ColumnType<Private<string> | null, string | null, string | null>
  grantedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface PikkuUserSessions {
  pikkuUserId: ColumnType<Private<string>, string, string>
  session: ColumnType<Private<string>, string, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface Secrets {
  key: ColumnType<Private<string>, string, string>
  ciphertext: ColumnType<Private<string>, string, string>
  wrappedDek: ColumnType<Private<string>, string, string>
  keyVersion: ColumnType<Private<number>, number, number>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface SecretsAudit {
  id: ColumnType<Private<string>, string, string>
  secretKey: ColumnType<Private<string>, string, string>
  action: ColumnType<Private<string>, string, string>
  performedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface Session {
  id: ColumnType<Private<string>, string, string>
  expiresAt: ColumnType<Private<string>, string, string>
  token: ColumnType<Private<string>, string, string>
  createdAt: ColumnType<Private<string>, string, string>
  updatedAt: ColumnType<Private<string>, string, string>
  ipAddress: ColumnType<Private<string> | null, string | null, string | null>
  userAgent: ColumnType<Private<string> | null, string | null, string | null>
  userId: ColumnType<Private<string>, string, string>
}

export interface User {
  id: ColumnType<Private<string>, string, string>
  name: ColumnType<Private<string>, string, string>
  email: ColumnType<Private<string>, string, string>
  emailVerified: ColumnType<Private<number>, number, number>
  image: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string, string>
  updatedAt: ColumnType<Private<string>, string, string>
  actor: ColumnType<Private<number> | null, number | null, number | null>
}

export interface Verification {
  id: ColumnType<Private<string>, string, string>
  identifier: ColumnType<Private<string>, string, string>
  value: ColumnType<Private<string>, string, string>
  expiresAt: ColumnType<Private<string>, string, string>
  createdAt: ColumnType<Private<string>, string, string>
  updatedAt: ColumnType<Private<string>, string, string>
}

export interface WebhookDelivery {
  deliveryId: ColumnType<Private<string>, string, string>
  organizationId: ColumnType<Private<string> | null, string | null, string | null>
  url: ColumnType<Private<string>, string, string>
  event: ColumnType<Private<string> | null, string | null, string | null>
  status: ColumnType<Private<string>, string | undefined, string>
  attempts: ColumnType<Private<number>, number | undefined, number>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
  deliveredAt: ColumnType<Private<string> | null, string | null, string | null>
}

export interface WebhookDeliveryAttempt {
  attemptId: ColumnType<Private<string>, string, string>
  deliveryId: ColumnType<Private<string>, string, string>
  attemptNumber: ColumnType<Private<number>, number, number>
  statusCode: ColumnType<Private<number> | null, number | null, number | null>
  responseBody: ColumnType<Private<string> | null, string | null, string | null>
  error: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface WorkflowRuns {
  workflowRunId: ColumnType<Private<string>, string, string>
  workflow: ColumnType<Private<string>, string, string>
  status: ColumnType<Private<string>, string, string>
  input: ColumnType<Private<string>, string, string>
  output: ColumnType<Private<string> | null, string | null, string | null>
  error: ColumnType<Private<string> | null, string | null, string | null>
  state: ColumnType<Private<string> | null, string | null | undefined, string | null>
  inline: ColumnType<Private<boolean> | null, boolean | null | undefined, boolean | null>
  graphHash: ColumnType<Private<string> | null, string | null, string | null>
  deterministic: ColumnType<Private<boolean> | null, boolean | null | undefined, boolean | null>
  plannedSteps: ColumnType<Private<string> | null, string | null, string | null>
  wire: ColumnType<Private<string> | null, string | null, string | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface WorkflowStep {
  workflowStepId: ColumnType<Private<string>, string, string>
  workflowRunId: ColumnType<Private<string>, string, string>
  stepName: ColumnType<Private<string>, string, string>
  rpcName: ColumnType<Private<string> | null, string | null, string | null>
  data: ColumnType<Private<string> | null, string | null, string | null>
  status: ColumnType<Private<string>, string | undefined, string>
  result: ColumnType<Private<string> | null, string | null, string | null>
  error: ColumnType<Private<string> | null, string | null, string | null>
  childRunId: ColumnType<Private<string> | null, string | null, string | null>
  branchTaken: ColumnType<Private<string> | null, string | null, string | null>
  retries: ColumnType<Private<number> | null, number | null, number | null>
  retryDelay: ColumnType<Private<string> | null, string | null, string | null>
  fromStepName: ColumnType<Private<string> | null, string | null, string | null>
  currentAttempt: ColumnType<Private<number> | null, number | null, number | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  updatedAt: ColumnType<Private<string>, string | undefined, string>
}

export interface WorkflowStepHistory {
  historyId: ColumnType<Private<string>, string, string>
  workflowStepId: ColumnType<Private<string>, string, string>
  status: ColumnType<Private<string>, string, string>
  result: ColumnType<Private<string> | null, string | null, string | null>
  error: ColumnType<Private<string> | null, string | null, string | null>
  attempt: ColumnType<Private<number> | null, number | null, number | null>
  createdAt: ColumnType<Private<string>, string | undefined, string>
  runningAt: ColumnType<Private<string> | null, string | null, string | null>
  scheduledAt: ColumnType<Private<string> | null, string | null, string | null>
  succeededAt: ColumnType<Private<string> | null, string | null, string | null>
  failedAt: ColumnType<Private<string> | null, string | null, string | null>
}

export interface WorkflowVersions {
  workflowName: ColumnType<Private<string>, string, string>
  graphHash: ColumnType<Private<string>, string, string>
  graph: ColumnType<Private<string>, string, string>
  source: ColumnType<Private<string>, string, string>
  status: ColumnType<Private<string>, string | undefined, string>
  createdAt: ColumnType<Private<string>, string | undefined, string>
}

export interface DB {
  account: Account
  aiMessage: AiMessage
  aiRun: AiRun
  aiThreads: AiThreads
  aiToolCall: AiToolCall
  aiWorkingMemory: AiWorkingMemory
  appUser: AppUser
  auditLog: AuditLog
  basket: Basket
  basketItem: BasketItem
  category: Category
  channelSubscriptions: ChannelSubscriptions
  channels: Channels
  credentials: Credentials
  credentialsAudit: CredentialsAudit
  item: Item
  order: Order
  orderItem: OrderItem
  payment: Payment
  pikkuDeploymentFunctions: PikkuDeploymentFunctions
  pikkuDeployments: PikkuDeployments
  pikkuRoleScopes: PikkuRoleScopes
  pikkuRoles: PikkuRoles
  pikkuScopes: PikkuScopes
  pikkuUserRole: PikkuUserRole
  pikkuUserScope: PikkuUserScope
  pikkuUserSessions: PikkuUserSessions
  secrets: Secrets
  secretsAudit: SecretsAudit
  session: Session
  user: User
  verification: Verification
  webhookDelivery: WebhookDelivery
  webhookDeliveryAttempt: WebhookDeliveryAttempt
  workflowRuns: WorkflowRuns
  workflowStep: WorkflowStep
  workflowStepHistory: WorkflowStepHistory
  workflowVersions: WorkflowVersions
}
