// Generated by @pikku/cli — do not edit by hand.
// Run `pikku db migrate` to refresh.

import { z } from 'zod'

export const AccountZ = z.object({
  id: z.string(),
  accountId: z.string(),
  providerId: z.string(),
  userId: z.string(),
  accessToken: z.string().nullable(),
  refreshToken: z.string().nullable(),
  idToken: z.string().nullable(),
  accessTokenExpiresAt: z.string().nullable(),
  refreshTokenExpiresAt: z.string().nullable(),
  scope: z.string().nullable(),
  password: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const AccountInsertZ = z.object({
  id: z.string(),
  accountId: z.string(),
  providerId: z.string(),
  userId: z.string(),
  accessToken: z.string().nullable(),
  refreshToken: z.string().nullable(),
  idToken: z.string().nullable(),
  accessTokenExpiresAt: z.string().nullable(),
  refreshTokenExpiresAt: z.string().nullable(),
  scope: z.string().nullable(),
  password: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const AccountPatchZ = AccountZ.partial()

export const AiMessageZ = z.object({
  id: z.string(),
  threadId: z.string(),
  role: z.string(),
  content: z.string().nullable(),
  createdAt: z.string(),
})

export const AiMessageInsertZ = z.object({
  id: z.string(),
  threadId: z.string(),
  role: z.string(),
  content: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const AiMessagePatchZ = AiMessageZ.partial()

export const AiRunZ = z.object({
  runId: z.string(),
  agentName: z.string(),
  threadId: z.string(),
  resourceId: z.string(),
  status: z.string(),
  errorMessage: z.string().nullable(),
  suspendReason: z.string().nullable(),
  missingRpcs: z.string().nullable(),
  pendingApprovals: z.string().nullable(),
  usageInputTokens: z.number(),
  usageOutputTokens: z.number(),
  usageModel: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const AiRunInsertZ = z.object({
  runId: z.string(),
  agentName: z.string(),
  threadId: z.string(),
  resourceId: z.string(),
  status: z.string().optional(),
  errorMessage: z.string().nullable(),
  suspendReason: z.string().nullable(),
  missingRpcs: z.string().nullable(),
  pendingApprovals: z.string().nullable(),
  usageInputTokens: z.number().optional(),
  usageOutputTokens: z.number().optional(),
  usageModel: z.string().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const AiRunPatchZ = AiRunZ.partial()

export const AiThreadsZ = z.object({
  id: z.string(),
  resourceId: z.string(),
  title: z.string().nullable(),
  metadata: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const AiThreadsInsertZ = z.object({
  id: z.string(),
  resourceId: z.string(),
  title: z.string().nullable(),
  metadata: z.string().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const AiThreadsPatchZ = AiThreadsZ.partial()

export const AiToolCallZ = z.object({
  id: z.string(),
  threadId: z.string(),
  messageId: z.string(),
  runId: z.string().nullable(),
  toolName: z.string(),
  args: z.string(),
  result: z.string().nullable(),
  approvalStatus: z.string().nullable(),
  approvalType: z.string().nullable(),
  agentRunId: z.string().nullable(),
  displayToolName: z.string().nullable(),
  displayArgs: z.string().nullable(),
  createdAt: z.string(),
})

export const AiToolCallInsertZ = z.object({
  id: z.string(),
  threadId: z.string(),
  messageId: z.string(),
  runId: z.string().nullable(),
  toolName: z.string(),
  args: z.string(),
  result: z.string().nullable(),
  approvalStatus: z.string().nullable(),
  approvalType: z.string().nullable(),
  agentRunId: z.string().nullable(),
  displayToolName: z.string().nullable(),
  displayArgs: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const AiToolCallPatchZ = AiToolCallZ.partial()

export const AiWorkingMemoryZ = z.object({
  id: z.string(),
  scope: z.string(),
  data: z.string(),
  updatedAt: z.string(),
})

export const AiWorkingMemoryInsertZ = z.object({
  id: z.string(),
  scope: z.string(),
  data: z.string(),
  updatedAt: z.string().optional(),
})

export const AiWorkingMemoryPatchZ = AiWorkingMemoryZ.partial()

export const AuditLogZ = z.object({
  auditId: z.string(),
  entityType: z.string(),
  entityId: z.string(),
  action: z.string(),
  actorId: z.string().nullable(),
  payload: z.string().nullable(),
  createdAt: z.string(),
})

export const AuditLogInsertZ = z.object({
  auditId: z.string(),
  entityType: z.string(),
  entityId: z.string(),
  action: z.string(),
  actorId: z.string().nullable(),
  payload: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const AuditLogPatchZ = AuditLogZ.partial()

export const BasketZ = z.object({
  basketId: z.string(),
  userId: z.string().nullable(),
  sessionId: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const BasketInsertZ = z.object({
  basketId: z.string(),
  userId: z.string().nullable(),
  sessionId: z.string().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const BasketPatchZ = BasketZ.partial()

export const BasketItemZ = z.object({
  basketItemId: z.string(),
  basketId: z.string(),
  itemId: z.string(),
  quantity: z.number(),
})

export const BasketItemInsertZ = z.object({
  basketItemId: z.string(),
  basketId: z.string(),
  itemId: z.string(),
  quantity: z.number().optional(),
})

export const BasketItemPatchZ = BasketItemZ.partial()

export const CategoryZ = z.object({
  categoryId: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  createdAt: z.string(),
})

export const CategoryInsertZ = z.object({
  categoryId: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const CategoryPatchZ = CategoryZ.partial()

export const ChannelSubscriptionsZ = z.object({
  channelId: z.string(),
  topic: z.string(),
})

export const ChannelSubscriptionsInsertZ = z.object({
  channelId: z.string(),
  topic: z.string(),
})

export const ChannelSubscriptionsPatchZ = ChannelSubscriptionsZ.partial()

export const ChannelsZ = z.object({
  channelId: z.string(),
  channelName: z.string(),
  createdAt: z.string(),
  openingData: z.string(),
  pikkuUserId: z.string().nullable(),
  state: z.string().nullable(),
  lastWire: z.string(),
})

export const ChannelsInsertZ = z.object({
  channelId: z.string(),
  channelName: z.string(),
  createdAt: z.string().optional(),
  openingData: z.string().optional(),
  pikkuUserId: z.string().nullable(),
  state: z.string().nullable(),
  lastWire: z.string().optional(),
})

export const ChannelsPatchZ = ChannelsZ.partial()

export const CredentialsZ = z.object({
  name: z.string(),
  userId: z.string().nullable(),
  ciphertext: z.string(),
  wrappedDek: z.string(),
  keyVersion: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const CredentialsInsertZ = z.object({
  name: z.string(),
  userId: z.string().nullable(),
  ciphertext: z.string(),
  wrappedDek: z.string(),
  keyVersion: z.number(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const CredentialsPatchZ = CredentialsZ.partial()

export const CredentialsAuditZ = z.object({
  id: z.string(),
  credentialName: z.string(),
  userId: z.string().nullable(),
  action: z.string(),
  performedAt: z.string(),
})

export const CredentialsAuditInsertZ = z.object({
  id: z.string(),
  credentialName: z.string(),
  userId: z.string().nullable(),
  action: z.string(),
  performedAt: z.string().optional(),
})

export const CredentialsAuditPatchZ = CredentialsAuditZ.partial()

export const ItemZ = z.object({
  itemId: z.string(),
  categoryId: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  priceCents: z.number(),
  stock: z.number(),
  imageUrl: z.string().nullable(),
  isActive: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const ItemInsertZ = z.object({
  itemId: z.string(),
  categoryId: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  priceCents: z.number(),
  stock: z.number().optional(),
  imageUrl: z.string().nullable(),
  isActive: z.number().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const ItemPatchZ = ItemZ.partial()

export const OrderZ = z.object({
  orderId: z.string(),
  userId: z.string(),
  status: z.enum(['pending', 'paid', 'payment_failed', 'shipped', 'cancelled', 'refunded']),
  totalCents: z.number(),
  shippingAddress: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const OrderInsertZ = z.object({
  orderId: z.string(),
  userId: z.string(),
  status: z.enum(['pending', 'paid', 'payment_failed', 'shipped', 'cancelled', 'refunded']).optional(),
  totalCents: z.number(),
  shippingAddress: z.string().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const OrderPatchZ = OrderZ.partial()

export const OrderItemZ = z.object({
  orderItemId: z.string(),
  orderId: z.string(),
  itemId: z.string(),
  quantity: z.number(),
  unitPriceCents: z.number(),
})

export const OrderItemInsertZ = z.object({
  orderItemId: z.string(),
  orderId: z.string(),
  itemId: z.string(),
  quantity: z.number(),
  unitPriceCents: z.number(),
})

export const OrderItemPatchZ = OrderItemZ.partial()

export const PaymentZ = z.object({
  paymentId: z.string(),
  orderId: z.string(),
  amountCents: z.number(),
  status: z.string(),
  provider: z.string().nullable(),
  providerRef: z.string().nullable(),
  reason: z.string().nullable(),
  createdAt: z.string(),
})

export const PaymentInsertZ = z.object({
  paymentId: z.string(),
  orderId: z.string(),
  amountCents: z.number(),
  status: z.string(),
  provider: z.string().nullable(),
  providerRef: z.string().nullable(),
  reason: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const PaymentPatchZ = PaymentZ.partial()

export const PikkuDeploymentFunctionsZ = z.object({
  deploymentId: z.string(),
  functionName: z.string(),
})

export const PikkuDeploymentFunctionsInsertZ = z.object({
  deploymentId: z.string(),
  functionName: z.string(),
})

export const PikkuDeploymentFunctionsPatchZ = PikkuDeploymentFunctionsZ.partial()

export const PikkuDeploymentsZ = z.object({
  deploymentId: z.string(),
  endpoint: z.string(),
  lastHeartbeat: z.string(),
  createdAt: z.string(),
})

export const PikkuDeploymentsInsertZ = z.object({
  deploymentId: z.string(),
  endpoint: z.string(),
  lastHeartbeat: z.string().optional(),
  createdAt: z.string().optional(),
})

export const PikkuDeploymentsPatchZ = PikkuDeploymentsZ.partial()

export const PikkuRoleScopesZ = z.object({
  role: z.string(),
  scope: z.string(),
})

export const PikkuRoleScopesInsertZ = z.object({
  role: z.string(),
  scope: z.string(),
})

export const PikkuRoleScopesPatchZ = PikkuRoleScopesZ.partial()

export const PikkuRolesZ = z.object({
  name: z.string(),
  description: z.string().nullable(),
  createdAt: z.string(),
  system: z.boolean(),
  declared: z.boolean(),
})

export const PikkuRolesInsertZ = z.object({
  name: z.string(),
  description: z.string().nullable(),
  createdAt: z.string().optional(),
  system: z.boolean().optional(),
  declared: z.boolean().optional(),
})

export const PikkuRolesPatchZ = PikkuRolesZ.partial()

export const PikkuScopesZ = z.object({
  name: z.string(),
  description: z.string().nullable(),
  declared: z.boolean(),
})

export const PikkuScopesInsertZ = z.object({
  name: z.string(),
  description: z.string().nullable(),
  declared: z.boolean().optional(),
})

export const PikkuScopesPatchZ = PikkuScopesZ.partial()

export const PikkuUserRoleZ = z.object({
  userId: z.string(),
  role: z.string(),
  grantedBy: z.string().nullable(),
  grantedAt: z.string(),
})

export const PikkuUserRoleInsertZ = z.object({
  userId: z.string(),
  role: z.string(),
  grantedBy: z.string().nullable(),
  grantedAt: z.string().optional(),
})

export const PikkuUserRolePatchZ = PikkuUserRoleZ.partial()

export const PikkuUserScopeZ = z.object({
  userId: z.string(),
  scope: z.string(),
  grantedBy: z.string().nullable(),
  grantedAt: z.string(),
})

export const PikkuUserScopeInsertZ = z.object({
  userId: z.string(),
  scope: z.string(),
  grantedBy: z.string().nullable(),
  grantedAt: z.string().optional(),
})

export const PikkuUserScopePatchZ = PikkuUserScopeZ.partial()

export const PikkuUserSessionsZ = z.object({
  pikkuUserId: z.string(),
  session: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const PikkuUserSessionsInsertZ = z.object({
  pikkuUserId: z.string(),
  session: z.string(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const PikkuUserSessionsPatchZ = PikkuUserSessionsZ.partial()

export const SecretsZ = z.object({
  key: z.string(),
  ciphertext: z.string(),
  wrappedDek: z.string(),
  keyVersion: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const SecretsInsertZ = z.object({
  key: z.string(),
  ciphertext: z.string(),
  wrappedDek: z.string(),
  keyVersion: z.number(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const SecretsPatchZ = SecretsZ.partial()

export const SecretsAuditZ = z.object({
  id: z.string(),
  secretKey: z.string(),
  action: z.string(),
  performedAt: z.string(),
})

export const SecretsAuditInsertZ = z.object({
  id: z.string(),
  secretKey: z.string(),
  action: z.string(),
  performedAt: z.string().optional(),
})

export const SecretsAuditPatchZ = SecretsAuditZ.partial()

export const SessionZ = z.object({
  id: z.string(),
  expiresAt: z.string(),
  token: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  ipAddress: z.string().nullable(),
  userAgent: z.string().nullable(),
  userId: z.string(),
  impersonatedBy: z.string().nullable(),
})

export const SessionInsertZ = z.object({
  id: z.string(),
  expiresAt: z.string(),
  token: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  ipAddress: z.string().nullable(),
  userAgent: z.string().nullable(),
  userId: z.string(),
  impersonatedBy: z.string().nullable(),
})

export const SessionPatchZ = SessionZ.partial()

export const UserZ = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  emailVerified: z.number(),
  image: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  actor: z.number().nullable(),
  role: z.string().nullable(),
  banned: z.number().nullable(),
  banReason: z.string().nullable(),
  banExpires: z.string().nullable(),
  fabric: z.number().nullable(),
})

export const UserInsertZ = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  emailVerified: z.number(),
  image: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  actor: z.number().nullable(),
  role: z.string().nullable(),
  banned: z.number().nullable(),
  banReason: z.string().nullable(),
  banExpires: z.string().nullable(),
  fabric: z.number().nullable(),
})

export const UserPatchZ = UserZ.partial()

export const VerificationZ = z.object({
  id: z.string(),
  identifier: z.string(),
  value: z.string(),
  expiresAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const VerificationInsertZ = z.object({
  id: z.string(),
  identifier: z.string(),
  value: z.string(),
  expiresAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const VerificationPatchZ = VerificationZ.partial()

export const WebhookDeliveryZ = z.object({
  deliveryId: z.string(),
  organizationId: z.string().nullable(),
  url: z.string(),
  event: z.string().nullable(),
  status: z.string(),
  attempts: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
  deliveredAt: z.string().nullable(),
})

export const WebhookDeliveryInsertZ = z.object({
  deliveryId: z.string(),
  organizationId: z.string().nullable(),
  url: z.string(),
  event: z.string().nullable(),
  status: z.string().optional(),
  attempts: z.number().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  deliveredAt: z.string().nullable(),
})

export const WebhookDeliveryPatchZ = WebhookDeliveryZ.partial()

export const WebhookDeliveryAttemptZ = z.object({
  attemptId: z.string(),
  deliveryId: z.string(),
  attemptNumber: z.number(),
  statusCode: z.number().nullable(),
  responseBody: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.string(),
})

export const WebhookDeliveryAttemptInsertZ = z.object({
  attemptId: z.string(),
  deliveryId: z.string(),
  attemptNumber: z.number(),
  statusCode: z.number().nullable(),
  responseBody: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.string().optional(),
})

export const WebhookDeliveryAttemptPatchZ = WebhookDeliveryAttemptZ.partial()

export const WorkflowRunsZ = z.object({
  workflowRunId: z.string(),
  workflow: z.string(),
  status: z.string(),
  input: z.string(),
  output: z.string().nullable(),
  error: z.string().nullable(),
  state: z.string().nullable(),
  inline: z.boolean().nullable(),
  graphHash: z.string().nullable(),
  deterministic: z.boolean().nullable(),
  plannedSteps: z.string().nullable(),
  wire: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const WorkflowRunsInsertZ = z.object({
  workflowRunId: z.string(),
  workflow: z.string(),
  status: z.string(),
  input: z.string(),
  output: z.string().nullable(),
  error: z.string().nullable(),
  state: z.string().nullable().optional(),
  inline: z.boolean().nullable().optional(),
  graphHash: z.string().nullable(),
  deterministic: z.boolean().nullable().optional(),
  plannedSteps: z.string().nullable(),
  wire: z.string().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const WorkflowRunsPatchZ = WorkflowRunsZ.partial()

export const WorkflowStepZ = z.object({
  workflowStepId: z.string(),
  workflowRunId: z.string(),
  stepName: z.string(),
  rpcName: z.string().nullable(),
  data: z.string().nullable(),
  status: z.string(),
  result: z.string().nullable(),
  error: z.string().nullable(),
  childRunId: z.string().nullable(),
  branchTaken: z.string().nullable(),
  retries: z.number().nullable(),
  retryDelay: z.string().nullable(),
  fromStepName: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export const WorkflowStepInsertZ = z.object({
  workflowStepId: z.string(),
  workflowRunId: z.string(),
  stepName: z.string(),
  rpcName: z.string().nullable(),
  data: z.string().nullable(),
  status: z.string().optional(),
  result: z.string().nullable(),
  error: z.string().nullable(),
  childRunId: z.string().nullable(),
  branchTaken: z.string().nullable(),
  retries: z.number().nullable(),
  retryDelay: z.string().nullable(),
  fromStepName: z.string().nullable(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export const WorkflowStepPatchZ = WorkflowStepZ.partial()

export const WorkflowStepHistoryZ = z.object({
  historyId: z.string(),
  workflowStepId: z.string(),
  status: z.string(),
  result: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.string(),
  runningAt: z.string().nullable(),
  scheduledAt: z.string().nullable(),
  succeededAt: z.string().nullable(),
  failedAt: z.string().nullable(),
})

export const WorkflowStepHistoryInsertZ = z.object({
  historyId: z.string(),
  workflowStepId: z.string(),
  status: z.string(),
  result: z.string().nullable(),
  error: z.string().nullable(),
  createdAt: z.string().optional(),
  runningAt: z.string().nullable(),
  scheduledAt: z.string().nullable(),
  succeededAt: z.string().nullable(),
  failedAt: z.string().nullable(),
})

export const WorkflowStepHistoryPatchZ = WorkflowStepHistoryZ.partial()

export const WorkflowVersionsZ = z.object({
  workflowName: z.string(),
  graphHash: z.string(),
  graph: z.string(),
  source: z.string(),
  status: z.string(),
  createdAt: z.string(),
})

export const WorkflowVersionsInsertZ = z.object({
  workflowName: z.string(),
  graphHash: z.string(),
  graph: z.string(),
  source: z.string(),
  status: z.string().optional(),
  createdAt: z.string().optional(),
})

export const WorkflowVersionsPatchZ = WorkflowVersionsZ.partial()

