/**
 * This file was generated by @pikku/cli@0.12.102
 */
export { defineVariable } from '@pikku/core/variable'
export type { CoreVariable, VariableDefinitionMeta, VariableDefinitionsMeta } from '@pikku/core/variable'
