/**
 * This file was generated by @pikku/cli@0.12.27
 */
export { wireVariable } from '@pikku/core/variable'
export type { CoreVariable, VariableDefinitionMeta, VariableDefinitionsMeta } from '@pikku/core/variable'
