/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { pikkuState } from '@pikku/core/ecosystem'
import { TriggerSourceMeta } from '@pikku/core/trigger'
import metaData from './pikku-trigger-sources-meta.gen.json' with { type: 'json' }

pikkuState(null, 'trigger', 'sourceMeta', metaData as TriggerSourceMeta)