/**
 * This file was generated by @pikku/cli@0.12.93
 */
/**
 * Auto-generated console function schemas
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { z } from 'zod'

export const SecretRef = z.object({ secretId: z.string() })

export const SetSecret = z.object({
  secretId: z.string(),
  value: z.unknown(),
})

export const VariableRef = z.object({ variableId: z.string() })

export const SetVariable = z.object({
  variableId: z.string(),
  value: z.unknown(),
})

export const ValueResult = z.object({
  exists: z.boolean(),
  value: z.unknown().nullable(),
})

export const Exists = z.object({ exists: z.boolean() })

export const Success = z.object({ success: z.boolean() })
