/**
 * This file was generated by @pikku/cli@0.12.99
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core/function'
import { addToBasket } from '../../src/functions/add-to-basket.function.js'
import { cancelOrder } from '../../src/functions/cancel-order.function.js'
import { cancelOrderTool } from '../../src/wires/shop.mcp.js'
import { deleteAgentThread } from '../../src/scaffold/agent/agent.gen.js'
import { getAgentThreadMessages } from '../../src/scaffold/agent/agent.gen.js'
import { getAgentThreadRuns } from '../../src/scaffold/agent/agent.gen.js'
import { getAgentThreads } from '../../src/scaffold/agent/agent.gen.js'
import { getSession } from '../../src/functions/get-session.function.js'
import { listItems } from '../../src/functions/list-items.function.js'
import { listItemsTool } from '../../src/wires/shop.mcp.js'
import { pikkuConsoleGetSecret } from '../../src/scaffold/console/console.gen.js'
import { pikkuConsoleGetVariable } from '../../src/scaffold/console/console.gen.js'
import { pikkuConsoleHasSecret } from '../../src/scaffold/console/console.gen.js'
import { pikkuConsoleSetSecret } from '../../src/scaffold/console/console.gen.js'
import { pikkuConsoleSetVariable } from '../../src/scaffold/console/console.gen.js'

addFunction('addToBasket', addToBasket)
addFunction('cancelOrder', cancelOrder)
addFunction('cancelOrderTool', cancelOrderTool)
addFunction('deleteAgentThread', deleteAgentThread)
addFunction('getAgentThreadMessages', getAgentThreadMessages)
addFunction('getAgentThreadRuns', getAgentThreadRuns)
addFunction('getAgentThreads', getAgentThreads)
addFunction('getSession', getSession)
addFunction('listItems', listItems)
addFunction('listItemsTool', listItemsTool)
addFunction('pikkuConsoleGetSecret', pikkuConsoleGetSecret)
addFunction('pikkuConsoleGetVariable', pikkuConsoleGetVariable)
addFunction('pikkuConsoleHasSecret', pikkuConsoleHasSecret)
addFunction('pikkuConsoleSetSecret', pikkuConsoleSetSecret)
addFunction('pikkuConsoleSetVariable', pikkuConsoleSetVariable)