/**
 * This file was generated by @pikku/cli@0.12.27
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core/function'
import { addToBasket } from '../../src/functions/basket/add-to-basket.function.js'
import { cancelOrder } from '../../src/functions/orders/cancel-order.function.js'
import { checkItemAvailability } from '../../src/wirings/shop.rpc.js'
import { createCategory } from '../../src/functions/categories/create-category.function.js'
import { createItem } from '../../src/functions/items/create-item.function.js'
import { createOrder } from '../../src/functions/orders/create-order.function.js'
import { deleteAgentThread } from '../../src/scaffold/agent.gen.js'
import { getAgentThreadMessages } from '../../src/scaffold/agent.gen.js'
import { getAgentThreadRuns } from '../../src/scaffold/agent.gen.js'
import { getAgentThreads } from '../../src/scaffold/agent.gen.js'
import { getBasket } from '../../src/functions/basket/get-basket.function.js'
import { getItemV1 as getItem_v1 } from '../../src/functions/items/get-item.function.js'
import { getItemV2 as getItem_v2 } from '../../src/functions/items/get-item.function.js'
import { getItem as getItem_v3 } from '../../src/functions/items/get-item.function.js'
import { getOrder } from '../../src/functions/orders/get-order.function.js'
import { listCategories } from '../../src/functions/categories/list-categories.function.js'
import { listItems } from '../../src/functions/items/list-items.function.js'
import { listOrders } from '../../src/functions/orders/list-orders.function.js'
import { pikkuConsoleGetSecret } from '../../src/scaffold/console.gen.js'
import { pikkuConsoleGetVariable } from '../../src/scaffold/console.gen.js'
import { pikkuConsoleHasSecret } from '../../src/scaffold/console.gen.js'
import { pikkuConsoleSetSecret } from '../../src/scaffold/console.gen.js'
import { pikkuConsoleSetVariable } from '../../src/scaffold/console.gen.js'
import { remoteRPCHandler } from '../../src/scaffold/rpc-remote.gen.js'
import { removeFromBasket } from '../../src/functions/basket/remove-from-basket.function.js'
import { updateItem } from '../../src/functions/items/update-item.function.js'

addFunction('addToBasket', addToBasket)
addFunction('cancelOrder', cancelOrder)
addFunction('checkItemAvailability', checkItemAvailability)
addFunction('createCategory', createCategory)
addFunction('createItem', createItem)
addFunction('createOrder', createOrder)
addFunction('deleteAgentThread', deleteAgentThread)
addFunction('getAgentThreadMessages', getAgentThreadMessages)
addFunction('getAgentThreadRuns', getAgentThreadRuns)
addFunction('getAgentThreads', getAgentThreads)
addFunction('getBasket', getBasket)
addFunction('getItem@v1', getItem_v1)
addFunction('getItem@v2', getItem_v2)
addFunction('getItem@v3', getItem_v3)
addFunction('getOrder', getOrder)
addFunction('listCategories', listCategories)
addFunction('listItems', listItems)
addFunction('listOrders', listOrders)
addFunction('pikkuConsoleGetSecret', pikkuConsoleGetSecret)
addFunction('pikkuConsoleGetVariable', pikkuConsoleGetVariable)
addFunction('pikkuConsoleHasSecret', pikkuConsoleHasSecret)
addFunction('pikkuConsoleSetSecret', pikkuConsoleSetSecret)
addFunction('pikkuConsoleSetVariable', pikkuConsoleSetVariable)
addFunction('remoteRPCHandler', remoteRPCHandler)
addFunction('removeFromBasket', removeFromBasket)
addFunction('updateItem', updateItem)