/**
 * This file was generated by @pikku/cli@0.12.99
 */
/* The files with an wireHTTP function call */
import '../../src/middleware/cors.middleware.js'
import '../../src/scaffold/agent/agent.gen.js'
import '../../src/scaffold/auth/auth-middleware.gen.js'
import '../../src/scaffold/auth/auth.gen.js'
import '../../src/scaffold/console/console.gen.js'
import '../../src/scaffold/realtime/events.gen.js'
import '../../src/scaffold/rpc/rpc-public.gen.js'
import '../../src/scaffold/workflow/workflow-routes.gen.js'
import '../../src/wires/http/analytics.http.js'
import '../../src/wirings/checkout.workflow.js'
import '../../src/wirings/shop.bot.js'
import '../../src/wirings/shop.delete-order.http.js'
import '../../src/wirings/shop.http.js'
import '../../src/wirings/shop.payments.js'