/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { pikkuState } from '@pikku/core/ecosystem'
import type { HTTPWiringsMeta } from '@pikku/core/http'
import metaData from './pikku-http-wirings-meta.gen.json' with { type: 'json' }
pikkuState(null, 'http', 'meta', metaData as HTTPWiringsMeta)