/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */

import type { ShippingAddress } from '../../src/wirings/checkout.workflow.js'
import type { AIMessage, AgentRunRow, AIThread, AIAgentInput } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/ai-agent/ai-agent.types'
import type { StreamWorkflowRunInput } from '.bun/@pikku+addon-console@0.12.38+772ba8e58e84dbc2/node_modules/@pikku/addon-console/dist/.pikku/rpc/pikku-rpc-wirings-map.internal.gen'
import type { StripeWebhookHandlerInput } from '.bun/@pikku+addon-stripe@0.1.5+628e4fbaeccdd6be/node_modules/@pikku/addon-stripe/dist/.pikku/rpc/pikku-rpc-wirings-map.internal.gen'
import type { WorkflowRunStatus } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/workflow/workflow.types'


export type AddToBasketInput = {
    basketId: string;
    itemId: string;
    quantity: number;
}
export type AgentApproveCallerInput = {
    agentName: string;
    runId: string;
    approvals: {
        toolCallId: string;
        approved: boolean;
    }[];
}
export type AgentCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AgentCallerOutput = { runId: string; result: any; usage: { inputTokens: number; outputTokens: number; }; }
export type AgentResumeCallerInput = {
    agentName: string;
    runId: string;
    toolCallId: string;
    approved: boolean;
}
export type AgentStreamCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type ApplyStripeEventInput = { type: string; data: { object: Record<string, any>; }; }
export type ApplyStripeEventOutput = { applied: boolean; }
export type AuthHandlerOutput = Promise<void> | Promise<any>
export type CallsMcpToolInput = {
    tool: string;
    args: string;
}
export type CallsMcpToolOutput = {
    text: string;
    advertised: string[];
}
export type CancelOrderInput = {
    orderId: string;
}
export type CapturesEveryPageScenarioOutput = { files: string[]; clean: boolean; }
export type CapturesPageInput = {
    path: string;
    name: string;
    outDir: string;
    width: number;
    height: number;
    scheme: "light" | "dark";
}
export type CapturesPageOutput = {
    file: string;
    pathname: string;
    status: number | null;
    consoleErrors: string[];
    pageErrors: string[];
    failedRequests: string[];
    apiErrors: string[];
}
export type ChargeCardInput = { orderId: string; totalCents: number; cardToken?: string | undefined; }
export type ChargeCardOutput = { status: "succeeded"; providerRef: string; reason?: undefined; } | { status: "failed"; reason: string; providerRef?: undefined; }
export type CheckItemAvailabilityInput = { itemId: string; }
export type CheckItemAvailabilityOutput = { available: boolean; stock: number; name: string; }
export type CheckOrderRefundableInput = { orderId: string; }
export type CheckOrderRefundableOutput = { eligible: boolean; totalCents: number | number; }
export type CheckoutWorkflowInput = { basketId: string; userId: string; shippingAddress: ShippingAddress; cardToken?: string | undefined; }
export type CheckoutWorkflowOutput = { orderId: string; status: "paid" | "payment_failed"; totalCents: number; }
export type ClicksInput = {
    name: string;
}
export type ClicksNearInput = {
    near: string;
    name: string;
}
export type ClicksNearOutput = {
    near: string;
    name: string;
}
export type ClicksOutput = {
    name: string;
    pathname: string;
}
export type CreateCategoryInput = {
    name: string;
    slug: string;
    description?: string | undefined;
}
export type CreateCategoryOutput = {
    categoryId: string;
    name: string;
    slug: string;
}
export type CreateItemInput = {
    categoryId: string;
    name: string;
    slug: string;
    description?: string | undefined;
    priceCents: number;
    stock: number;
    imageUrl?: string | undefined;
}
export type CreateItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    priceCents: number;
    stock: number;
}
export type CreateOrderInput = {
    basketId: string;
    shippingAddress: {
        line1: string;
        line2?: string | undefined;
        city: string;
        postcode: string;
        country: string;
    };
    cardToken?: string | undefined;
}
export type CreateOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
}
export type CreateOrderRecordInput = { userId: string; totalCents: number; shippingAddress: ShippingAddress; items: { itemId: string; quantity: number; priceCents: number; }[]; }
export type CreateOrderRecordOutput = { orderId: any; }
export type CredentialSchema_shipping_provider = {
    accessToken: string;
    refreshToken?: string | undefined;
}
export type DeleteAgentThreadInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type DeleteAgentThreadOutput = {
    deleted: boolean;
}
export type DeleteOrderInput = { orderId: string; }
export type DoesNotSeeTextInput = {
    text: string;
}
export type DoesNotSeeTextOutput = {
    text: string;
}
export type EveryFunctionRunsOutput = { checked: number; }
export type EveryPageLoadsScenarioOutput = { routes: string[]; }
export type FinalizeOrderInput = { orderId: string; basketId: string; userId: string; status: "paid" | "payment_failed"; }
export type GetAgentThreadMessagesInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadMessagesOutput = AIMessage[]
export type GetAgentThreadRunsInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadRunsOutput = AgentRunRow[]
export type GetAgentThreadsInput = {
    agentName?: string | undefined;
    resourceId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type GetAgentThreadsOutput = AIThread[]
export type GetBasketInput = {
    sessionId?: string | undefined;
}
export type GetBasketOutput = {
    basketId: string;
    items: {
        basketItemId: string;
        itemId: string;
        name: string;
        slug: string;
        priceCents: number;
        imageUrl: string | null;
        quantity: number;
        lineTotalCents: number;
    }[];
    totalCents: number;
    itemCount: number;
}
export type GetItemForAIInput = { itemId: string; }
export type GetItemForAIOutput = { type: "text"; text: string; }[]
export type GetItemInput = {
    itemId: string;
}
export type GetItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetItemToolInput = { itemId: string; }
export type GetItemToolOutput = { type: "text"; text: string; }[]
export type GetItemV1Input = {
    itemId: string;
}
export type GetItemV1Output = {
    itemId: string;
    name: string;
    priceCents: number;
}
export type GetItemV2Input = {
    itemId: string;
}
export type GetItemV2Output = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetOrderInput = {
    orderId: string;
}
export type GetOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
    shippingAddress: {
        [key: string]: unknown;
    };
    items: {
        itemId: string;
        name: string;
        quantity: number;
        unitPriceCents: number;
        lineTotalCents: number;
    }[];
    createdAt: string;
}
export type GetProfileOutput = { name: string; email: string; id: string; role: string | null; }
export type GetSessionInput = {}
export type GetSessionOutput = {
    userId: string;
    email: string;
    name: string | null;
}
export type GraphStarterInput = {
    workflowName: string;
    nodeId: string;
    data?: unknown | undefined;
}
export type GraphStarterOutput = {
    runId: string;
}
export type HandleChatMessageInput = { text: string; raw: unknown; }
export type HandleChatMessageOutput = { received: boolean; }
export type HttpPostAgentsCheckoutOutput = { runId: string; result: string; usage: { inputTokens: number; outputTokens: number; }; }
export type HttpPostAgentsOpsOutput = { runId: string; result: string; usage: { inputTokens: number; outputTokens: number; }; }
export type HttpPostAgentsShopOutput = { runId: string; result: string; usage: { inputTokens: number; outputTokens: number; }; }
export type HttpPostAgentsShopStreamInput = { agentName?: string | undefined; message: string; threadId: string; resourceId: string; }
export type HttpPostWebhooksStripeOutput = { received: boolean; eventId: string; type: string; jobId: string; }
export type IssueRefundInput = { orderId: string; }
export type ListCategoriesOutput = {
    categoryId: string;
    name: string;
    slug: string;
    description: string | null;
}[]
export type ListCategoriesToolOutput = { type: "text"; text: string; }[]
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        description: string | null;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
        category: {
            categoryId: string;
            name: string;
            slug: string;
        };
    }[];
    total: number;
}
export type ListItemsToolInput = { categorySlug?: string | undefined; search?: string | undefined; limit?: number | undefined; offset?: number | undefined; }
export type ListItemsToolOutput = { type: "text"; text: string; }[]
export type ListOrdersInput = {
    limit: number;
    offset: number;
}
export type ListOrdersOutput = { orderId: string; status: "paid" | "payment_failed" | "refunded" | "pending" | "shipped" | "cancelled"; totalCents: number; createdAt: string; }[]
export type NotifyOrderShippedInput = { orderId: string; }
export type OnLowStockInput = {
    itemId: string;
    name: string;
    stock: number;
}
export type OpensPageInput = {
    path: string;
}
export type OpensPageOutput = {
    pathname: string;
    status: number | null;
}
export type PikkuConsoleGetSecretInput = {
    secretId: string;
}
export type PikkuConsoleGetSecretOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleGetVariableInput = {
    variableId: string;
}
export type PikkuConsoleGetVariableOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleHasSecretInput = {
    secretId: string;
}
export type PikkuConsoleHasSecretOutput = {
    exists: boolean;
}
export type PikkuConsoleSetSecretInput = {
    secretId: string;
    value: unknown;
}
export type PikkuConsoleSetSecretOutput = {
    success: boolean;
}
export type PikkuConsoleSetVariableInput = {
    variableId: string;
    value: unknown;
}
export type PikkuConsoleSetVariableOutput = {
    success: boolean;
}
export type PostsToInput = {
    path: string;
    body: string;
    maxStatus: number;
    minStatus: number;
    expectBody?: string | undefined;
}
export type PostsToOutput = {
    status: number;
    body: string;
}
export type ProcessExportInput = { exportId: string; }
export type RealtimeEventStreamInput = {
    topic: string;
}
export type RealtimeSubscribeInput = {
    topic: string;
}
export type RealtimeUnsubscribeInput = {
    topic: string;
}
export type RecordAnalyticsEventsInput = {
    events: {
        at?: number | undefined;
        event: {
            name: "page_viewed";
            path: string;
        } | {
            name: "signed_up";
        } | {
            name: "checkout_completed";
            amount: number;
            currency: string;
        };
    }[];
}
export type RecordAnalyticsEventsOutput = {
    accepted: number;
}
export type RefundWorkflowInput = { orderId: string; reason: string; }
export type RefundWorkflowOutput = { orderId: string; refunded: boolean; message: string; }
export type RemoveFromBasketInput = {
    basketId: string;
    itemId: string;
}
export type RestsOnPathInput = {
    path: string;
}
export type RestsOnPathOutput = {
    pathname: string;
}
export type RpcCallerInput = {
    rpcName: string;
    data?: unknown | undefined;
}
export type SecretSchema_betterAuthSecret = string
export type SecretSchema_scenarioActorSecret = string
export type SecretSchema_stripeSecretKey = string
export type SeesTextInput = {
    text: string;
}
export type SeesTextOutput = {
    text: string;
}
export type SendOrderConfirmationInput = {
    orderId: string;
    userId: string;
}
export type SessionHealthScenarioOutput = { email: string; userId: string; }
export type ShopperAsksTheAssistantOutput = { itemCount: number; }
export type ShopperBuysAnItemInTheBrowserOutput = { landed: string; }
export type ShopperBuysAnItemOutput = { orderId: string; totalCents: number; }
export type SignedInActorReachesTheAppScenarioOutput = { pathname: string; email: string; }
export type StartCheckoutInput = { basketId: string; userId: string; shippingAddress: ShippingAddress; cardToken?: string | undefined; }
export type StartCheckoutOutput = { runId: string; }
export type StartExportOutput = { exportId: any; requestedBy: string; }
export type StartRefundInput = { orderId: string; reason: string; }
export type StartRefundOutput = { runId: string; }
export type SubscribesToChannelInput = {
    route: string;
    action: string;
    unsubscribeAction?: string | undefined;
}
export type SubscribesToChannelOutput = {
    connected: boolean;
}
export type SubscribeToOrderInput = { orderId: string; }
export type SweepsAllPagesInput = {
    repoRoot: string;
}
export type SweepsAllPagesOutput = {
    routes: string[];
}
export type TypesIntoInput = {
    label: string;
    text: string;
}
export type TypesIntoOutput = {
    label: string;
}
export type UnsubscribeFromOrderInput = { orderId: string; }
export type UpdateItemInput = {
    itemId: string;
    name?: string | undefined;
    description?: string | undefined;
    priceCents?: number | undefined;
    stock?: number | undefined;
    imageUrl?: (string | null) | undefined;
    isActive?: boolean | undefined;
}
export type UpdateStockToolInput = { itemId: string; stock: number; }
export type UpdateStockToolOutput = { type: "text"; text: string; }[]
export type ValidateBasketInput = { basketId: string; }
export type ValidateBasketOutput = { items: { itemId: string; quantity: number; priceCents: number; }[]; totalCents: number; }
export type VariableSchema_betterAuthUrl = string
export type VariableSchema_corsOrigins = string
export type VariableSchema_databaseUrl = string
export type VariableSchema_frontendUrl = string
export type VariableSchema_lowStockThreshold = number
export type VariableSchema_scenarioActorSecret = string
export type WorkflowApproverInput = {
    workflowName: string;
    runId: string;
    reason: string;
    decision: unknown;
}
export type WorkflowApproverOutput = {
    ok: true;
}
export type WorkflowRunnerInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterOutput = {
    runId: string;
}
export type WorkflowStatusCheckerInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamFullInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamInput = {
    workflowName: string;
    runId: string;
}
export type WriteAuditEventInput = {
    entityType: string;
    entityId: string;
    action: string;
    actorId?: string | undefined;
    payload?: {
        [key: string]: unknown;
    } | undefined;
}

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputParams = Pick<AgentResumeCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputBody = Omit<AgentResumeCallerInput, 'agentName'> & {}
export type StreamWorkflowRunInputParams = Pick<StreamWorkflowRunInput, 'runId'> & {}
export type StreamWorkflowRunInputBody = Omit<StreamWorkflowRunInput, 'runId'> & {}
export type RealtimeEventStreamInputParams = Pick<RealtimeEventStreamInput, 'topic'> & {}
export type RealtimeEventStreamInputBody = Omit<RealtimeEventStreamInput, 'topic'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type WorkflowStarterInputParams = Pick<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowStarterInputBody = Omit<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowApproverInputParams = Pick<WorkflowApproverInput, 'workflowName' | 'runId'> & {}
export type WorkflowApproverInputBody = Omit<WorkflowApproverInput, 'workflowName' | 'runId'> & {}
export type WorkflowRunnerInputParams = Pick<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowRunnerInputBody = Omit<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowStatusCheckerInputParams = Pick<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusCheckerInputBody = Omit<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputParams = Pick<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputBody = Omit<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputParams = Pick<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputBody = Omit<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type GraphStarterInputParams = Pick<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type GraphStarterInputBody = Omit<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type RecordAnalyticsEventsInputBody = RecordAnalyticsEventsInput & {}
export type StartCheckoutInputBody = StartCheckoutInput & {}
export type StartRefundInputParams = Pick<StartRefundInput, 'orderId'> & {}
export type StartRefundInputBody = Omit<StartRefundInput, 'orderId'> & {}
export type AIAgentInputBody = AIAgentInput & {}
export type HttpPostAgentsShopStreamInputBody = HttpPostAgentsShopStreamInput & {}
export type DeleteOrderInputParams = Pick<DeleteOrderInput, 'orderId'> & {}
export type DeleteOrderInputBody = Omit<DeleteOrderInput, 'orderId'> & {}
export type CreateCategoryInputBody = CreateCategoryInput & {}
export type ListItemsInputBody = ListItemsInput & {}
export type GetItemInputParams = Pick<GetItemInput, 'itemId'> & {}
export type GetItemInputBody = Omit<GetItemInput, 'itemId'> & {}
export type CreateItemInputBody = CreateItemInput & {}
export type UpdateItemInputParams = Pick<UpdateItemInput, 'itemId'> & {}
export type UpdateItemInputBody = Omit<UpdateItemInput, 'itemId'> & {}
export type GetBasketInputBody = GetBasketInput & {}
export type AddToBasketInputBody = AddToBasketInput & {}
export type RemoveFromBasketInputParams = Pick<RemoveFromBasketInput, 'itemId'> & {}
export type RemoveFromBasketInputBody = Omit<RemoveFromBasketInput, 'itemId'> & {}
export type CreateOrderInputBody = CreateOrderInput & {}
export type ListOrdersInputBody = ListOrdersInput & {}
export type GetOrderInputParams = Pick<GetOrderInput, 'orderId'> & {}
export type GetOrderInputBody = Omit<GetOrderInput, 'orderId'> & {}
export type CancelOrderInputParams = Pick<CancelOrderInput, 'orderId'> & {}
export type CancelOrderInputBody = Omit<CancelOrderInput, 'orderId'> & {}
export type StripeWebhookHandlerInputBody = StripeWebhookHandlerInput & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/api/auth{/*splat}': {
    readonly GET: HTTPWiringHandler<null, AuthHandlerOutput>,
    readonly POST: HTTPWiringHandler<null, AuthHandlerOutput>,
  },
  readonly '/workflow-run/:runId/stream': {
    readonly GET: HTTPWiringHandler<StreamWorkflowRunInput, null>,
  },
  readonly '/events/:topic': {
    readonly GET: HTTPWiringHandler<RealtimeEventStreamInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId': {
    readonly GET: HTTPWiringHandler<WorkflowStatusCheckerInput, WorkflowRunStatus>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream/full': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamFullInput, null>,
  },
  readonly '/categories': {
    readonly GET: HTTPWiringHandler<null, ListCategoriesOutput>,
    readonly POST: HTTPWiringHandler<CreateCategoryInput, CreateCategoryOutput>,
  },
  readonly '/items': {
    readonly GET: HTTPWiringHandler<ListItemsInput, ListItemsOutput>,
    readonly POST: HTTPWiringHandler<CreateItemInput, CreateItemOutput>,
  },
  readonly '/items/:itemId': {
    readonly GET: HTTPWiringHandler<GetItemInput, GetItemOutput>,
    readonly PATCH: HTTPWiringHandler<UpdateItemInput, null>,
  },
  readonly '/profile': {
    readonly GET: HTTPWiringHandler<null, GetProfileOutput>,
  },
  readonly '/basket': {
    readonly GET: HTTPWiringHandler<GetBasketInput, GetBasketOutput>,
  },
  readonly '/orders': {
    readonly GET: HTTPWiringHandler<ListOrdersInput, ListOrdersOutput>,
    readonly POST: HTTPWiringHandler<CreateOrderInput, CreateOrderOutput>,
  },
  readonly '/orders/:orderId': {
    readonly GET: HTTPWiringHandler<GetOrderInput, GetOrderOutput>,
    readonly DELETE: HTTPWiringHandler<DeleteOrderInput, null>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, AgentCallerOutput>,
  },
  readonly '/rpc/agent/:agentName/stream': {
    readonly POST: HTTPWiringHandler<AgentStreamCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/resume': {
    readonly POST: HTTPWiringHandler<AgentResumeCallerInput, null>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
  },
  readonly '/workflow/:workflowName/start': {
    readonly POST: HTTPWiringHandler<WorkflowStarterInput, WorkflowStarterOutput>,
  },
  readonly '/workflow/:workflowName/approve/:runId': {
    readonly POST: HTTPWiringHandler<WorkflowApproverInput, WorkflowApproverOutput>,
  },
  readonly '/workflow/:workflowName/run': {
    readonly POST: HTTPWiringHandler<WorkflowRunnerInput, null>,
  },
  readonly '/workflow/:workflowName/graph/:nodeId': {
    readonly POST: HTTPWiringHandler<GraphStarterInput, GraphStarterOutput>,
  },
  readonly '/analytics': {
    readonly POST: HTTPWiringHandler<RecordAnalyticsEventsInput, RecordAnalyticsEventsOutput>,
  },
  readonly '/checkout': {
    readonly POST: HTTPWiringHandler<StartCheckoutInput, StartCheckoutOutput>,
  },
  readonly '/orders/:orderId/refund': {
    readonly POST: HTTPWiringHandler<StartRefundInput, StartRefundOutput>,
  },
  readonly '/agents/shop': {
    readonly POST: HTTPWiringHandler<AIAgentInput, HttpPostAgentsShopOutput>,
  },
  readonly '/agents/shop/stream': {
    readonly POST: HTTPWiringHandler<HttpPostAgentsShopStreamInput, null>,
  },
  readonly '/agents/ops': {
    readonly POST: HTTPWiringHandler<AIAgentInput, HttpPostAgentsOpsOutput>,
  },
  readonly '/agents/checkout': {
    readonly POST: HTTPWiringHandler<AIAgentInput, HttpPostAgentsCheckoutOutput>,
  },
  readonly '/basket/items': {
    readonly POST: HTTPWiringHandler<AddToBasketInput, null>,
  },
  readonly '/orders/:orderId/cancel': {
    readonly POST: HTTPWiringHandler<CancelOrderInput, null>,
  },
  readonly '/exports': {
    readonly POST: HTTPWiringHandler<null, StartExportOutput>,
  },
  readonly '/reports/conditional': {
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/webhooks/stripe': {
    readonly POST: HTTPWiringHandler<StripeWebhookHandlerInput, HttpPostWebhooksStripeOutput>,
  },
  readonly '/basket/items/:itemId': {
    readonly DELETE: HTTPWiringHandler<RemoveFromBasketInput, null>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  