/**
 * This file was generated by @pikku/cli@0.12.93
 */
/* The files with an wireHTTP function call */
import '../../src/scaffold/agent/agent.gen.js'
import '../../src/scaffold/auth/auth-middleware.gen.js'
import '../../src/scaffold/auth/auth.gen.js'
import '../../src/scaffold/console/console.gen.js'
import '../../src/scaffold/rpc/rpc-public.gen.js'
import '../../src/scaffold/workflow/workflow-routes.gen.js'
import '../../src/wirings/checkout.workflow.js'
import '../../src/wirings/shop.bot.js'
import '../../src/wirings/shop.gateway.js'
import '../../src/wirings/shop.http.js'
import '../../src/wirings/shop.security.js'