/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */

import type { AIMessage, AgentRunRow, AIThread } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/ai-agent/ai-agent.types'
import type { StreamWorkflowRunInput } from '.bun/@pikku+addon-console@0.12.38+772ba8e58e84dbc2/node_modules/@pikku/addon-console/dist/.pikku/rpc/pikku-rpc-wirings-map.internal.gen'
import type { WorkflowRunStatus } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/workflow/workflow.types'


export type AddToBasketInput = {
    itemId: string;
    quantity: number;
}
export type AddToBasketOutput = {
    basketId: string;
    itemCount: number;
}
export type AgentApproveCallerInput = {
    agentName: string;
    runId: string;
    approvals: {
        toolCallId: string;
        approved: boolean;
    }[];
}
export type AgentCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AgentResumeCallerInput = {
    agentName: string;
    runId: string;
    toolCallId: string;
    approved: boolean;
}
export type AgentStreamCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AuthHandlerOutput = Promise<void> | Promise<any>
export type CancelOrderInput = {
    orderId: string;
}
export type CancelOrderOutput = {
    orderId: string;
    status: string;
}
export type CancelOrderToolInput = { orderId: string; }
export type CancelOrderToolOutput = { type: "text"; text: string; }[]
export type DeleteAgentThreadInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type DeleteAgentThreadOutput = {
    deleted: boolean;
}
export type EveryPageLoadsScenarioOutput = { routes: string[]; }
export type GetAgentThreadMessagesInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadMessagesOutput = AIMessage[]
export type GetAgentThreadRunsInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadRunsOutput = AgentRunRow[]
export type GetAgentThreadsInput = {
    agentName?: string | undefined;
    resourceId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type GetAgentThreadsOutput = AIThread[]
export type GetSessionInput = {}
export type GetSessionOutput = {
    userId: string;
    email: string;
    name: string | null;
}
export type GraphStarterInput = {
    workflowName: string;
    nodeId: string;
    data?: unknown | undefined;
}
export type GraphStarterOutput = {
    runId: string;
}
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit: number;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        category: string;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
    }[];
}
export type ListItemsToolInput = { categorySlug?: string | undefined; search?: string | undefined; limit?: number | undefined; }
export type ListItemsToolOutput = { type: "text"; text: string; }[]
export type OpensPageInput = {
    path: string;
}
export type OpensPageOutput = {
    pathname: string;
    status: number | null;
}
export type PikkuConsoleGetSecretInput = {
    secretId: string;
}
export type PikkuConsoleGetSecretOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleGetVariableInput = {
    variableId: string;
}
export type PikkuConsoleGetVariableOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleHasSecretInput = {
    secretId: string;
}
export type PikkuConsoleHasSecretOutput = {
    exists: boolean;
}
export type PikkuConsoleSetSecretInput = {
    secretId: string;
    value: unknown;
}
export type PikkuConsoleSetSecretOutput = {
    success: boolean;
}
export type PikkuConsoleSetVariableInput = {
    variableId: string;
    value: unknown;
}
export type PikkuConsoleSetVariableOutput = {
    success: boolean;
}
export type RealtimeEventStreamInput = {
    topic: string;
}
export type RealtimeSubscribeInput = {
    topic: string;
}
export type RealtimeUnsubscribeInput = {
    topic: string;
}
export type RecordAnalyticsEventsInput = {
    events: {
        at?: number | undefined;
        event: {
            name: "page_viewed";
            path: string;
        } | {
            name: "signed_up";
        } | {
            name: "checkout_completed";
            amount: number;
            currency: string;
        };
    }[];
}
export type RecordAnalyticsEventsOutput = {
    accepted: number;
}
export type RestsOnPathInput = {
    path: string;
}
export type RestsOnPathOutput = {
    pathname: string;
}
export type RpcCallerInput = {
    rpcName: string;
    data?: unknown | undefined;
}
export type SecretSchema_betterAuthSecret = string
export type SecretSchema_scenarioActorSecret = string
export type SeesTextInput = {
    text: string;
}
export type SeesTextOutput = {
    text: string;
}
export type SendOrderConfirmationInput = {
    orderId: string;
    email: string;
}
export type SessionHealthScenarioOutput = { email: string; userId: string; }
export type SignedInActorReachesTheAppScenarioOutput = { pathname: string; email: string; }
export type SweepsAllPagesInput = {
    repoRoot: string;
}
export type SweepsAllPagesOutput = {
    routes: string[];
}
export type VariableSchema_corsOrigins = string
export type VariableSchema_frontendUrl = string
export type WatchOrderInput = { orderId: string; }
export type WorkflowApproverInput = {
    workflowName: string;
    runId: string;
    reason: string;
    decision: unknown;
}
export type WorkflowApproverOutput = {
    ok: true;
}
export type WorkflowRunnerInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterOutput = {
    runId: string;
}
export type WorkflowStatusCheckerInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamFullInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamInput = {
    workflowName: string;
    runId: string;
}

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputParams = Pick<AgentResumeCallerInput, 'agentName'> & {}
export type AgentResumeCallerInputBody = Omit<AgentResumeCallerInput, 'agentName'> & {}
export type StreamWorkflowRunInputParams = Pick<StreamWorkflowRunInput, 'runId'> & {}
export type StreamWorkflowRunInputBody = Omit<StreamWorkflowRunInput, 'runId'> & {}
export type RealtimeEventStreamInputParams = Pick<RealtimeEventStreamInput, 'topic'> & {}
export type RealtimeEventStreamInputBody = Omit<RealtimeEventStreamInput, 'topic'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type WorkflowStarterInputParams = Pick<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowStarterInputBody = Omit<WorkflowStarterInput, 'workflowName'> & {}
export type WorkflowApproverInputParams = Pick<WorkflowApproverInput, 'workflowName' | 'runId'> & {}
export type WorkflowApproverInputBody = Omit<WorkflowApproverInput, 'workflowName' | 'runId'> & {}
export type WorkflowRunnerInputParams = Pick<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowRunnerInputBody = Omit<WorkflowRunnerInput, 'workflowName'> & {}
export type WorkflowStatusCheckerInputParams = Pick<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusCheckerInputBody = Omit<WorkflowStatusCheckerInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputParams = Pick<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamInputBody = Omit<WorkflowStatusStreamInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputParams = Pick<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type WorkflowStatusStreamFullInputBody = Omit<WorkflowStatusStreamFullInput, 'workflowName' | 'runId'> & {}
export type GraphStarterInputParams = Pick<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type GraphStarterInputBody = Omit<GraphStarterInput, 'workflowName' | 'nodeId'> & {}
export type RecordAnalyticsEventsInputBody = RecordAnalyticsEventsInput & {}
export type ListItemsInputBody = ListItemsInput & {}
export type AddToBasketInputBody = AddToBasketInput & {}
export type CancelOrderInputParams = Pick<CancelOrderInput, 'orderId'> & {}
export type CancelOrderInputBody = Omit<CancelOrderInput, 'orderId'> & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/api/auth{/*splat}': {
    readonly GET: HTTPWiringHandler<null, AuthHandlerOutput>,
    readonly POST: HTTPWiringHandler<null, AuthHandlerOutput>,
  },
  readonly '/workflow-run/:runId/stream': {
    readonly GET: HTTPWiringHandler<StreamWorkflowRunInput, null>,
  },
  readonly '/events/:topic': {
    readonly GET: HTTPWiringHandler<RealtimeEventStreamInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId': {
    readonly GET: HTTPWiringHandler<WorkflowStatusCheckerInput, WorkflowRunStatus>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamInput, null>,
  },
  readonly '/workflow/:workflowName/status/:runId/stream/full': {
    readonly GET: HTTPWiringHandler<WorkflowStatusStreamFullInput, null>,
  },
  readonly '/items': {
    readonly GET: HTTPWiringHandler<ListItemsInput, ListItemsOutput>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/stream': {
    readonly POST: HTTPWiringHandler<AgentStreamCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/rpc/agent/:agentName/resume': {
    readonly POST: HTTPWiringHandler<AgentResumeCallerInput, null>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
  },
  readonly '/workflow/:workflowName/start': {
    readonly POST: HTTPWiringHandler<WorkflowStarterInput, WorkflowStarterOutput>,
  },
  readonly '/workflow/:workflowName/approve/:runId': {
    readonly POST: HTTPWiringHandler<WorkflowApproverInput, WorkflowApproverOutput>,
  },
  readonly '/workflow/:workflowName/run': {
    readonly POST: HTTPWiringHandler<WorkflowRunnerInput, null>,
  },
  readonly '/workflow/:workflowName/graph/:nodeId': {
    readonly POST: HTTPWiringHandler<GraphStarterInput, GraphStarterOutput>,
  },
  readonly '/analytics': {
    readonly POST: HTTPWiringHandler<RecordAnalyticsEventsInput, RecordAnalyticsEventsOutput>,
  },
  readonly '/basket/items': {
    readonly POST: HTTPWiringHandler<AddToBasketInput, AddToBasketOutput>,
  },
  readonly '/orders/:orderId/cancel': {
    readonly POST: HTTPWiringHandler<CancelOrderInput, CancelOrderOutput>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  