/**
 * This file was generated by @pikku/cli@0.12.102
 */
// AUTO-GENERATED by pikku CLI — do not edit

import { pikkuBetterAuth as _pikkuBetterAuth } from '@pikku/better-auth'
import type { BetterAuthInstance, PikkuBetterAuthFactory } from '@pikku/better-auth'
import type { SingletonServices } from '../function/pikku-function-types.gen.js'
import { TypedSecretService } from '../secrets/pikku-secrets.gen.js'
import { TypedVariablesService } from '../variables/pikku-variables.gen.js'

type AuthSingletonServices = Omit<SingletonServices, 'secrets' | 'variables'> & {
  secrets: TypedSecretService
  variables: TypedVariablesService
}

export const pikkuBetterAuth = <I extends BetterAuthInstance>(
  factory: (services: AuthSingletonServices) => I | Promise<I>
): PikkuBetterAuthFactory<I> =>
  _pikkuBetterAuth((services) =>
    factory({
      ...services,
      secrets: new TypedSecretService(services.secrets),
      variables: new TypedVariablesService(services.variables),
    } as AuthSingletonServices)
  )
