/**
 * This file was generated by @pikku/cli@0.12.27
 */
/* Side-effect imports for direct middleware registration calls */
import '../../src/wirings/shop.security.js'
import '../../src/wirings/shop.http.js'