/**
 * This file was generated by @pikku/cli@0.12.102
 */
/* Side-effect imports for direct middleware registration calls */
import '../../src/middleware/cors.middleware.js'
import '../../src/wirings/shop.http.js'
import '../../src/scaffold/auth/auth-middleware.gen.js'