/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { pikkuState } from '@pikku/core/internal'
import type { WorkflowsRuntimeMeta } from '@pikku/core/workflow/types'

const workflowsMeta: WorkflowsRuntimeMeta = {}

pikkuState(null, 'workflows', 'meta', workflowsMeta)