/**
 * This file was generated by @pikku/cli@0.12.93
 */
/**
 * Scenario step map: the names `scenario.step/given/when/then` accepts, with
 * the input and output types of each step.
 */




interface ScenarioStepHandler<I, O> {
    input: I;
    output: O;
}

export type FlattenedScenarioStepMap = {
};
