/**
 * This file was generated by @pikku/cli@0.12.99
 */
/** Personas declared with definePersonas() */
import { createHttpPersonas } from '@pikku/core/persona'
import type {
  HttpPersonasConfig,
  ScenarioPersona,
  ResolvedPersona,
} from '@pikku/core/services'
import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'
import type { FlattenedRPCMap } from '../rpc/pikku-rpc-wirings-map.gen.d.js'

export const personaConfigs = {
  "visitor": {
    "id": "visitor",
    "name": "Visitor",
    "roles": [],
    "goals": [],
    "tags": [],
    "runnable": true,
    "sourceFile": "/root/pikku-templates/online-shop/packages/functions/src/personas.virtual-user.ts",
    "jobTitle": "Synthetic health-check user",
    "personality": "Signs in and checks their own session — proves auth end to end",
    "account": {},
    "email": "visitor@actors.local"
  },
  "susan": {
    "id": "susan",
    "name": "Susan",
    "roles": [
      "customer"
    ],
    "goals": [
      "Get the weekly order in under five minutes"
    ],
    "tags": [],
    "runnable": true,
    "sourceFile": "/root/pikku-templates/online-shop/packages/functions/src/personas.virtual-user.ts",
    "jobTitle": "Buys for a small café",
    "description": "Orders stock every week and watches the margins",
    "personality": "Hunts cheap deals. Tries three coupon codes before giving up, and abandons a basket if checkout asks for anything unexpected.",
    "disposition": "careless",
    "account": {},
    "email": "susan@actors.local"
  },
  "priya": {
    "id": "priya",
    "name": "Priya from Support",
    "roles": [
      "support"
    ],
    "goals": [
      "Resolve the customer’s problem without escalating"
    ],
    "tags": [],
    "runnable": true,
    "sourceFile": "/root/pikku-templates/online-shop/packages/functions/src/personas.virtual-user.ts",
    "jobTitle": "Customer support",
    "description": "Handles refunds and cancellations for other people’s orders",
    "personality": "Methodical. Reads the order history before touching anything, and says what she changed.",
    "account": {},
    "email": "priya@actors.local"
  },
  "alex": {
    "id": "alex",
    "name": "Alex the Owner",
    "roles": [
      "admin"
    ],
    "goals": [
      "Keep stock accurate",
      "See what sold this week"
    ],
    "tags": [],
    "runnable": true,
    "sourceFile": "/root/pikku-templates/online-shop/packages/functions/src/personas.virtual-user.ts",
    "jobTitle": "Shop owner",
    "description": "Runs the shop — prices, stock and who works here",
    "personality": "Impatient. Knows the catalogue by heart and expects bulk actions to exist.",
    "account": {},
    "email": "alex@actors.local"
  }
} as const satisfies Record<string, ResolvedPersona>

export type PersonaName = keyof typeof personaConfigs

/**
 * The same personas as a list, widened to `ResolvedPersona`. Iterating
 * `personaConfigs` directly yields the literal type of each entry, on which an
 * optional field a persona did not declare does not exist — so a seed reading
 * `roles` off every persona needs this instead.
 */
export const personaList: ResolvedPersona[] = Object.values(personaConfigs)

export type AgentName = keyof AgentMap & string
export type TypedPersonas = Record<
  PersonaName,
  ScenarioPersona<AgentName, FlattenedRPCMap>
>

export const createPersonas = (
  options: Omit<HttpPersonasConfig, 'personas'>
): TypedPersonas =>
  createHttpPersonas({
    ...options,
    personas: personaConfigs,
  }) as TypedPersonas
