/**
 * This file was generated by @pikku/cli@0.12.93
 */
/** Scenario actors declared in pikku.config.json (`scenarios.actors`) */
import {
  createHttpScenarioActors,
  type HttpScenarioActorsConfig,
  type ScenarioActor,
  type ScenarioActorConfig,
} from '@pikku/core/services'
import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'
import type { FlattenedRPCMap } from '../rpc/pikku-rpc-wirings-map.gen.d.js'

export const scenarioActorConfigs = {
  "shopper": {
    "email": "shopper@actors.local",
    "name": "Sam the Shopper",
    "jobTitle": "Customer",
    "personality": "A friendly customer who loves coffee and asks short, direct questions."
  }
} as const satisfies Record<string, ScenarioActorConfig>

export type ScenarioActorName = keyof typeof scenarioActorConfigs

/**
 * The same registry as a list, widened to `ScenarioActorConfig`. Iterating
 * `scenarioActorConfigs` directly yields the literal type of each entry, on
 * which an optional field an actor did not declare does not exist — so a seed
 * reading `scopes`/`roles` off every actor needs this instead.
 */
export const scenarioActorList: ScenarioActorConfig[] = Object.values(
  scenarioActorConfigs
)

export type AgentName = keyof AgentMap & string
export type TypedScenarioActors = Record<
  ScenarioActorName,
  ScenarioActor<AgentName, FlattenedRPCMap>
>

export const createScenarioActors = (
  options: Omit<HttpScenarioActorsConfig, 'actors'>
): TypedScenarioActors =>
  createHttpScenarioActors({
    ...options,
    actors: scenarioActorConfigs,
  }) as TypedScenarioActors
