/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { addWorkflow } from '@pikku/core/workflow'
import './pikku-workflow-wirings-meta.gen.js'
import { checkoutWorkflow } from '../../src/wirings/checkout.workflow.js'
import { refundWorkflow } from '../../src/wirings/checkout.workflow.js'

addWorkflow('checkoutWorkflow', checkoutWorkflow)
addWorkflow('refundWorkflow', refundWorkflow)

export type WorkflowNames = 'checkoutWorkflow' | 'refundWorkflow'