/**
 * This file was generated by @pikku/cli@0.12.27
 */
import { pikkuState } from '@pikku/core/internal'
import type { SerializedWorkflowGraphs } from '@pikku/inspector/workflow-graph'

const workflowsMeta: SerializedWorkflowGraphs = {}

pikkuState(null, 'workflows', 'meta', workflowsMeta)