/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */


import type { AIMessage, AgentRunRow, AIThread } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/ai-agent/ai-agent.types'

export type AddToBasketInput = {
    itemId: string;
    quantity: number;
}
export type AddToBasketOutput = {
    basketId: string;
    itemCount: number;
}
export type AgentApproveCallerInput = {
    agentName: string;
    runId: string;
    approvals: {
        toolCallId: string;
        approved: boolean;
    }[];
}
export type AgentCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AgentResumeCallerInput = {
    agentName: string;
    runId: string;
    toolCallId: string;
    approved: boolean;
}
export type AgentStreamCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AuthHandlerOutput = Promise<void> | Promise<any>
export type CancelOrderInput = {
    orderId: string;
}
export type CancelOrderOutput = {
    orderId: string;
    status: string;
}
export type CancelOrderToolInput = { orderId: string; }
export type CancelOrderToolOutput = { type: "text"; text: string; }[]
export type DeleteAgentThreadInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type DeleteAgentThreadOutput = {
    deleted: boolean;
}
export type EveryPageLoadsScenarioOutput = { routes: string[]; }
export type GetAgentThreadMessagesInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadMessagesOutput = AIMessage[]
export type GetAgentThreadRunsInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadRunsOutput = AgentRunRow[]
export type GetAgentThreadsInput = {
    agentName?: string | undefined;
    resourceId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type GetAgentThreadsOutput = AIThread[]
export type GetSessionInput = {}
export type GetSessionOutput = {
    userId: string;
    email: string;
    name: string | null;
}
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit: number;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        category: string;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
    }[];
}
export type ListItemsToolInput = { categorySlug?: string | undefined; search?: string | undefined; limit?: number | undefined; }
export type ListItemsToolOutput = { type: "text"; text: string; }[]
export type OpensPageInput = {
    path: string;
}
export type OpensPageOutput = {
    pathname: string;
    status: number | null;
}
export type PikkuConsoleGetSecretInput = {
    secretId: string;
}
export type PikkuConsoleGetSecretOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleGetVariableInput = {
    variableId: string;
}
export type PikkuConsoleGetVariableOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleHasSecretInput = {
    secretId: string;
}
export type PikkuConsoleHasSecretOutput = {
    exists: boolean;
}
export type PikkuConsoleSetSecretInput = {
    secretId: string;
    value: unknown;
}
export type PikkuConsoleSetSecretOutput = {
    success: boolean;
}
export type PikkuConsoleSetVariableInput = {
    variableId: string;
    value: unknown;
}
export type PikkuConsoleSetVariableOutput = {
    success: boolean;
}
export type RealtimeEventStreamInput = {
    topic: string;
}
export type RealtimeSubscribeInput = {
    topic: string;
}
export type RealtimeUnsubscribeInput = {
    topic: string;
}
export type RecordAnalyticsEventsInput = {
    events: {
        at?: number | undefined;
        event: {
            name: "page_viewed";
            path: string;
        } | {
            name: "signed_up";
        } | {
            name: "checkout_completed";
            amount: number;
            currency: string;
        };
    }[];
}
export type RecordAnalyticsEventsOutput = {
    accepted: number;
}
export type RestsOnPathInput = {
    path: string;
}
export type RestsOnPathOutput = {
    pathname: string;
}
export type RpcCallerInput = {
    rpcName: string;
    data?: unknown | undefined;
}
export type SecretSchema_betterAuthSecret = string
export type SecretSchema_scenarioActorSecret = string
export type SeesTextInput = {
    text: string;
}
export type SeesTextOutput = {
    text: string;
}
export type SendOrderConfirmationInput = {
    orderId: string;
    email: string;
}
export type SessionHealthScenarioOutput = { email: string; userId: string; }
export type SignedInActorReachesTheAppScenarioOutput = { pathname: string; email: string; }
export type SweepsAllPagesInput = {
    repoRoot: string;
}
export type SweepsAllPagesOutput = {
    routes: string[];
}
export type VariableSchema_corsOrigins = string
export type VariableSchema_frontendUrl = string
export type WatchOrderInput = { orderId: string; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'addToBasket': RPCHandler<AddToBasketInput, AddToBasketOutput>,
  readonly 'cancelOrder': RPCHandler<CancelOrderInput, CancelOrderOutput>,
  readonly 'getSession': RPCHandler<GetSessionInput, GetSessionOutput>,
  readonly 'listItems': RPCHandler<ListItemsInput, ListItemsOutput>,
  readonly 'getAgentThreads': RPCHandler<GetAgentThreadsInput, GetAgentThreadsOutput>,
  readonly 'getAgentThreadMessages': RPCHandler<GetAgentThreadMessagesInput, GetAgentThreadMessagesOutput>,
  readonly 'getAgentThreadRuns': RPCHandler<GetAgentThreadRunsInput, GetAgentThreadRunsOutput>,
  readonly 'deleteAgentThread': RPCHandler<DeleteAgentThreadInput, DeleteAgentThreadOutput>,
  readonly 'pikkuConsoleSetSecret': RPCHandler<PikkuConsoleSetSecretInput, PikkuConsoleSetSecretOutput>,
  readonly 'pikkuConsoleGetVariable': RPCHandler<PikkuConsoleGetVariableInput, PikkuConsoleGetVariableOutput>,
  readonly 'pikkuConsoleSetVariable': RPCHandler<PikkuConsoleSetVariableInput, PikkuConsoleSetVariableOutput>,
  readonly 'pikkuConsoleHasSecret': RPCHandler<PikkuConsoleHasSecretInput, PikkuConsoleHasSecretOutput>,
  readonly 'pikkuConsoleGetSecret': RPCHandler<PikkuConsoleGetSecretInput, PikkuConsoleGetSecretOutput>,
};


// Addon package RPC maps
import type { RPCMap as ConsoleRPCMap } from '@pikku/addon-console/.pikku/rpc/pikku-rpc-wirings-map.internal.gen.js'


// Utility type to prefix keys with namespace (skips 'any' to prevent type poisoning)
type PrefixKeys<T, Prefix extends string> = unknown extends T ? {} : {
  [K in keyof T as `${Prefix}:${string & K}`]: T[K]
}

// Merge all RPC maps with namespace prefixes
export type FlattenedRPCMap =
  RPCMap & PrefixKeys<ConsoleRPCMap, 'console'>

type IsAny<T> = 0 extends (1 & T) ? true : false
type IsVoidishInput<T> = IsAny<T> extends true
  ? false
  : [T] extends [void | null | undefined]
    ? true
    : false


export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  ...args: IsVoidishInput<FlattenedRPCMap[Name]['input']> extends true
    ? [name: Name]
    : [name: Name, data: FlattenedRPCMap[Name]['input']]
) => Promise<FlattenedRPCMap[Name]['output']>

export type RPCRemote = <Name extends keyof FlattenedRPCMap>(
  ...args: IsVoidishInput<FlattenedRPCMap[Name]['input']> extends true
    ? [name: Name]
    : [name: Name, data: FlattenedRPCMap[Name]['input']]
) => Promise<FlattenedRPCMap[Name]['output']>

import type { FlattenedWorkflowMap } from '../workflow/pikku-workflow-map.gen.d.js'

import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'

// Addon package Agent maps
import type { AgentMap as ConsoleAgentMap } from '@pikku/addon-console/.pikku/agent/pikku-agent-map.gen.d.js'


type FlattenedAgentMap =
  AgentMap & PrefixKeys<ConsoleAgentMap, 'console'>


import type { PikkuRPC } from '@pikku/core/rpc'

interface AIAgentInput {
  message: string
  threadId: string
  resourceId: string
}

export type TypedStartWorkflow = <Name extends keyof FlattenedWorkflowMap>(
  name: Name,
  input: FlattenedWorkflowMap[Name]['input'],
  options?: { startNode?: string }
) => Promise<{ runId: string }>

export type TypedRunWorkflow = <Name extends keyof FlattenedWorkflowMap>(
  name: Name,
  input: FlattenedWorkflowMap[Name]['input']
) => Promise<FlattenedWorkflowMap[Name]['output']>

export type TypedWorkflowStatus = (
  workflowName: string,
  runId: string
) => Promise<{ id: string; status: 'running' | 'suspended' | 'completed' | 'failed' | 'cancelled'; output?: unknown; error?: { message?: string } }>

type TypedAgentRun = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput) => Promise<any>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput
    ) => Promise<{ runId: string; result: FlattenedAgentMap[Name]['output']; usage: { inputTokens: number; outputTokens: number } }>

type TypedAgentStream = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput, options?: { requiresToolApproval?: 'all' | 'explicit' | false }) => Promise<void>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput,
      options?: { requiresToolApproval?: 'all' | 'explicit' | false }
    ) => Promise<void>

export type TypedPikkuRPC = PikkuRPC<RPCInvoke, RPCRemote, TypedStartWorkflow, TypedAgentRun, TypedAgentStream>
  