/**
 * This file was generated by @pikku/cli@0.12.93
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */

import type { MCPToolResponse } from '@pikku/core/mcp'
import type { ShippingAddress } from '../../src/wirings/checkout.workflow.js'
import type { AIMessage, AgentRunRow, AIThread } from '@pikku/core/dist/wirings/ai-agent/ai-agent.types'
import type { WorkflowRunStatus } from '@pikku/core/dist/wirings/workflow/workflow.types'

export type AddToBasketInput = {
    basketId: string;
    itemId: string;
    quantity: number;
}
export type AgentApproveCallerInput = {
    agentName: string;
    runId: string;
    approvals: {
        toolCallId: string;
        approved: boolean;
    }[];
}
export type AgentCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AgentCallerOutput = { runId: string; result: any; usage: { inputTokens: number; outputTokens: number; }; }
export type AgentResumeCallerInput = {
    agentName: string;
    runId: string;
    toolCallId: string;
    approved: boolean;
}
export type AgentStreamCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AuthHandlerOutput = Promise<void> | Promise<any>
export type CancelOrderInput = {
    orderId: string;
}
export type ChargeCardInput = { orderId: string; totalCents: number; cardToken?: string | undefined; }
export type ChargeCardOutput = { status: "succeeded"; providerRef: string; } | { status: "failed"; reason: string; }
export type CheckItemAvailabilityInput = { itemId: string; }
export type CheckItemAvailabilityOutput = { available: boolean; stock: number; name: string; }
export type CheckOrderRefundableInput = { orderId: string; }
export type CheckOrderRefundableOutput = { eligible: boolean; totalCents: number | number; }
export type CheckoutWorkflowInput = { basketId: string; userId: string; shippingAddress: ShippingAddress; cardToken?: string | undefined; }
export type CheckoutWorkflowOutput = { orderId: string; status: "paid" | "payment_failed"; totalCents: number; }
export type CreateCategoryInput = {
    name: string;
    slug: string;
    description?: string | undefined;
}
export type CreateCategoryOutput = {
    categoryId: string;
    name: string;
    slug: string;
}
export type CreateItemInput = {
    categoryId: string;
    name: string;
    slug: string;
    description?: string | undefined;
    priceCents: number;
    stock: number;
    imageUrl?: string | undefined;
}
export type CreateItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    priceCents: number;
    stock: number;
}
export type CreateOrderInput = {
    basketId: string;
    shippingAddress: {
        line1: string;
        line2?: string | undefined;
        city: string;
        postcode: string;
        country: string;
    };
    cardToken?: string | undefined;
}
export type CreateOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
}
export type CreateOrderRecordInput = { userId: string; totalCents: number; shippingAddress: ShippingAddress; items: { itemId: string; quantity: number; priceCents: number; }[]; }
export type CreateOrderRecordOutput = { orderId: any; }
export type CreateOrderWithValidationInput = { sessionId: string; }
export type CreateOrderWithValidationOutput = { valid: boolean; itemCount: number; sessionId: string; }
export type DeleteAgentThreadInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type DeleteAgentThreadOutput = {
    deleted: boolean;
}
export type DeleteOrderInput = { orderId: string; }
export type FinalizeOrderInput = { orderId: string; basketId: string; userId: string; status: "paid" | "payment_failed"; }
export type GetAgentThreadMessagesInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadMessagesOutput = AIMessage[]
export type GetAgentThreadRunsInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadRunsOutput = AgentRunRow[]
export type GetAgentThreadsInput = {
    agentName?: string | undefined;
    resourceId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type GetAgentThreadsOutput = AIThread[]
export type GetBasketInput = {
    sessionId?: string | undefined;
}
export type GetBasketOutput = {
    basketId: string;
    items: {
        basketItemId: string;
        itemId: string;
        name: string;
        slug: string;
        priceCents: number;
        imageUrl: string | null;
        quantity: number;
        lineTotalCents: number;
    }[];
    totalCents: number;
    itemCount: number;
}
export type GetItemForAIInput = { itemId: string; }
export type GetItemForAIOutput = { type: "text"; text: string; }[]
export type GetItemInput = {
    itemId: string;
}
export type GetItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetItemToolInput = { itemId: string; }
export type GetItemToolOutput = { type: "text"; text: string; }[]
export type GetItemV1Input = {
    itemId: string;
}
export type GetItemV1Output = {
    itemId: string;
    name: string;
    priceCents: number;
}
export type GetItemV2Input = {
    itemId: string;
}
export type GetItemV2Output = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetOrderInput = {
    orderId: string;
}
export type GetOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
    shippingAddress: {
        [key: string]: unknown;
    };
    items: {
        itemId: string;
        name: string;
        quantity: number;
        unitPriceCents: number;
        lineTotalCents: number;
    }[];
    createdAt: string;
}
export type GetOrderThreeParamsInput = { orderId: any; }
export type GetOrderThreeParamsOutput = { order: { orderId: string; status: string; totalCents: number; userId: string; shippingAddress: string; createdAt: string; updatedAt: string; }; viewer: string; }
export type GetProfileOutput = { name: string; userId: string; email: string; role: string; }
export type GraphStarterInput = {
    workflowName: string;
    nodeId: string;
    data?: unknown | undefined;
}
export type GraphStarterOutput = {
    runId: string;
}
export type HandlePaymentWebhookInput = { text: string; raw: unknown; }
export type HandlePaymentWebhookOutput = { received: boolean; }
export type HttpPostAgentsShopOutput = { runId: string; result: string; usage: { inputTokens: number; outputTokens: number; }; }
export type HttpPostAgentsShopStreamInput = { agentName?: string | undefined; message: string; threadId: string; resourceId: string; }
export type IssueRefundInput = { orderId: string; }
export type ListCategoriesOutput = {
    categoryId: string;
    name: string;
    slug: string;
    description: string | null;
}[]
export type ListCategoriesToolOutput = { type: "text"; text: string; }[]
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        description: string | null;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
        category: {
            categoryId: string;
            name: string;
            slug: string;
        };
    }[];
    total: number;
}
export type ListItemsToolInput = { categorySlug?: string | undefined; search?: string | undefined; limit?: number | undefined; offset?: number | undefined; }
export type ListItemsToolOutput = { type: "text"; text: string; }[]
export type ListOrdersInput = {
    limit: number;
    offset: number;
}
export type ListOrdersOutput = { orderId: string; status: string; totalCents: number; createdAt: string; }[]
export type NotifyOrderShippedInput = { orderId: string; }
export type OnLowStockInput = {
    itemId: string;
    name: string;
    stock: number;
}
export type PikkuConsoleGetSecretInput = {
    secretId: string;
}
export type PikkuConsoleGetSecretOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleGetVariableInput = {
    variableId: string;
}
export type PikkuConsoleGetVariableOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleHasSecretInput = {
    secretId: string;
}
export type PikkuConsoleHasSecretOutput = {
    exists: boolean;
}
export type PikkuConsoleSetSecretInput = {
    secretId: string;
    value: unknown;
}
export type PikkuConsoleSetSecretOutput = {
    success: boolean;
}
export type PikkuConsoleSetVariableInput = {
    variableId: string;
    value: unknown;
}
export type PikkuConsoleSetVariableOutput = {
    success: boolean;
}
export type PlaceOrderInput = { basketId: string; }
export type PlaceOrderOutput = { orderId: any; }
export type ProcessExportInput = { exportId: string; }
export type ProcessPaymentInput = { orderId: string; amountCents: number; }
export type ProcessPaymentOutput = { providerRef: string; status: "succeeded"; }
export type RefundWorkflowInput = { orderId: string; reason: string; }
export type RefundWorkflowOutput = { orderId: string; refunded: boolean; message: string; }
export type RemoveFromBasketInput = {
    basketId: string;
    itemId: string;
}
export type RpcCallerInput = {
    rpcName: string;
    data?: unknown | undefined;
}
export type SecretSchema_betterAuthSecret = string
export type SecretSchema_stripeSecretKey = string
export type SendOrderConfirmationInput = {
    orderId: string;
    userId: string;
}
export type ShopperAsksTheAssistantOutput = { itemCount: number; }
export type ShopperBuysAnItemOutput = { orderId: string; totalCents: number; }
export type StartCheckoutInput = { basketId: string; userId: string; shippingAddress: ShippingAddress; cardToken?: string | undefined; }
export type StartCheckoutOutput = { runId: string; }
export type StockPollTriggerInput = { thresholdStock: number; }
export type StockPollTriggerOutput = { itemId: string; name: string; stock: number; }
export type SubscribeToOrderInput = { orderId: string; }
export type UnsubscribeFromOrderInput = { orderId: string; }
export type UpdateItemInput = {
    itemId: string;
    name?: string | undefined;
    description?: string | undefined;
    priceCents?: number | undefined;
    stock?: number | undefined;
    imageUrl?: (string | null) | undefined;
    isActive?: boolean | undefined;
}
export type UpdateStockToolInput = { itemId: string; stock: number; }
export type UpdateStockToolOutput = { type: "text"; text: string; }[]
export type ValidateBasketInput = { basketId: string; }
export type ValidateBasketOutput = { items: { itemId: string; quantity: number; priceCents: number; }[]; totalCents: number; }
export type VariableSchema_betterAuthUrl = string
export type VariableSchema_databaseUrl = string
export type VariableSchema_lowStockThreshold = number
export type VariableSchema_scenarioActorSecret = string
export type WorkflowApproverInput = {
    workflowName: string;
    runId: string;
    reason: string;
    decision: unknown;
}
export type WorkflowApproverOutput = {
    ok: true;
}
export type WorkflowRunnerInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterOutput = {
    runId: string;
}
export type WorkflowStatusCheckerInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamFullInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamInput = {
    workflowName: string;
    runId: string;
}
export type WriteAuditEventInput = {
    entityType: string;
    entityId: string;
    action: string;
    actorId?: string | undefined;
    payload?: {
        [key: string]: unknown;
    } | undefined;
}

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'addToBasket': RPCHandler<AddToBasketInput, null>,
  readonly 'getBasket': RPCHandler<GetBasketInput, GetBasketOutput>,
  readonly 'removeFromBasket': RPCHandler<RemoveFromBasketInput, null>,
  readonly 'createCategory': RPCHandler<CreateCategoryInput, CreateCategoryOutput>,
  readonly 'listCategories': RPCHandler<null, ListCategoriesOutput>,
  readonly 'createItem': RPCHandler<CreateItemInput, CreateItemOutput>,
  readonly 'getItemV1': RPCHandler<GetItemV1Input, GetItemV1Output>,
  readonly 'getItem@v1': RPCHandler<GetItemV1Input, GetItemV1Output>,
  readonly 'getItemV2': RPCHandler<GetItemV2Input, GetItemV2Output>,
  readonly 'getItem@v2': RPCHandler<GetItemV2Input, GetItemV2Output>,
  readonly 'getItem': RPCHandler<GetItemInput, GetItemOutput>,
  readonly 'listItems': RPCHandler<ListItemsInput, ListItemsOutput>,
  readonly 'updateItem': RPCHandler<UpdateItemInput, null>,
  readonly 'sendOrderConfirmation': RPCHandler<SendOrderConfirmationInput, null>,
  readonly 'writeAuditEvent': RPCHandler<WriteAuditEventInput, null>,
  readonly 'cancelOrder': RPCHandler<CancelOrderInput, null>,
  readonly 'createOrder': RPCHandler<CreateOrderInput, CreateOrderOutput>,
  readonly 'getOrderThreeParams': RPCHandler<GetOrderThreeParamsInput, GetOrderThreeParamsOutput>,
  readonly 'getOrder': RPCHandler<GetOrderInput, GetOrderOutput>,
  readonly 'listOrders': RPCHandler<ListOrdersInput, ListOrdersOutput>,
  readonly 'cleanupAbandonedBaskets': RPCHandler<null, null>,
  readonly 'dailySalesReport': RPCHandler<null, null>,
  readonly 'agentCaller': RPCHandler<AgentCallerInput, AgentCallerOutput>,
  readonly 'agentStreamCaller': RPCHandler<AgentStreamCallerInput, null>,
  readonly 'agentApproveCaller': RPCHandler<AgentApproveCallerInput, null>,
  readonly 'agentResumeCaller': RPCHandler<AgentResumeCallerInput, null>,
  readonly 'getAgentThreads': RPCHandler<GetAgentThreadsInput, GetAgentThreadsOutput>,
  readonly 'getAgentThreadMessages': RPCHandler<GetAgentThreadMessagesInput, GetAgentThreadMessagesOutput>,
  readonly 'getAgentThreadRuns': RPCHandler<GetAgentThreadRunsInput, GetAgentThreadRunsOutput>,
  readonly 'deleteAgentThread': RPCHandler<DeleteAgentThreadInput, DeleteAgentThreadOutput>,
  readonly 'authHandler': RPCHandler<null, AuthHandlerOutput>,
  readonly 'pikkuConsoleSetSecret': RPCHandler<PikkuConsoleSetSecretInput, PikkuConsoleSetSecretOutput>,
  readonly 'pikkuConsoleGetVariable': RPCHandler<PikkuConsoleGetVariableInput, PikkuConsoleGetVariableOutput>,
  readonly 'pikkuConsoleSetVariable': RPCHandler<PikkuConsoleSetVariableInput, PikkuConsoleSetVariableOutput>,
  readonly 'pikkuConsoleHasSecret': RPCHandler<PikkuConsoleHasSecretInput, PikkuConsoleHasSecretOutput>,
  readonly 'pikkuConsoleGetSecret': RPCHandler<PikkuConsoleGetSecretInput, PikkuConsoleGetSecretOutput>,
  readonly 'rpcCaller': RPCHandler<RpcCallerInput, null>,
  readonly 'workflowStarter': RPCHandler<WorkflowStarterInput, WorkflowStarterOutput>,
  readonly 'workflowRunner': RPCHandler<WorkflowRunnerInput, null>,
  readonly 'workflowStatusChecker': RPCHandler<WorkflowStatusCheckerInput, WorkflowRunStatus>,
  readonly 'workflowStatusStream': RPCHandler<WorkflowStatusStreamInput, null>,
  readonly 'workflowStatusStreamFull': RPCHandler<WorkflowStatusStreamFullInput, null>,
  readonly 'graphStarter': RPCHandler<GraphStarterInput, GraphStarterOutput>,
  readonly 'workflowApprover': RPCHandler<WorkflowApproverInput, WorkflowApproverOutput>,
  readonly 'validateBasket': RPCHandler<ValidateBasketInput, ValidateBasketOutput>,
  readonly 'createOrderRecord': RPCHandler<CreateOrderRecordInput, CreateOrderRecordOutput>,
  readonly 'chargeCard': RPCHandler<ChargeCardInput, ChargeCardOutput>,
  readonly 'finalizeOrder': RPCHandler<FinalizeOrderInput, null>,
  readonly 'startCheckout': RPCHandler<StartCheckoutInput, StartCheckoutOutput>,
  readonly 'checkOrderRefundable': RPCHandler<CheckOrderRefundableInput, CheckOrderRefundableOutput>,
  readonly 'issueRefund': RPCHandler<IssueRefundInput, null>,
  readonly 'subscribeToOrder': RPCHandler<SubscribeToOrderInput, null>,
  readonly 'unsubscribeFromOrder': RPCHandler<UnsubscribeFromOrderInput, null>,
  readonly 'notifyOrderShipped': RPCHandler<NotifyOrderShippedInput, null>,
  readonly 'conditionalReport': RPCHandler<null, null>,
  readonly 'handlePaymentWebhook': RPCHandler<HandlePaymentWebhookInput, HandlePaymentWebhookOutput>,
  readonly 'listCategoriesTool': RPCHandler<null, MCPToolResponse>,
  readonly 'listItemsTool': RPCHandler<ListItemsToolInput, MCPToolResponse>,
  readonly 'getItemTool': RPCHandler<GetItemToolInput, MCPToolResponse>,
  readonly 'getItemForAI': RPCHandler<GetItemForAIInput, MCPToolResponse>,
  readonly 'updateStockTool': RPCHandler<UpdateStockToolInput, MCPToolResponse>,
  readonly 'placeOrder': RPCHandler<PlaceOrderInput, PlaceOrderOutput>,
  readonly 'processExport': RPCHandler<ProcessExportInput, null>,
  readonly 'checkItemAvailability': RPCHandler<CheckItemAvailabilityInput, CheckItemAvailabilityOutput>,
  readonly 'createOrderWithValidation': RPCHandler<CreateOrderWithValidationInput, CreateOrderWithValidationOutput>,
  readonly 'shopperBuysAnItem': RPCHandler<null, ShopperBuysAnItemOutput>,
  readonly 'shopperAsksTheAssistant': RPCHandler<null, ShopperAsksTheAssistantOutput>,
  readonly 'processPayment': RPCHandler<ProcessPaymentInput, ProcessPaymentOutput>,
  readonly 'deleteOrder': RPCHandler<DeleteOrderInput, null>,
  readonly 'getProfile': RPCHandler<null, GetProfileOutput>,
  readonly 'onLowStock': RPCHandler<OnLowStockInput, null>,
  readonly 'getItem@v3': RPCHandler<GetItemInput, GetItemOutput>,
};


// Addon package RPC maps
import type { RPCMap as ConsoleRPCMap } from '@pikku/addon-console/.pikku/rpc/pikku-rpc-wirings-map.internal.gen.js'


// Utility type to prefix keys with namespace (skips 'any' to prevent type poisoning)
type PrefixKeys<T, Prefix extends string> = unknown extends T ? {} : {
  [K in keyof T as `${Prefix}:${string & K}`]: T[K]
}

// Merge all RPC maps with namespace prefixes
export type FlattenedRPCMap =
  RPCMap & PrefixKeys<ConsoleRPCMap, 'console'>

type IsAny<T> = 0 extends (1 & T) ? true : false
type IsVoidishInput<T> = IsAny<T> extends true
  ? false
  : [T] extends [void | null | undefined]
    ? true
    : false


export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  ...args: IsVoidishInput<FlattenedRPCMap[Name]['input']> extends true
    ? [name: Name]
    : [name: Name, data: FlattenedRPCMap[Name]['input']]
) => Promise<FlattenedRPCMap[Name]['output']>

export type RPCRemote = <Name extends keyof FlattenedRPCMap>(
  ...args: IsVoidishInput<FlattenedRPCMap[Name]['input']> extends true
    ? [name: Name]
    : [name: Name, data: FlattenedRPCMap[Name]['input']]
) => Promise<FlattenedRPCMap[Name]['output']>

import type { FlattenedWorkflowMap } from '../workflow/pikku-workflow-map.gen.d.js'

import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'

// Addon package Agent maps
import type { AgentMap as ConsoleAgentMap } from '@pikku/addon-console/.pikku/agent/pikku-agent-map.gen.d.js'


type FlattenedAgentMap =
  AgentMap & PrefixKeys<ConsoleAgentMap, 'console'>


import type { PikkuRPC } from '@pikku/core/rpc'

interface AIAgentInput {
  message: string
  threadId: string
  resourceId: string
}

export type TypedStartWorkflow = <Name extends keyof FlattenedWorkflowMap>(
  name: Name,
  input: FlattenedWorkflowMap[Name]['input'],
  options?: { startNode?: string }
) => Promise<{ runId: string }>

export type TypedRunWorkflow = <Name extends keyof FlattenedWorkflowMap>(
  name: Name,
  input: FlattenedWorkflowMap[Name]['input']
) => Promise<FlattenedWorkflowMap[Name]['output']>

export type TypedWorkflowStatus = (
  workflowName: string,
  runId: string
) => Promise<{ id: string; status: 'running' | 'suspended' | 'completed' | 'failed' | 'cancelled'; output?: unknown; error?: { message?: string } }>

type TypedAgentRun = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput) => Promise<any>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput
    ) => Promise<{ runId: string; result: FlattenedAgentMap[Name]['output']; usage: { inputTokens: number; outputTokens: number } }>

type TypedAgentStream = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput, options?: { requiresToolApproval?: 'all' | 'explicit' | false }) => Promise<void>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput,
      options?: { requiresToolApproval?: 'all' | 'explicit' | false }
    ) => Promise<void>

export type TypedPikkuRPC = PikkuRPC<RPCInvoke, RPCRemote, TypedStartWorkflow, TypedAgentRun, TypedAgentStream>
  