/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { pikkuState } from '@pikku/core/ecosystem'
import metaData from './pikku-rpc-wirings-meta.internal.gen.json' with { type: 'json' }
pikkuState(null, 'rpc', 'meta', metaData as Record<string, string>)