/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * Auto-generated public agent schemas
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { z } from 'zod'

export const Attachment = z.object({
  type: z.enum(['image', 'file']),
  data: z.string().optional(),
  url: z.string().optional(),
  mediaType: z.string().optional(),
  filename: z.string().optional(),
})

export const AgentCall = z.object({
  agentName: z.string(),
  message: z.string(),
  threadId: z.string(),
  resourceId: z.string(),
  attachments: z.array(Attachment).optional(),
  model: z.string().optional(),
  temperature: z.number().optional(),
  context: z.string().optional(),
})

export const AgentApproval = z.object({
  agentName: z.string(),
  runId: z.string(),
  approvals: z.array(
    z.object({ toolCallId: z.string(), approved: z.boolean() })
  ),
})

export const AgentResume = z.object({
  agentName: z.string(),
  runId: z.string(),
  toolCallId: z.string(),
  approved: z.boolean(),
})

export const ThreadsQuery = z.object({
  agentName: z.string().optional(),
  resourceId: z.string().optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
})

export const ThreadRef = z.object({
  threadId: z.string(),
  resourceId: z.string().optional(),
})

export const ThreadDeleted = z.object({ deleted: z.boolean() })
