/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { canAccessThread, threadOwnerConstraint } from '@pikku/core/ai-agent'
import { pikkuSessionlessFunc, pikkuPermission, defineHTTPRoutes, wireHTTPRoutes } from '../../../.pikku/pikku-types.gen.js'
import {
  AgentCall,
  AgentApproval,
  AgentResume,
  ThreadsQuery,
  ThreadRef,
  ThreadDeleted,
} from './agent.schemas.gen.js'

/**
 * Thread reads are keyed by a caller-supplied `threadId`, so ownership cannot
 * come from the request — it is derived from the session and checked against
 * the stored thread's resourceId.
 */
export const isThreadOwner = pikkuPermission<{ threadId: string }>(
  async ({ agentRunService }, { threadId }, { session }) => {
    const thread = await agentRunService.getThread(threadId)
    // A missing thread is denied rather than 404'd so it is indistinguishable
    // from one owned by someone else — no existence oracle.
    if (!thread) return false
    return canAccessThread(thread.resourceId, session)
  }
)

export const agentCaller = pikkuSessionlessFunc({
  tags: ['pikku'],
  auth: false,
  input: AgentCall,
  func: async (_services, data, { rpc }) => {
    return await rpc.agent.run(data.agentName as any, {
      message: data.message,
      threadId: data.threadId,
      resourceId: data.resourceId,
      ...(data.attachments ? { attachments: data.attachments } : {}),
      ...(data.model ? { model: data.model } : {}),
      ...(data.temperature !== undefined ? { temperature: data.temperature } : {}),
      ...(data.context ? { context: data.context } : {}),
    })
  },
})

export const agentStreamCaller = pikkuSessionlessFunc({
  tags: ['pikku'],
  auth: false,
  input: AgentCall,
  func: async (_services, data, { rpc }) => {
    await rpc.agent.stream(data.agentName as any, {
      message: data.message,
      threadId: data.threadId,
      resourceId: data.resourceId,
      ...(data.attachments ? { attachments: data.attachments } : {}),
      ...(data.model ? { model: data.model } : {}),
      ...(data.temperature !== undefined ? { temperature: data.temperature } : {}),
      ...(data.context ? { context: data.context } : {}),
    })
  },
})

export const agentApproveCaller = pikkuSessionlessFunc({
  tags: ['pikku'],
  auth: false,
  input: AgentApproval,
  func: async (_services, { runId, approvals, agentName }, { rpc }) => {
    return await rpc.agent.approve(runId, approvals, agentName)
  },
})

export const agentResumeCaller = pikkuSessionlessFunc({
  tags: ['pikku'],
  auth: false,
  input: AgentResume,
  func: async (_services, data, { rpc }) => {
    await rpc.agent.resume(data.runId, {
      toolCallId: data.toolCallId,
      approved: data.approved,
    })
  },
})

export const getAgentThreads = pikkuSessionlessFunc({
  tags: ['pikku', 'pikku:agent'],
  input: ThreadsQuery,
  title: 'Get Agent Threads',
  description:
    'Returns the caller\'s AI agent threads from storage. Accepts optional filters: agentName, resourceId, limit, and offset for pagination.',
  expose: true,
  auth: false,
  func: async ({ agentRunService }, input, { session }) => {
    // `owners` is an authorization constraint derived from the session, never
    // from input — `resourceId` remains a caller-supplied filter within it.
    return await agentRunService.listThreads({
      agentName: input?.agentName,
      resourceId: input?.resourceId,
      owners: threadOwnerConstraint(session),
      limit: input?.limit,
      offset: input?.offset,
    })
  },
})

export const getAgentThreadMessages = pikkuSessionlessFunc({
  tags: ['pikku', 'pikku:agent'],
  input: ThreadRef,
  title: 'Get Agent Thread Messages',
  description:
    'Returns all messages for a given AI agent thread, ordered by creation time.',
  expose: true,
  auth: false,
  permissions: { owner: isThreadOwner },
  func: async ({ agentRunService }, input) => {
    return await agentRunService.getThreadMessages(input.threadId)
  },
})

export const getAgentThreadRuns = pikkuSessionlessFunc({
  tags: ['pikku', 'pikku:agent'],
  input: ThreadRef,
  title: 'Get Agent Thread Runs',
  description:
    'Returns the run history for a given AI agent thread, ordered by creation time.',
  expose: true,
  auth: false,
  permissions: { owner: isThreadOwner },
  func: async ({ agentRunService }, input) => {
    return await agentRunService.getThreadRuns(input.threadId)
  },
})

export const deleteAgentThread = pikkuSessionlessFunc({
  tags: ['pikku', 'pikku:agent'],
  input: ThreadRef,
  output: ThreadDeleted,
  title: 'Delete Agent Thread',
  description:
    'Deletes an AI agent thread and all of its persisted state.',
  expose: true,
  auth: false,
  permissions: { owner: isThreadOwner },
  func: async ({ agentRunService }, input) => {
    const deleted = await agentRunService.deleteThread(input.threadId)
    return { deleted }
  },
})

export const agentRoutes = defineHTTPRoutes({
  auth: false,
  tags: ['pikku:public'],
  routes: {
    agentRun: {
      route: '/rpc/agent/:agentName',
      method: 'post',
      func: agentCaller,
    },
    agentStream: {
      route: '/rpc/agent/:agentName/stream',
      method: 'post',
      sse: true,
      func: agentStreamCaller,
    },
    agentApprove: {
      route: '/rpc/agent/:agentName/approve',
      method: 'post',
      func: agentApproveCaller,
    },
    agentResume: {
      route: '/rpc/agent/:agentName/resume',
      method: 'post',
      sse: true,
      func: agentResumeCaller,
    },
  },
})

wireHTTPRoutes({ routes: { agent: agentRoutes } })
