/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * Auto-generated public RPC HTTP endpoint
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { pikkuSessionlessFunc, wireHTTP } from '../../../.pikku/pikku-types.gen.js'
import { RPCCall } from './rpc-public.schemas.gen.js'

export const rpcCaller = pikkuSessionlessFunc({
  tags: ['pikku'],
  auth: true,
  input: RPCCall,
  func: async (_services, { rpcName, data }, { rpc }) => {
    return await rpc.exposed(rpcName, data)
  },
})

wireHTTP({
  route: '/rpc/:rpcName',
  method: 'post',
  auth: true,
  tags: ['pikku'],
  func: rpcCaller,
})
