/**
 * This file was generated by @pikku/cli@0.12.93
 */
export { wireScope } from '@pikku/core/scope'
export type { CoreScopes, CoreScopeNode, FlatScope, ScopeDefinitionMeta, ScopeDefinitionsMeta } from '@pikku/core/scope'
