/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * This file was generated by the @pikku/cli
 */
import { definePersonas as definePersonasCore } from '@pikku/core/persona'
import type { CorePersona, PersonaMeta, PersonasMeta } from '@pikku/core/persona'
import type { SystemRoleName } from './pikku-roles.gen.js'
import definitions from './pikku-personas-meta.gen.json' with { type: 'json' }

/** Every declared persona. */
export type PersonaId =
  | 'alex'
  | 'priya'
  | 'shopper'
  | 'visitor'

/**
 * The personas a virtual user can actually be.
 *
 * Excludes anyone whose only login is a provider account — driving a consent
 * screen needs a human — and anyone declared `runnable: false`, who exists to
 * be acted upon rather than to act.
 */
export type RunnablePersonaId =
  | 'alex'
  | 'priya'
  | 'shopper'
  | 'visitor'

/** Every environment configured in pikku.config.json. */
export type EnvironmentName = never

/**
 * A persona whose roles are checked against `defineSystemRole` and whose
 * environments are checked against the config.
 *
 * Omitting `environments` means every environment except the ones flagged
 * `production: true`. Naming a production one additionally requires
 * `disposition: 'accountable'`, which the type cannot express and `pikku`
 * refuses at build time.
 */
export type TypedPersona = Omit<CorePersona, 'roles' | 'environments'> & {
  roles?: SystemRoleName[]
  environments?: EnvironmentName[]
}

/**
 * Declare the people who use this application.
 *
 * A persona while running is a virtual user; there is no second declaration.
 */
export const definePersonas = (personas: Record<string, TypedPersona>): void =>
  definePersonasCore(personas)

/** Declared personas, keyed by id. Read by the console and `pikku persona`. */
export const PERSONAS: PersonasMeta = definitions as unknown as PersonasMeta

export const PERSONA_LIST: PersonaMeta[] = Object.values(PERSONAS)
