/**
 * This file was generated by @pikku/cli@0.12.102
 */
export { defineScope } from '@pikku/core/scope'
export type { CoreScopes, CoreScopeNode, FlatScope, ScopeDefinitionMeta, ScopeDefinitionsMeta } from '@pikku/core/scope'
export { defineSystemRole } from '@pikku/core/role'
export type { CoreSystemRole, CoreSystemRoles, SystemRole, SystemRoleDefinitionMeta, SystemRoleDefinitionsMeta } from '@pikku/core/role'
