/**
 * This file was generated by @pikku/cli@0.12.102
 */
/**
 * This file was generated by the @pikku/cli
 */
import { defineSecret } from '@pikku/core/secret'
import { z } from 'zod'

export const ScenarioActorSecretSchema = z.string()

defineSecret({
  name: 'scenarioActorSecret',
  displayName: 'Scenario Actor Secret',
  description:
    'Signing secret that lets scenarios and virtual users sign in as a declared persona',
  secretId: 'SCENARIO_ACTOR_SECRET',
  schema: ScenarioActorSecretSchema,
})
