/**
 * This file was generated by @pikku/cli@0.12.102
 */
/* The files with an addChannel function call */
import '../../src/scaffold/realtime/events.gen.js'
import '../../src/wirings/shop.channel.js'