/**
 * This file was generated by @pikku/cli@0.12.27
 */
import { pikkuState } from '@pikku/core/internal'
import type { ChannelsMeta } from '@pikku/core/channel'
import metaData from './pikku-channels-meta.gen.json' with { type: 'json' }
pikkuState(null, 'channel', 'meta', metaData as ChannelsMeta)