/**
 * This file was generated by @pikku/cli@0.12.99
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */

import type { AIThread, AIMessage, AgentRunRow } from '.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/ai-agent/ai-agent.types'

import type { AIThread, AIMessage, AgentRunRow } from '/root/pikku-templates/online-shop/node_modules/.bun/@pikku+core@0.12.79/node_modules/@pikku/core/dist/wirings/ai-agent/ai-agent.types.d.ts'

export type AddToBasketInput = {
    itemId: string;
    quantity: number;
}
export type AddToBasketOutput = {
    basketId: string;
    itemCount: number;
}
export type AgentApproveCallerInput = {
    agentName: string;
    runId: string;
    approvals: {
        toolCallId: string;
        approved: boolean;
    }[];
}
export type AgentCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AgentResumeCallerInput = {
    agentName: string;
    runId: string;
    toolCallId: string;
    approved: boolean;
}
export type AgentStreamCallerInput = {
    agentName: string;
    message: string;
    threadId: string;
    resourceId: string;
    attachments?: {
        type: "image" | "file";
        data?: string | undefined;
        url?: string | undefined;
        mediaType?: string | undefined;
        filename?: string | undefined;
    }[] | undefined;
    model?: string | undefined;
    temperature?: number | undefined;
    context?: string | undefined;
}
export type AuthHandlerOutput = Promise<void> | Promise<any>
export type CancelOrderInput = {
    orderId: string;
}
export type CancelOrderOutput = {
    orderId: string;
    status: string;
}
export type CancelOrderToolInput = { orderId: string; }
export type CancelOrderToolOutput = { type: "text"; text: string; }[]
export type DeleteAgentThreadInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type DeleteAgentThreadOutput = {
    deleted: boolean;
}
export type EveryPageLoadsScenarioOutput = { routes: string[]; }
export type GetAgentThreadMessagesInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadMessagesOutput = AIMessage[]
export type GetAgentThreadRunsInput = {
    threadId: string;
    resourceId?: string | undefined;
}
export type GetAgentThreadRunsOutput = AgentRunRow[]
export type GetAgentThreadsInput = {
    agentName?: string | undefined;
    resourceId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
export type GetAgentThreadsOutput = AIThread[]
export type GetSessionInput = {}
export type GetSessionOutput = {
    userId: string;
    email: string;
    name: string | null;
}
export type GraphStarterInput = {
    workflowName: string;
    nodeId: string;
    data?: unknown | undefined;
}
export type GraphStarterOutput = {
    runId: string;
}
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit: number;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        category: string;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
    }[];
}
export type ListItemsToolInput = { categorySlug?: string | undefined; search?: string | undefined; limit?: number | undefined; }
export type ListItemsToolOutput = { type: "text"; text: string; }[]
export type OpensPageInput = {
    path: string;
}
export type OpensPageOutput = {
    pathname: string;
    status: number | null;
}
export type PikkuConsoleGetSecretInput = {
    secretId: string;
}
export type PikkuConsoleGetSecretOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleGetVariableInput = {
    variableId: string;
}
export type PikkuConsoleGetVariableOutput = {
    exists: boolean;
    value: unknown | null;
}
export type PikkuConsoleHasSecretInput = {
    secretId: string;
}
export type PikkuConsoleHasSecretOutput = {
    exists: boolean;
}
export type PikkuConsoleSetSecretInput = {
    secretId: string;
    value: unknown;
}
export type PikkuConsoleSetSecretOutput = {
    success: boolean;
}
export type PikkuConsoleSetVariableInput = {
    variableId: string;
    value: unknown;
}
export type PikkuConsoleSetVariableOutput = {
    success: boolean;
}
export type RealtimeEventStreamInput = {
    topic: string;
}
export type RealtimeSubscribeInput = {
    topic: string;
}
export type RealtimeUnsubscribeInput = {
    topic: string;
}
export type RecordAnalyticsEventsInput = {
    events: {
        at?: number | undefined;
        event: {
            name: "page_viewed";
            path: string;
        } | {
            name: "signed_up";
        } | {
            name: "checkout_completed";
            amount: number;
            currency: string;
        };
    }[];
}
export type RecordAnalyticsEventsOutput = {
    accepted: number;
}
export type RestsOnPathInput = {
    path: string;
}
export type RestsOnPathOutput = {
    pathname: string;
}
export type RpcCallerInput = {
    rpcName: string;
    data?: unknown | undefined;
}
export type SecretSchema_betterAuthSecret = string
export type SecretSchema_scenarioActorSecret = string
export type SeesTextInput = {
    text: string;
}
export type SeesTextOutput = {
    text: string;
}
export type SendOrderConfirmationInput = {
    orderId: string;
    email: string;
}
export type SessionHealthScenarioOutput = { email: string; userId: string; }
export type SignedInActorReachesTheAppScenarioOutput = { pathname: string; email: string; }
export type SweepsAllPagesInput = {
    repoRoot: string;
}
export type SweepsAllPagesOutput = {
    routes: string[];
}
export type VariableSchema_corsOrigins = string
export type VariableSchema_frontendUrl = string
export type WatchOrderInput = { orderId: string; }
export type WorkflowApproverInput = {
    workflowName: string;
    runId: string;
    reason: string;
    decision: unknown;
}
export type WorkflowApproverOutput = {
    ok: true;
}
export type WorkflowRunnerInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterInput = {
    workflowName: string;
    data?: unknown | undefined;
}
export type WorkflowStarterOutput = {
    runId: string;
}
export type WorkflowStatusCheckerInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamFullInput = {
    workflowName: string;
    runId: string;
}
export type WorkflowStatusStreamInput = {
    workflowName: string;
    runId: string;
}

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
  readonly 'events': {
    readonly routes: {
      readonly action: {
        readonly subscribe: ChannelHandler<RealtimeSubscribeInput, never>,
        readonly unsubscribe: ChannelHandler<RealtimeUnsubscribeInput, never>,
      },
    },
    readonly defaultMessage: never,
  },
  readonly 'orders': {
    readonly routes: {
      readonly action: {
        readonly watchOrder: ChannelHandler<WatchOrderInput, never>,
      },
    },
    readonly defaultMessage: never,
  },
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
