/**
 * This file was generated by @pikku/cli@0.12.27
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */




export type AddToBasketInput = {
    basketId: string;
    itemId: string;
    quantity: number;
}
export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; context?: string; }
export type CancelOrderInput = {
    orderId: string;
}
export type CheckItemAvailabilityInput = { itemId: string; }
export type CheckItemAvailabilityOutput = { available: boolean; stock: any; name: any; }
export type CreateCategoryInput = {
    name: string;
    slug: string;
    description?: string | undefined;
}
export type CreateCategoryOutput = {
    categoryId: string;
    name: string;
    slug: string;
}
export type CreateItemInput = {
    categoryId: string;
    name: string;
    slug: string;
    description?: string | undefined;
    priceCents: number;
    stock: number;
    imageUrl?: string | undefined;
}
export type CreateItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    priceCents: number;
    stock: number;
}
export type CreateOrderInput = {
    basketId: string;
    shippingAddress: {
        line1: string;
        line2?: string | undefined;
        city: string;
        postcode: string;
        country: string;
    };
    cardToken?: string | undefined;
}
export type CreateOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
}
export type CreateOrderWithValidationInput = { basketId: string; }
export type CreateOrderWithValidationOutput = { valid: boolean; itemCount: number; basketId: string; }
export type DeleteAgentThreadInput = { threadId: string; resourceId?: string; }
export type DeleteAgentThreadOutput = { deleted: boolean; }
export type DeleteOrderInput = { orderId: string; }
export type GetAgentThreadMessagesInput = { threadId: string; resourceId?: string; }
export type GetAgentThreadMessagesOutput = any[]
export type GetAgentThreadRunsInput = { threadId: string; resourceId?: string; }
export type GetAgentThreadRunsOutput = any[]
export type GetAgentThreadsInput = { agentName?: string; resourceId?: string; limit?: number; offset?: number; }
export type GetAgentThreadsOutput = any[]
export type GetBasketInput = {
    sessionId?: string | undefined;
}
export type GetBasketOutput = {
    basketId: string;
    items: {
        basketItemId: string;
        itemId: string;
        name: string;
        slug: string;
        priceCents: number;
        imageUrl: string | null;
        quantity: number;
        lineTotalCents: number;
    }[];
    totalCents: number;
    itemCount: number;
}
export type GetItemInput = {
    itemId: string;
}
export type GetItemOutput = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetItemV1Input = {
    itemId: string;
}
export type GetItemV1Output = {
    itemId: string;
    name: string;
    priceCents: number;
}
export type GetItemV2Input = {
    itemId: string;
}
export type GetItemV2Output = {
    itemId: string;
    name: string;
    slug: string;
    description: string | null;
    priceCents: number;
    stock: number;
    imageUrl: string | null;
    isActive: number;
    category: {
        categoryId: string;
        name: string;
        slug: string;
    };
    createdAt: string;
    updatedAt: string;
}
export type GetOrderInput = {
    orderId: string;
}
export type GetOrderOutput = {
    orderId: string;
    status: string;
    totalCents: number;
    shippingAddress: {
        [key: string]: unknown;
    };
    items: {
        itemId: string;
        name: string;
        quantity: number;
        unitPriceCents: number;
        lineTotalCents: number;
    }[];
    createdAt: string;
}
export type GetOrderThreeParamsOutput = { order: { [x: string]: any; }; viewer: string; }
export type GetProfileOutput = { userId: any; name: any; role: any; email: any; }
export type HandlePaymentWebhookInput = { text: string; raw: unknown; }
export type HandlePaymentWebhookOutput = { received: boolean; }
export type HttpPostAgentsShopOutput = { runId: string; result: string; usage: { inputTokens: number; outputTokens: number; }; }
export type HttpPostAgentsShopStreamInput = { agentName?: string; message: string; threadId: string; resourceId: string; }
export type ListCategoriesOutput = {
    categoryId: string;
    name: string;
    slug: string;
    description: string | null;
}[]
export type ListItemsInput = {
    categorySlug?: string | undefined;
    search?: string | undefined;
    limit: number;
    offset: number;
}
export type ListItemsOutput = {
    items: {
        itemId: string;
        name: string;
        slug: string;
        description: string | null;
        priceCents: number;
        stock: number;
        imageUrl: string | null;
        category: {
            categoryId: string;
            name: string;
            slug: string;
        };
    }[];
    total: number;
}
export type ListOrdersInput = {
    limit: number;
    offset: number;
}
export type ListOrdersOutput = { status: any; orderId: any; totalCents: any; createdAt: any; }[]
export type NotifyOrderShippedInput = { orderId: string; }
export type OnLowStockInput = {
    itemId: string;
    name: string;
    stock: number;
}
export type PikkuConsoleGetSecretInput = { secretId: string; }
export type PikkuConsoleGetSecretOutput = { exists: boolean; value: unknown; }
export type PikkuConsoleGetVariableInput = { variableId: string; }
export type PikkuConsoleGetVariableOutput = { exists: boolean; value: unknown; }
export type PikkuConsoleHasSecretInput = { secretId: string; }
export type PikkuConsoleHasSecretOutput = { exists: boolean; }
export type PikkuConsoleSetSecretInput = { secretId: string; value: unknown; }
export type PikkuConsoleSetSecretOutput = { success: boolean; }
export type PikkuConsoleSetVariableInput = { variableId: string; value: unknown; }
export type PikkuConsoleSetVariableOutput = { success: boolean; }
export type PlaceOrderInput = { basketId: string; }
export type PlaceOrderOutput = { orderId: any; }
export type ProcessLargeExportInput = { exportId: string; }
export type ProcessPaymentInput = { orderId: string; amountCents: number; }
export type ProcessPaymentOutput = { providerRef: string; status: "succeeded"; }
export type RemoteRPCHandlerInput = { rpcName: string; data?: unknown; }
export type RemoveFromBasketInput = {
    basketId: string;
    itemId: string;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type SecretSchema_authSecret = string
export type SecretSchema_stripeSecretKey = string
export type SendOrderConfirmationInput = {
    orderId: string;
    userId: string;
}
export type ShopLoginInput = { email: string; password: string; }
export type ShopLoginOutput = { userId: any; role: any; }
export type StockPollTriggerInput = { thresholdStock: number; }
export type StockPollTriggerOutput = { itemId: string; name: string; stock: number; }
export type UpdateItemInput = {
    itemId: string;
    name?: string | undefined;
    description?: string | undefined;
    priceCents?: number | undefined;
    stock?: number | undefined;
    imageUrl?: (string | null) | undefined;
    isActive?: boolean | undefined;
}
export type WriteAuditEventInput = {
    entityType: string;
    entityId: string;
    action: string;
    actorId?: string | undefined;
    payload?: {
        [key: string]: unknown;
    } | undefined;
}

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
  readonly 'order-status': {
    readonly routes: {
    },
    readonly defaultMessage: never,
  },
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
