/**
 * This file was generated by @pikku/cli@0.12.102
 */
import {
  pikkuChannelFunc,
  pikkuSessionlessFunc,
  wireChannel,
  wireHTTP,
  defineChannelRoutes,
} from '../../../.pikku/pikku-types.gen.js'
import { TopicRef } from './events.schemas.gen.js'

/**
 * Topic envelope clients receive: `{ topic, data }`. Functions that publish
 * events should send this shape:
 *
 *   await eventHub.publish('todo-created', null, { topic: 'todo-created', data: { todo } })
 *
 * The pikku-realtime skill covers a thin `publishEvent` helper to remove
 * the duplication; pick whichever style your project prefers.
 */

export const realtimeSubscribe = pikkuChannelFunc({
  input: TopicRef,
  func: async ({ eventHub }, { topic }, { channel }) => {
    await eventHub?.subscribe(topic, channel.channelId)
  },
})

export const realtimeUnsubscribe = pikkuChannelFunc({
  input: TopicRef,
  func: async ({ eventHub }, { topic }, { channel }) => {
    await eventHub?.unsubscribe(topic, channel.channelId)
  },
})

// Pikku dispatches by the `action` field; client sends
//   { action: 'subscribe',   topic: 'todo-created' }
//   { action: 'unsubscribe', topic: 'todo-created' }
export const realtimeRoutes = defineChannelRoutes({
  subscribe: realtimeSubscribe,
  unsubscribe: realtimeUnsubscribe,
})

wireChannel({
  name: 'events',
  route: '/events',
  auth: false,
  onMessageWiring: {
    action: realtimeRoutes,
  },
  tags: ['pikku:realtime'],
})

/**
 * SSE per-topic stream. One connection = one subscription. The eventHub
 * cleans up automatically when the channel closes (onChannelClosed).
 */
export const realtimeEventStream = pikkuSessionlessFunc({
  input: TopicRef,
  description: 'Auto-generated SSE stream for a single event-hub topic',
  func: async ({ eventHub }, { topic }, { channel }) => {
    if (!channel) {
      throw new Error('Realtime SSE handler invoked without a channel')
    }
    await eventHub?.subscribe(topic, channel.channelId)
    // Function returns; eventHub continues pushing via channel.send until
    // the client disconnects, at which point onChannelClosed unsubscribes.
  },
})

wireHTTP({
  method: 'get',
  route: '/events/:topic',
  func: realtimeEventStream,
  auth: false,
  sse: true,
  tags: ['pikku:realtime', 'sse'],
})
