/**
 * This file was generated by @pikku/cli@0.12.99
 */
import { LocalMetaService } from '@pikku/core/services/local-meta'

export class PikkuMetaService extends LocalMetaService {
  constructor() {
    super('/root/pikku-templates/online-shop/packages/functions/.pikku')
  }
}
