/**
 * This file was generated by @pikku/cli@0.12.102
 */
import './pikku-bootstrap.gen.js'
import './scenarios/schemas/register.gen.js'
import './scenarios/pikku-scenario-functions-meta.gen.js'
import './scenarios/pikku-scenario-functions.gen.js'
import './scenarios/pikku-scenario-wirings-meta.gen.js'
import './scenarios/pikku-scenario-wirings.gen.js'