/**
 * This file was generated by @pikku/cli@0.12.93
 */
import type { SingletonServices } from '../src/application-types.d.js'
import type { Services } from '../src/application-types.d.js'

// Singleton services map: true if required, false if available but unused
export const requiredSingletonServices = {
  'agentRunService': true,
  'aiAgentRunner': true,
  'aiEmbedding': false,
  'aiRunState': true,
  'aiStorage': true,
  'audit': true,
  'auditLog': false,
  'auth': true,
  'config': true,
  'content': false,
  'coverageService': false,
  'credentialService': false,
  'deploymentService': false,
  'emailService': false,
  'eventHub': true,
  'jwt': false,
  'kysely': true,
  'logger': true,
  'metaService': false,
  'paymentService': true,
  'queueService': true,
  'schedulerService': true,
  'schema': true,
  'scopeService': false,
  'secrets': true,
  'sessionStore': false,
  'variables': true,
  'webhookService': false,
  'workflowRunService': true,
  'workflowService': true,
} as const

// Wire services map: true if required, false if available but unused
export const requiredWireServices = {
} as const

// Type exports
export type RequiredSingletonServices = Required<Pick<SingletonServices, 'agentRunService' | 'aiAgentRunner' | 'aiRunState' | 'aiStorage' | 'audit' | 'auth' | 'config' | 'eventHub' | 'kysely' | 'logger' | 'paymentService' | 'queueService' | 'schedulerService' | 'schema' | 'secrets' | 'variables' | 'workflowRunService' | 'workflowService'>> & Partial<Omit<SingletonServices, 'agentRunService' | 'aiAgentRunner' | 'aiRunState' | 'aiStorage' | 'audit' | 'auth' | 'config' | 'eventHub' | 'kysely' | 'logger' | 'paymentService' | 'queueService' | 'schedulerService' | 'schema' | 'secrets' | 'variables' | 'workflowRunService' | 'workflowService'>>

export type RequiredWireServices = Partial<Services>
