/**
 * This file was generated by @pikku/cli@0.12.93
 */
import { LocalMetaService } from '@pikku/core/services/local-meta'

export class PikkuMetaService extends LocalMetaService {
  constructor() {
    super('/private/tmp/claude-501/-Users-yasser-git-pikku/826f30f1-670b-4be2-be0c-b0ea1529b795/scratchpad/tpl/packages/functions/.pikku')
  }
}
