/**
 * This file was generated by @pikku/cli@0.12.102
 */
import { TypedSecretService as CoreTypedSecretService, type CredentialMeta } from '@pikku/core/services'
import type { SecretService } from '@pikku/core/services'
import type { SecretDefinitionsMeta } from '@pikku/core/secret'
import secretsMeta from './pikku-secrets-meta.gen.json' with { type: 'json' }
import type { z } from 'zod'
import { ScenarioActorSecretSchema } from '../scopes/pikku-personas-secrets.gen.js'
import { BetterAuthSecretSchema } from '../../src/scaffold/auth/auth-secrets.gen.js'
import { StripeKeySchema } from '../../src/wirings/shop.secret.js'

/**
 * Every secret declared in this package.
 *
 * Read from the metadata sidecar rather than inlined, so that the import above
 * forces tsc to emit the .json alongside this file. An addon publishes only its
 * compiled output, and a host reads that .json to discover the addon's declared
 * secrets — an uncopied sidecar leaves them invisible to the host.
 */
export const SECRETS_META: SecretDefinitionsMeta =
  secretsMeta as SecretDefinitionsMeta

export interface CredentialsMap {
  'SCENARIO_ACTOR_SECRET': z.infer<typeof ScenarioActorSecretSchema>
  'BETTER_AUTH_SECRET': z.infer<typeof BetterAuthSecretSchema>
  'STRIPE_SECRET_KEY': z.infer<typeof StripeKeySchema>
}

export type SecretId = keyof CredentialsMap

const CREDENTIALS_META: Record<string, CredentialMeta> = {
  'SCENARIO_ACTOR_SECRET': { name: 'scenarioActorSecret', displayName: "Scenario Actor Secret" },
  'BETTER_AUTH_SECRET': { name: 'betterAuthSecret', displayName: "Better Auth Secret" },
  'STRIPE_SECRET_KEY': { name: 'stripeSecretKey', displayName: "Stripe Secret Key" }
}

export class TypedSecretService extends CoreTypedSecretService<CredentialsMap> {
  constructor(secrets: SecretService) {
    super(secrets, CREDENTIALS_META)
  }
}
