/**
 * This file was generated by @pikku/cli@0.12.27
 */
import { TypedSecretService as CoreTypedSecretService, type CredentialMeta } from '@pikku/core/services'
import type { SecretService } from '@pikku/core/services'
import type { z } from 'zod'
import { AuthSecretSchema, StripeKeySchema } from '../../src/wirings/shop.secret.js'

export interface CredentialsMap {
  'AUTH_SECRET': z.infer<typeof AuthSecretSchema>
  'STRIPE_SECRET_KEY': z.infer<typeof StripeKeySchema>
}

export type SecretId = keyof CredentialsMap

const CREDENTIALS_META: Record<string, CredentialMeta> = {
  'AUTH_SECRET': { name: 'authSecret', displayName: 'Auth Secret' },
  'STRIPE_SECRET_KEY': { name: 'stripeSecretKey', displayName: 'Stripe Secret Key' }
}

export class TypedSecretService extends CoreTypedSecretService<CredentialsMap> {
  constructor(secrets: SecretService) {
    super(secrets, CREDENTIALS_META)
  }
}
