/**
 * This file was generated by @pikku/cli@0.12.102
 */
export { defineSecret } from '@pikku/core/secret'
export type { CoreSecret, SecretDefinitionMeta, SecretDefinitionsMeta } from '@pikku/core/secret'
